// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: api/v1/hub.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeyManagementService_BindKey_FullMethodName    = "/digitalkey.hub.v1.KeyManagementService/BindKey"
	KeyManagementService_UnbindKey_FullMethodName  = "/digitalkey.hub.v1.KeyManagementService/UnbindKey"
	KeyManagementService_SuspendKey_FullMethodName = "/digitalkey.hub.v1.KeyManagementService/SuspendKey"
	KeyManagementService_ResumeKey_FullMethodName  = "/digitalkey.hub.v1.KeyManagementService/ResumeKey"
	KeyManagementService_RevokeKey_FullMethodName  = "/digitalkey.hub.v1.KeyManagementService/RevokeKey"
	KeyManagementService_RenewKey_FullMethodName   = "/digitalkey.hub.v1.KeyManagementService/RenewKey"
	KeyManagementService_GetKey_FullMethodName     = "/digitalkey.hub.v1.KeyManagementService/GetKey"
	KeyManagementService_ListKeys_FullMethodName   = "/digitalkey.hub.v1.KeyManagementService/ListKeys"
)

// KeyManagementServiceClient is the client API for KeyManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeyManagementServiceClient interface {
	// 密钥绑定
	BindKey(ctx context.Context, in *BindKeyRequest, opts ...grpc.CallOption) (*BindKeyResponse, error)
	// 密钥解绑
	UnbindKey(ctx context.Context, in *UnbindKeyRequest, opts ...grpc.CallOption) (*UnbindKeyResponse, error)
	// 密钥挂起/恢复
	SuspendKey(ctx context.Context, in *SuspendKeyRequest, opts ...grpc.CallOption) (*SuspendKeyResponse, error)
	ResumeKey(ctx context.Context, in *ResumeKeyRequest, opts ...grpc.CallOption) (*ResumeKeyResponse, error)
	// 密钥撤销
	RevokeKey(ctx context.Context, in *RevokeKeyRequest, opts ...grpc.CallOption) (*RevokeKeyResponse, error)
	// 密钥续期
	RenewKey(ctx context.Context, in *RenewKeyRequest, opts ...grpc.CallOption) (*RenewKeyResponse, error)
	// 查询密钥
	GetKey(ctx context.Context, in *GetKeyRequest, opts ...grpc.CallOption) (*GetKeyResponse, error)
	ListKeys(ctx context.Context, in *ListKeysRequest, opts ...grpc.CallOption) (*ListKeysResponse, error)
}

type keyManagementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyManagementServiceClient(cc grpc.ClientConnInterface) KeyManagementServiceClient {
	return &keyManagementServiceClient{cc}
}

func (c *keyManagementServiceClient) BindKey(ctx context.Context, in *BindKeyRequest, opts ...grpc.CallOption) (*BindKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindKeyResponse)
	err := c.cc.Invoke(ctx, KeyManagementService_BindKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyManagementServiceClient) UnbindKey(ctx context.Context, in *UnbindKeyRequest, opts ...grpc.CallOption) (*UnbindKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnbindKeyResponse)
	err := c.cc.Invoke(ctx, KeyManagementService_UnbindKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyManagementServiceClient) SuspendKey(ctx context.Context, in *SuspendKeyRequest, opts ...grpc.CallOption) (*SuspendKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuspendKeyResponse)
	err := c.cc.Invoke(ctx, KeyManagementService_SuspendKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyManagementServiceClient) ResumeKey(ctx context.Context, in *ResumeKeyRequest, opts ...grpc.CallOption) (*ResumeKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResumeKeyResponse)
	err := c.cc.Invoke(ctx, KeyManagementService_ResumeKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyManagementServiceClient) RevokeKey(ctx context.Context, in *RevokeKeyRequest, opts ...grpc.CallOption) (*RevokeKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeKeyResponse)
	err := c.cc.Invoke(ctx, KeyManagementService_RevokeKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyManagementServiceClient) RenewKey(ctx context.Context, in *RenewKeyRequest, opts ...grpc.CallOption) (*RenewKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewKeyResponse)
	err := c.cc.Invoke(ctx, KeyManagementService_RenewKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyManagementServiceClient) GetKey(ctx context.Context, in *GetKeyRequest, opts ...grpc.CallOption) (*GetKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeyResponse)
	err := c.cc.Invoke(ctx, KeyManagementService_GetKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyManagementServiceClient) ListKeys(ctx context.Context, in *ListKeysRequest, opts ...grpc.CallOption) (*ListKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListKeysResponse)
	err := c.cc.Invoke(ctx, KeyManagementService_ListKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyManagementServiceServer is the server API for KeyManagementService service.
// All implementations must embed UnimplementedKeyManagementServiceServer
// for forward compatibility.
type KeyManagementServiceServer interface {
	// 密钥绑定
	BindKey(context.Context, *BindKeyRequest) (*BindKeyResponse, error)
	// 密钥解绑
	UnbindKey(context.Context, *UnbindKeyRequest) (*UnbindKeyResponse, error)
	// 密钥挂起/恢复
	SuspendKey(context.Context, *SuspendKeyRequest) (*SuspendKeyResponse, error)
	ResumeKey(context.Context, *ResumeKeyRequest) (*ResumeKeyResponse, error)
	// 密钥撤销
	RevokeKey(context.Context, *RevokeKeyRequest) (*RevokeKeyResponse, error)
	// 密钥续期
	RenewKey(context.Context, *RenewKeyRequest) (*RenewKeyResponse, error)
	// 查询密钥
	GetKey(context.Context, *GetKeyRequest) (*GetKeyResponse, error)
	ListKeys(context.Context, *ListKeysRequest) (*ListKeysResponse, error)
	mustEmbedUnimplementedKeyManagementServiceServer()
}

// UnimplementedKeyManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyManagementServiceServer struct{}

func (UnimplementedKeyManagementServiceServer) BindKey(context.Context, *BindKeyRequest) (*BindKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BindKey not implemented")
}
func (UnimplementedKeyManagementServiceServer) UnbindKey(context.Context, *UnbindKeyRequest) (*UnbindKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnbindKey not implemented")
}
func (UnimplementedKeyManagementServiceServer) SuspendKey(context.Context, *SuspendKeyRequest) (*SuspendKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SuspendKey not implemented")
}
func (UnimplementedKeyManagementServiceServer) ResumeKey(context.Context, *ResumeKeyRequest) (*ResumeKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeKey not implemented")
}
func (UnimplementedKeyManagementServiceServer) RevokeKey(context.Context, *RevokeKeyRequest) (*RevokeKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeKey not implemented")
}
func (UnimplementedKeyManagementServiceServer) RenewKey(context.Context, *RenewKeyRequest) (*RenewKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RenewKey not implemented")
}
func (UnimplementedKeyManagementServiceServer) GetKey(context.Context, *GetKeyRequest) (*GetKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKey not implemented")
}
func (UnimplementedKeyManagementServiceServer) ListKeys(context.Context, *ListKeysRequest) (*ListKeysResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListKeys not implemented")
}
func (UnimplementedKeyManagementServiceServer) mustEmbedUnimplementedKeyManagementServiceServer() {}
func (UnimplementedKeyManagementServiceServer) testEmbeddedByValue()                              {}

// UnsafeKeyManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyManagementServiceServer will
// result in compilation errors.
type UnsafeKeyManagementServiceServer interface {
	mustEmbedUnimplementedKeyManagementServiceServer()
}

func RegisterKeyManagementServiceServer(s grpc.ServiceRegistrar, srv KeyManagementServiceServer) {
	// If the following call panics, it indicates UnimplementedKeyManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyManagementService_ServiceDesc, srv)
}

func _KeyManagementService_BindKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyManagementServiceServer).BindKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyManagementService_BindKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyManagementServiceServer).BindKey(ctx, req.(*BindKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyManagementService_UnbindKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnbindKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyManagementServiceServer).UnbindKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyManagementService_UnbindKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyManagementServiceServer).UnbindKey(ctx, req.(*UnbindKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyManagementService_SuspendKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuspendKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyManagementServiceServer).SuspendKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyManagementService_SuspendKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyManagementServiceServer).SuspendKey(ctx, req.(*SuspendKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyManagementService_ResumeKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyManagementServiceServer).ResumeKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyManagementService_ResumeKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyManagementServiceServer).ResumeKey(ctx, req.(*ResumeKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyManagementService_RevokeKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyManagementServiceServer).RevokeKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyManagementService_RevokeKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyManagementServiceServer).RevokeKey(ctx, req.(*RevokeKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyManagementService_RenewKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyManagementServiceServer).RenewKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyManagementService_RenewKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyManagementServiceServer).RenewKey(ctx, req.(*RenewKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyManagementService_GetKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyManagementServiceServer).GetKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyManagementService_GetKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyManagementServiceServer).GetKey(ctx, req.(*GetKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyManagementService_ListKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyManagementServiceServer).ListKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyManagementService_ListKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyManagementServiceServer).ListKeys(ctx, req.(*ListKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyManagementService_ServiceDesc is the grpc.ServiceDesc for KeyManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "digitalkey.hub.v1.KeyManagementService",
	HandlerType: (*KeyManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "BindKey",
			Handler:    _KeyManagementService_BindKey_Handler,
		},
		{
			MethodName: "UnbindKey",
			Handler:    _KeyManagementService_UnbindKey_Handler,
		},
		{
			MethodName: "SuspendKey",
			Handler:    _KeyManagementService_SuspendKey_Handler,
		},
		{
			MethodName: "ResumeKey",
			Handler:    _KeyManagementService_ResumeKey_Handler,
		},
		{
			MethodName: "RevokeKey",
			Handler:    _KeyManagementService_RevokeKey_Handler,
		},
		{
			MethodName: "RenewKey",
			Handler:    _KeyManagementService_RenewKey_Handler,
		},
		{
			MethodName: "GetKey",
			Handler:    _KeyManagementService_GetKey_Handler,
		},
		{
			MethodName: "ListKeys",
			Handler:    _KeyManagementService_ListKeys_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/hub.proto",
}

const (
	KeyShareService_CreateShare_FullMethodName = "/digitalkey.hub.v1.KeyShareService/CreateShare"
	KeyShareService_AcceptShare_FullMethodName = "/digitalkey.hub.v1.KeyShareService/AcceptShare"
	KeyShareService_CancelShare_FullMethodName = "/digitalkey.hub.v1.KeyShareService/CancelShare"
	KeyShareService_GetShare_FullMethodName    = "/digitalkey.hub.v1.KeyShareService/GetShare"
)

// KeyShareServiceClient is the client API for KeyShareService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeyShareServiceClient interface {
	CreateShare(ctx context.Context, in *CreateShareRequest, opts ...grpc.CallOption) (*CreateShareResponse, error)
	AcceptShare(ctx context.Context, in *AcceptShareRequest, opts ...grpc.CallOption) (*AcceptShareResponse, error)
	CancelShare(ctx context.Context, in *CancelShareRequest, opts ...grpc.CallOption) (*CancelShareResponse, error)
	GetShare(ctx context.Context, in *GetShareRequest, opts ...grpc.CallOption) (*GetShareResponse, error)
}

type keyShareServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyShareServiceClient(cc grpc.ClientConnInterface) KeyShareServiceClient {
	return &keyShareServiceClient{cc}
}

func (c *keyShareServiceClient) CreateShare(ctx context.Context, in *CreateShareRequest, opts ...grpc.CallOption) (*CreateShareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateShareResponse)
	err := c.cc.Invoke(ctx, KeyShareService_CreateShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyShareServiceClient) AcceptShare(ctx context.Context, in *AcceptShareRequest, opts ...grpc.CallOption) (*AcceptShareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptShareResponse)
	err := c.cc.Invoke(ctx, KeyShareService_AcceptShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyShareServiceClient) CancelShare(ctx context.Context, in *CancelShareRequest, opts ...grpc.CallOption) (*CancelShareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelShareResponse)
	err := c.cc.Invoke(ctx, KeyShareService_CancelShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyShareServiceClient) GetShare(ctx context.Context, in *GetShareRequest, opts ...grpc.CallOption) (*GetShareResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShareResponse)
	err := c.cc.Invoke(ctx, KeyShareService_GetShare_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyShareServiceServer is the server API for KeyShareService service.
// All implementations must embed UnimplementedKeyShareServiceServer
// for forward compatibility.
type KeyShareServiceServer interface {
	CreateShare(context.Context, *CreateShareRequest) (*CreateShareResponse, error)
	AcceptShare(context.Context, *AcceptShareRequest) (*AcceptShareResponse, error)
	CancelShare(context.Context, *CancelShareRequest) (*CancelShareResponse, error)
	GetShare(context.Context, *GetShareRequest) (*GetShareResponse, error)
	mustEmbedUnimplementedKeyShareServiceServer()
}

// UnimplementedKeyShareServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyShareServiceServer struct{}

func (UnimplementedKeyShareServiceServer) CreateShare(context.Context, *CreateShareRequest) (*CreateShareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateShare not implemented")
}
func (UnimplementedKeyShareServiceServer) AcceptShare(context.Context, *AcceptShareRequest) (*AcceptShareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AcceptShare not implemented")
}
func (UnimplementedKeyShareServiceServer) CancelShare(context.Context, *CancelShareRequest) (*CancelShareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelShare not implemented")
}
func (UnimplementedKeyShareServiceServer) GetShare(context.Context, *GetShareRequest) (*GetShareResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShare not implemented")
}
func (UnimplementedKeyShareServiceServer) mustEmbedUnimplementedKeyShareServiceServer() {}
func (UnimplementedKeyShareServiceServer) testEmbeddedByValue()                         {}

// UnsafeKeyShareServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyShareServiceServer will
// result in compilation errors.
type UnsafeKeyShareServiceServer interface {
	mustEmbedUnimplementedKeyShareServiceServer()
}

func RegisterKeyShareServiceServer(s grpc.ServiceRegistrar, srv KeyShareServiceServer) {
	// If the following call panics, it indicates UnimplementedKeyShareServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyShareService_ServiceDesc, srv)
}

func _KeyShareService_CreateShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyShareServiceServer).CreateShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyShareService_CreateShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyShareServiceServer).CreateShare(ctx, req.(*CreateShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyShareService_AcceptShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyShareServiceServer).AcceptShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyShareService_AcceptShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyShareServiceServer).AcceptShare(ctx, req.(*AcceptShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyShareService_CancelShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyShareServiceServer).CancelShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyShareService_CancelShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyShareServiceServer).CancelShare(ctx, req.(*CancelShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyShareService_GetShare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShareRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyShareServiceServer).GetShare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyShareService_GetShare_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyShareServiceServer).GetShare(ctx, req.(*GetShareRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyShareService_ServiceDesc is the grpc.ServiceDesc for KeyShareService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyShareService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "digitalkey.hub.v1.KeyShareService",
	HandlerType: (*KeyShareServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateShare",
			Handler:    _KeyShareService_CreateShare_Handler,
		},
		{
			MethodName: "AcceptShare",
			Handler:    _KeyShareService_AcceptShare_Handler,
		},
		{
			MethodName: "CancelShare",
			Handler:    _KeyShareService_CancelShare_Handler,
		},
		{
			MethodName: "GetShare",
			Handler:    _KeyShareService_GetShare_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/hub.proto",
}

const (
	VehicleControlService_SendCommand_FullMethodName  = "/digitalkey.hub.v1.VehicleControlService/SendCommand"
	VehicleControlService_StreamStatus_FullMethodName = "/digitalkey.hub.v1.VehicleControlService/StreamStatus"
)

// VehicleControlServiceClient is the client API for VehicleControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VehicleControlServiceClient interface {
	SendCommand(ctx context.Context, in *ControlCommandRequest, opts ...grpc.CallOption) (*ControlCommandResponse, error)
	StreamStatus(ctx context.Context, in *VehicleStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VehicleStatusUpdate], error)
}

type vehicleControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVehicleControlServiceClient(cc grpc.ClientConnInterface) VehicleControlServiceClient {
	return &vehicleControlServiceClient{cc}
}

func (c *vehicleControlServiceClient) SendCommand(ctx context.Context, in *ControlCommandRequest, opts ...grpc.CallOption) (*ControlCommandResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlCommandResponse)
	err := c.cc.Invoke(ctx, VehicleControlService_SendCommand_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vehicleControlServiceClient) StreamStatus(ctx context.Context, in *VehicleStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[VehicleStatusUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &VehicleControlService_ServiceDesc.Streams[0], VehicleControlService_StreamStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[VehicleStatusRequest, VehicleStatusUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VehicleControlService_StreamStatusClient = grpc.ServerStreamingClient[VehicleStatusUpdate]

// VehicleControlServiceServer is the server API for VehicleControlService service.
// All implementations must embed UnimplementedVehicleControlServiceServer
// for forward compatibility.
type VehicleControlServiceServer interface {
	SendCommand(context.Context, *ControlCommandRequest) (*ControlCommandResponse, error)
	StreamStatus(*VehicleStatusRequest, grpc.ServerStreamingServer[VehicleStatusUpdate]) error
	mustEmbedUnimplementedVehicleControlServiceServer()
}

// UnimplementedVehicleControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVehicleControlServiceServer struct{}

func (UnimplementedVehicleControlServiceServer) SendCommand(context.Context, *ControlCommandRequest) (*ControlCommandResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendCommand not implemented")
}
func (UnimplementedVehicleControlServiceServer) StreamStatus(*VehicleStatusRequest, grpc.ServerStreamingServer[VehicleStatusUpdate]) error {
	return status.Error(codes.Unimplemented, "method StreamStatus not implemented")
}
func (UnimplementedVehicleControlServiceServer) mustEmbedUnimplementedVehicleControlServiceServer() {}
func (UnimplementedVehicleControlServiceServer) testEmbeddedByValue()                               {}

// UnsafeVehicleControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VehicleControlServiceServer will
// result in compilation errors.
type UnsafeVehicleControlServiceServer interface {
	mustEmbedUnimplementedVehicleControlServiceServer()
}

func RegisterVehicleControlServiceServer(s grpc.ServiceRegistrar, srv VehicleControlServiceServer) {
	// If the following call panics, it indicates UnimplementedVehicleControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VehicleControlService_ServiceDesc, srv)
}

func _VehicleControlService_SendCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VehicleControlServiceServer).SendCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VehicleControlService_SendCommand_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VehicleControlServiceServer).SendCommand(ctx, req.(*ControlCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VehicleControlService_StreamStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(VehicleStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(VehicleControlServiceServer).StreamStatus(m, &grpc.GenericServerStream[VehicleStatusRequest, VehicleStatusUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type VehicleControlService_StreamStatusServer = grpc.ServerStreamingServer[VehicleStatusUpdate]

// VehicleControlService_ServiceDesc is the grpc.ServiceDesc for VehicleControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VehicleControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "digitalkey.hub.v1.VehicleControlService",
	HandlerType: (*VehicleControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendCommand",
			Handler:    _VehicleControlService_SendCommand_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamStatus",
			Handler:       _VehicleControlService_StreamStatus_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/v1/hub.proto",
}

const (
	HubTransportService_ForwardToVendor_FullMethodName = "/digitalkey.hub.v1.HubTransportService/ForwardToVendor"
	HubTransportService_VendorCallback_FullMethodName  = "/digitalkey.hub.v1.HubTransportService/VendorCallback"
	HubTransportService_HealthCheck_FullMethodName     = "/digitalkey.hub.v1.HubTransportService/HealthCheck"
)

// HubTransportServiceClient is the client API for HubTransportService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HubTransportServiceClient interface {
	// DKCS调用HUB: 转发到手机厂商云端
	ForwardToVendor(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*ForwardResponse, error)
	// 手机厂商回调HUB
	VendorCallback(ctx context.Context, in *CallbackRequest, opts ...grpc.CallOption) (*CallbackResponse, error)
	// 健康检查
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type hubTransportServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHubTransportServiceClient(cc grpc.ClientConnInterface) HubTransportServiceClient {
	return &hubTransportServiceClient{cc}
}

func (c *hubTransportServiceClient) ForwardToVendor(ctx context.Context, in *ForwardRequest, opts ...grpc.CallOption) (*ForwardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ForwardResponse)
	err := c.cc.Invoke(ctx, HubTransportService_ForwardToVendor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubTransportServiceClient) VendorCallback(ctx context.Context, in *CallbackRequest, opts ...grpc.CallOption) (*CallbackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CallbackResponse)
	err := c.cc.Invoke(ctx, HubTransportService_VendorCallback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hubTransportServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, HubTransportService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HubTransportServiceServer is the server API for HubTransportService service.
// All implementations must embed UnimplementedHubTransportServiceServer
// for forward compatibility.
type HubTransportServiceServer interface {
	// DKCS调用HUB: 转发到手机厂商云端
	ForwardToVendor(context.Context, *ForwardRequest) (*ForwardResponse, error)
	// 手机厂商回调HUB
	VendorCallback(context.Context, *CallbackRequest) (*CallbackResponse, error)
	// 健康检查
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedHubTransportServiceServer()
}

// UnimplementedHubTransportServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHubTransportServiceServer struct{}

func (UnimplementedHubTransportServiceServer) ForwardToVendor(context.Context, *ForwardRequest) (*ForwardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ForwardToVendor not implemented")
}
func (UnimplementedHubTransportServiceServer) VendorCallback(context.Context, *CallbackRequest) (*CallbackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VendorCallback not implemented")
}
func (UnimplementedHubTransportServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedHubTransportServiceServer) mustEmbedUnimplementedHubTransportServiceServer() {}
func (UnimplementedHubTransportServiceServer) testEmbeddedByValue()                             {}

// UnsafeHubTransportServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HubTransportServiceServer will
// result in compilation errors.
type UnsafeHubTransportServiceServer interface {
	mustEmbedUnimplementedHubTransportServiceServer()
}

func RegisterHubTransportServiceServer(s grpc.ServiceRegistrar, srv HubTransportServiceServer) {
	// If the following call panics, it indicates UnimplementedHubTransportServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HubTransportService_ServiceDesc, srv)
}

func _HubTransportService_ForwardToVendor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubTransportServiceServer).ForwardToVendor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubTransportService_ForwardToVendor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubTransportServiceServer).ForwardToVendor(ctx, req.(*ForwardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubTransportService_VendorCallback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CallbackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubTransportServiceServer).VendorCallback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubTransportService_VendorCallback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubTransportServiceServer).VendorCallback(ctx, req.(*CallbackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HubTransportService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HubTransportServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HubTransportService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HubTransportServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HubTransportService_ServiceDesc is the grpc.ServiceDesc for HubTransportService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HubTransportService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "digitalkey.hub.v1.HubTransportService",
	HandlerType: (*HubTransportServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ForwardToVendor",
			Handler:    _HubTransportService_ForwardToVendor_Handler,
		},
		{
			MethodName: "VendorCallback",
			Handler:    _HubTransportService_VendorCallback_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _HubTransportService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/hub.proto",
}
