// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: relay.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.relay.v1;

@kotlin.jvm.JvmName("-initializecreateMailboxResponse")
public inline fun createMailboxResponse(block: digitalkey.relay.v1.CreateMailboxResponseKt.Dsl.() -> kotlin.Unit): digitalkey.relay.v1.Relay.CreateMailboxResponse =
  digitalkey.relay.v1.CreateMailboxResponseKt.Dsl._create(digitalkey.relay.v1.Relay.CreateMailboxResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.relay.v1.CreateMailboxResponse`
 */
public object CreateMailboxResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.relay.v1.Relay.CreateMailboxResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.relay.v1.Relay.CreateMailboxResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.relay.v1.Relay.CreateMailboxResponse = _builder.build()

    /**
     * `string mailbox_id = 1;`
     */
    public var mailboxId: kotlin.String
      @kotlin.jvm.JvmName("getMailboxId")
        get() = _builder.mailboxId
      @kotlin.jvm.JvmName("setMailboxId")
        set(value) {
        _builder.mailboxId = value
      }
    /**
     * `string mailbox_id = 1;`
     */
    public fun clearMailboxId() {
      _builder.clearMailboxId()
    }

    /**
     * ```
     * 完整分享 URL（含 Secret fragment）
     * ```
     *
     * `string sharing_url = 2;`
     */
    public var sharingUrl: kotlin.String
      @kotlin.jvm.JvmName("getSharingUrl")
        get() = _builder.sharingUrl
      @kotlin.jvm.JvmName("setSharingUrl")
        set(value) {
        _builder.sharingUrl = value
      }
    /**
     * ```
     * 完整分享 URL（含 Secret fragment）
     * ```
     *
     * `string sharing_url = 2;`
     */
    public fun clearSharingUrl() {
      _builder.clearSharingUrl()
    }

    /**
     * ```
     * unix millis
     * ```
     *
     * `int64 expires_at = 3;`
     */
    public var expiresAt: kotlin.Long
      @kotlin.jvm.JvmName("getExpiresAt")
        get() = _builder.expiresAt
      @kotlin.jvm.JvmName("setExpiresAt")
        set(value) {
        _builder.expiresAt = value
      }
    /**
     * ```
     * unix millis
     * ```
     *
     * `int64 expires_at = 3;`
     */
    public fun clearExpiresAt() {
      _builder.clearExpiresAt()
    }

    /**
     * `string error_code = 4;`
     */
    public var errorCode: kotlin.String
      @kotlin.jvm.JvmName("getErrorCode")
        get() = _builder.errorCode
      @kotlin.jvm.JvmName("setErrorCode")
        set(value) {
        _builder.errorCode = value
      }
    /**
     * `string error_code = 4;`
     */
    public fun clearErrorCode() {
      _builder.clearErrorCode()
    }

    /**
     * `string error_msg = 5;`
     */
    public var errorMsg: kotlin.String
      @kotlin.jvm.JvmName("getErrorMsg")
        get() = _builder.errorMsg
      @kotlin.jvm.JvmName("setErrorMsg")
        set(value) {
        _builder.errorMsg = value
      }
    /**
     * `string error_msg = 5;`
     */
    public fun clearErrorMsg() {
      _builder.clearErrorMsg()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.relay.v1.Relay.CreateMailboxResponse.copy(block: `digitalkey.relay.v1`.CreateMailboxResponseKt.Dsl.() -> kotlin.Unit): digitalkey.relay.v1.Relay.CreateMailboxResponse =
  `digitalkey.relay.v1`.CreateMailboxResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

