// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: relay.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.relay.v1;

@kotlin.jvm.JvmName("-initializecreateMailboxRequest")
public inline fun createMailboxRequest(block: digitalkey.relay.v1.CreateMailboxRequestKt.Dsl.() -> kotlin.Unit): digitalkey.relay.v1.Relay.CreateMailboxRequest =
  digitalkey.relay.v1.CreateMailboxRequestKt.Dsl._create(digitalkey.relay.v1.Relay.CreateMailboxRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.relay.v1.CreateMailboxRequest`
 */
public object CreateMailboxRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.relay.v1.Relay.CreateMailboxRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.relay.v1.Relay.CreateMailboxRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.relay.v1.Relay.CreateMailboxRequest = _builder.build()

    /**
     * ```
     * 加密的 provisioning info (JSON format per §11.3)
     * ```
     *
     * `bytes payload = 1;`
     */
    public var payload: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getPayload")
        get() = _builder.payload
      @kotlin.jvm.JvmName("setPayload")
        set(value) {
        _builder.payload = value
      }
    /**
     * ```
     * 加密的 provisioning info (JSON format per §11.3)
     * ```
     *
     * `bytes payload = 1;`
     */
    public fun clearPayload() {
      _builder.clearPayload()
    }

    /**
     * ```
     * 展示信息（车品牌、型号等）
     * ```
     *
     * `bytes display_info = 2;`
     */
    public var displayInfo: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getDisplayInfo")
        get() = _builder.displayInfo
      @kotlin.jvm.JvmName("setDisplayInfo")
        set(value) {
        _builder.displayInfo = value
      }
    /**
     * ```
     * 展示信息（车品牌、型号等）
     * ```
     *
     * `bytes display_info = 2;`
     */
    public fun clearDisplayInfo() {
      _builder.clearDisplayInfo()
    }

    /**
     * ```
     * 发送方 Push 通知 token
     * ```
     *
     * `string notification_token = 3;`
     */
    public var notificationToken: kotlin.String
      @kotlin.jvm.JvmName("getNotificationToken")
        get() = _builder.notificationToken
      @kotlin.jvm.JvmName("setNotificationToken")
        set(value) {
        _builder.notificationToken = value
      }
    /**
     * ```
     * 发送方 Push 通知 token
     * ```
     *
     * `string notification_token = 3;`
     */
    public fun clearNotificationToken() {
      _builder.clearNotificationToken()
    }

    /**
     * `string sender_device_id = 4;`
     */
    public var senderDeviceId: kotlin.String
      @kotlin.jvm.JvmName("getSenderDeviceId")
        get() = _builder.senderDeviceId
      @kotlin.jvm.JvmName("setSenderDeviceId")
        set(value) {
        _builder.senderDeviceId = value
      }
    /**
     * `string sender_device_id = 4;`
     */
    public fun clearSenderDeviceId() {
      _builder.clearSenderDeviceId()
    }

    /**
     * ```
     * e.g. "apple", "samsung"
     * ```
     *
     * `string sender_vendor = 5;`
     */
    public var senderVendor: kotlin.String
      @kotlin.jvm.JvmName("getSenderVendor")
        get() = _builder.senderVendor
      @kotlin.jvm.JvmName("setSenderVendor")
        set(value) {
        _builder.senderVendor = value
      }
    /**
     * ```
     * e.g. "apple", "samsung"
     * ```
     *
     * `string sender_vendor = 5;`
     */
    public fun clearSenderVendor() {
      _builder.clearSenderVendor()
    }

    /**
     * `.digitalkey.relay.v1.MailboxConfig config = 6;`
     */
    public var config: digitalkey.relay.v1.Relay.MailboxConfig
      @kotlin.jvm.JvmName("getConfig")
        get() = _builder.config
      @kotlin.jvm.JvmName("setConfig")
        set(value) {
        _builder.config = value
      }
    /**
     * `.digitalkey.relay.v1.MailboxConfig config = 6;`
     */
    public fun clearConfig() {
      _builder.clearConfig()
    }
    /**
     * `.digitalkey.relay.v1.MailboxConfig config = 6;`
     * @return Whether the config field is set.
     */
    public fun hasConfig(): kotlin.Boolean {
      return _builder.hasConfig()
    }

    public val CreateMailboxRequestKt.Dsl.configOrNull: digitalkey.relay.v1.Relay.MailboxConfig?
      get() = _builder.configOrNull

    /**
     * `string trace_id = 7;`
     */
    public var traceId: kotlin.String
      @kotlin.jvm.JvmName("getTraceId")
        get() = _builder.traceId
      @kotlin.jvm.JvmName("setTraceId")
        set(value) {
        _builder.traceId = value
      }
    /**
     * `string trace_id = 7;`
     */
    public fun clearTraceId() {
      _builder.clearTraceId()
    }

    /**
     * ```
     * §11.3.5: sender device attestation for cross-OEM auth
     * ```
     *
     * `bytes device_attestation = 8;`
     */
    public var deviceAttestation: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getDeviceAttestation")
        get() = _builder.deviceAttestation
      @kotlin.jvm.JvmName("setDeviceAttestation")
        set(value) {
        _builder.deviceAttestation = value
      }
    /**
     * ```
     * §11.3.5: sender device attestation for cross-OEM auth
     * ```
     *
     * `bytes device_attestation = 8;`
     */
    public fun clearDeviceAttestation() {
      _builder.clearDeviceAttestation()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.relay.v1.Relay.CreateMailboxRequest.copy(block: `digitalkey.relay.v1`.CreateMailboxRequestKt.Dsl.() -> kotlin.Unit): digitalkey.relay.v1.Relay.CreateMailboxRequest =
  `digitalkey.relay.v1`.CreateMailboxRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val digitalkey.relay.v1.Relay.CreateMailboxRequestOrBuilder.configOrNull: digitalkey.relay.v1.Relay.MailboxConfig?
  get() = if (hasConfig()) getConfig() else null

