// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: relay.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.relay.v1;

@kotlin.jvm.JvmName("-initializedeleteMailboxRequest")
public inline fun deleteMailboxRequest(block: digitalkey.relay.v1.DeleteMailboxRequestKt.Dsl.() -> kotlin.Unit): digitalkey.relay.v1.Relay.DeleteMailboxRequest =
  digitalkey.relay.v1.DeleteMailboxRequestKt.Dsl._create(digitalkey.relay.v1.Relay.DeleteMailboxRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.relay.v1.DeleteMailboxRequest`
 */
public object DeleteMailboxRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.relay.v1.Relay.DeleteMailboxRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.relay.v1.Relay.DeleteMailboxRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.relay.v1.Relay.DeleteMailboxRequest = _builder.build()

    /**
     * `string mailbox_id = 1;`
     */
    public var mailboxId: kotlin.String
      @kotlin.jvm.JvmName("getMailboxId")
        get() = _builder.mailboxId
      @kotlin.jvm.JvmName("setMailboxId")
        set(value) {
        _builder.mailboxId = value
      }
    /**
     * `string mailbox_id = 1;`
     */
    public fun clearMailboxId() {
      _builder.clearMailboxId()
    }

    /**
     * ```
     * "completed" / "cancelled" / "expired"
     * ```
     *
     * `string reason = 2;`
     */
    public var reason: kotlin.String
      @kotlin.jvm.JvmName("getReason")
        get() = _builder.reason
      @kotlin.jvm.JvmName("setReason")
        set(value) {
        _builder.reason = value
      }
    /**
     * ```
     * "completed" / "cancelled" / "expired"
     * ```
     *
     * `string reason = 2;`
     */
    public fun clearReason() {
      _builder.clearReason()
    }

    /**
     * `string deleter_device_id = 3;`
     */
    public var deleterDeviceId: kotlin.String
      @kotlin.jvm.JvmName("getDeleterDeviceId")
        get() = _builder.deleterDeviceId
      @kotlin.jvm.JvmName("setDeleterDeviceId")
        set(value) {
        _builder.deleterDeviceId = value
      }
    /**
     * `string deleter_device_id = 3;`
     */
    public fun clearDeleterDeviceId() {
      _builder.clearDeleterDeviceId()
    }

    /**
     * `string trace_id = 4;`
     */
    public var traceId: kotlin.String
      @kotlin.jvm.JvmName("getTraceId")
        get() = _builder.traceId
      @kotlin.jvm.JvmName("setTraceId")
        set(value) {
        _builder.traceId = value
      }
    /**
     * `string trace_id = 4;`
     */
    public fun clearTraceId() {
      _builder.clearTraceId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.relay.v1.Relay.DeleteMailboxRequest.copy(block: `digitalkey.relay.v1`.DeleteMailboxRequestKt.Dsl.() -> kotlin.Unit): digitalkey.relay.v1.Relay.DeleteMailboxRequest =
  `digitalkey.relay.v1`.DeleteMailboxRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

