// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: relay.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.relay.v1;

@kotlin.jvm.JvmName("-initializemailbox")
public inline fun mailbox(block: digitalkey.relay.v1.MailboxKt.Dsl.() -> kotlin.Unit): digitalkey.relay.v1.Relay.Mailbox =
  digitalkey.relay.v1.MailboxKt.Dsl._create(digitalkey.relay.v1.Relay.Mailbox.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.relay.v1.Mailbox`
 */
public object MailboxKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.relay.v1.Relay.Mailbox.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.relay.v1.Relay.Mailbox.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.relay.v1.Relay.Mailbox = _builder.build()

    /**
     * `string mailbox_id = 1;`
     */
    public var mailboxId: kotlin.String
      @kotlin.jvm.JvmName("getMailboxId")
        get() = _builder.mailboxId
      @kotlin.jvm.JvmName("setMailboxId")
        set(value) {
        _builder.mailboxId = value
      }
    /**
     * `string mailbox_id = 1;`
     */
    public fun clearMailboxId() {
      _builder.clearMailboxId()
    }

    /**
     * `.digitalkey.relay.v1.MailboxStatus status = 2;`
     */
    public var status: digitalkey.relay.v1.Relay.MailboxStatus
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    public var statusValue: kotlin.Int
      @kotlin.jvm.JvmName("getStatusValue")
        get() = _builder.statusValue
      @kotlin.jvm.JvmName("setStatusValue")
        set(value) {
        _builder.statusValue = value
      }
    /**
     * `.digitalkey.relay.v1.MailboxStatus status = 2;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `string sender_device_id = 3;`
     */
    public var senderDeviceId: kotlin.String
      @kotlin.jvm.JvmName("getSenderDeviceId")
        get() = _builder.senderDeviceId
      @kotlin.jvm.JvmName("setSenderDeviceId")
        set(value) {
        _builder.senderDeviceId = value
      }
    /**
     * `string sender_device_id = 3;`
     */
    public fun clearSenderDeviceId() {
      _builder.clearSenderDeviceId()
    }

    /**
     * `string sender_vendor = 4;`
     */
    public var senderVendor: kotlin.String
      @kotlin.jvm.JvmName("getSenderVendor")
        get() = _builder.senderVendor
      @kotlin.jvm.JvmName("setSenderVendor")
        set(value) {
        _builder.senderVendor = value
      }
    /**
     * `string sender_vendor = 4;`
     */
    public fun clearSenderVendor() {
      _builder.clearSenderVendor()
    }

    /**
     * ```
     * 发送方 push token
     * ```
     *
     * `string notification_token = 5;`
     */
    public var notificationToken: kotlin.String
      @kotlin.jvm.JvmName("getNotificationToken")
        get() = _builder.notificationToken
      @kotlin.jvm.JvmName("setNotificationToken")
        set(value) {
        _builder.notificationToken = value
      }
    /**
     * ```
     * 发送方 push token
     * ```
     *
     * `string notification_token = 5;`
     */
    public fun clearNotificationToken() {
      _builder.clearNotificationToken()
    }

    /**
     * `bytes display_info = 6;`
     */
    public var displayInfo: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getDisplayInfo")
        get() = _builder.displayInfo
      @kotlin.jvm.JvmName("setDisplayInfo")
        set(value) {
        _builder.displayInfo = value
      }
    /**
     * `bytes display_info = 6;`
     */
    public fun clearDisplayInfo() {
      _builder.clearDisplayInfo()
    }

    /**
     * ```
     * unix millis
     * ```
     *
     * `int64 created_at = 7;`
     */
    public var createdAt: kotlin.Long
      @kotlin.jvm.JvmName("getCreatedAt")
        get() = _builder.createdAt
      @kotlin.jvm.JvmName("setCreatedAt")
        set(value) {
        _builder.createdAt = value
      }
    /**
     * ```
     * unix millis
     * ```
     *
     * `int64 created_at = 7;`
     */
    public fun clearCreatedAt() {
      _builder.clearCreatedAt()
    }

    /**
     * `int64 expires_at = 8;`
     */
    public var expiresAt: kotlin.Long
      @kotlin.jvm.JvmName("getExpiresAt")
        get() = _builder.expiresAt
      @kotlin.jvm.JvmName("setExpiresAt")
        set(value) {
        _builder.expiresAt = value
      }
    /**
     * `int64 expires_at = 8;`
     */
    public fun clearExpiresAt() {
      _builder.clearExpiresAt()
    }

    /**
     * `int64 updated_at = 9;`
     */
    public var updatedAt: kotlin.Long
      @kotlin.jvm.JvmName("getUpdatedAt")
        get() = _builder.updatedAt
      @kotlin.jvm.JvmName("setUpdatedAt")
        set(value) {
        _builder.updatedAt = value
      }
    /**
     * `int64 updated_at = 9;`
     */
    public fun clearUpdatedAt() {
      _builder.clearUpdatedAt()
    }

    /**
     * `int64 version = 10;`
     */
    public var version: kotlin.Long
      @kotlin.jvm.JvmName("getVersion")
        get() = _builder.version
      @kotlin.jvm.JvmName("setVersion")
        set(value) {
        _builder.version = value
      }
    /**
     * `int64 version = 10;`
     */
    public fun clearVersion() {
      _builder.clearVersion()
    }

    /**
     * `string sharing_url = 11;`
     */
    public var sharingUrl: kotlin.String
      @kotlin.jvm.JvmName("getSharingUrl")
        get() = _builder.sharingUrl
      @kotlin.jvm.JvmName("setSharingUrl")
        set(value) {
        _builder.sharingUrl = value
      }
    /**
     * `string sharing_url = 11;`
     */
    public fun clearSharingUrl() {
      _builder.clearSharingUrl()
    }

    /**
     * ```
     * 接收方设备 ID（Relinquish 后更新）
     * ```
     *
     * `string receiver_device_id = 12;`
     */
    public var receiverDeviceId: kotlin.String
      @kotlin.jvm.JvmName("getReceiverDeviceId")
        get() = _builder.receiverDeviceId
      @kotlin.jvm.JvmName("setReceiverDeviceId")
        set(value) {
        _builder.receiverDeviceId = value
      }
    /**
     * ```
     * 接收方设备 ID（Relinquish 后更新）
     * ```
     *
     * `string receiver_device_id = 12;`
     */
    public fun clearReceiverDeviceId() {
      _builder.clearReceiverDeviceId()
    }

    /**
     * ```
     * 接收方厂商
     * ```
     *
     * `string receiver_vendor = 13;`
     */
    public var receiverVendor: kotlin.String
      @kotlin.jvm.JvmName("getReceiverVendor")
        get() = _builder.receiverVendor
      @kotlin.jvm.JvmName("setReceiverVendor")
        set(value) {
        _builder.receiverVendor = value
      }
    /**
     * ```
     * 接收方厂商
     * ```
     *
     * `string receiver_vendor = 13;`
     */
    public fun clearReceiverVendor() {
      _builder.clearReceiverVendor()
    }

    /**
     * ```
     * 当前更新次数
     * ```
     *
     * `int32 update_count = 14;`
     */
    public var updateCount: kotlin.Int
      @kotlin.jvm.JvmName("getUpdateCount")
        get() = _builder.updateCount
      @kotlin.jvm.JvmName("setUpdateCount")
        set(value) {
        _builder.updateCount = value
      }
    /**
     * ```
     * 当前更新次数
     * ```
     *
     * `int32 update_count = 14;`
     */
    public fun clearUpdateCount() {
      _builder.clearUpdateCount()
    }

    /**
     * ```
     * 最大更新次数
     * ```
     *
     * `int32 max_updates = 15;`
     */
    public var maxUpdates: kotlin.Int
      @kotlin.jvm.JvmName("getMaxUpdates")
        get() = _builder.maxUpdates
      @kotlin.jvm.JvmName("setMaxUpdates")
        set(value) {
        _builder.maxUpdates = value
      }
    /**
     * ```
     * 最大更新次数
     * ```
     *
     * `int32 max_updates = 15;`
     */
    public fun clearMaxUpdates() {
      _builder.clearMaxUpdates()
    }

    /**
     * ```
     * §11.3.5: sender device attestation (persisted)
     * ```
     *
     * `bytes device_attestation = 16;`
     */
    public var deviceAttestation: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getDeviceAttestation")
        get() = _builder.deviceAttestation
      @kotlin.jvm.JvmName("setDeviceAttestation")
        set(value) {
        _builder.deviceAttestation = value
      }
    /**
     * ```
     * §11.3.5: sender device attestation (persisted)
     * ```
     *
     * `bytes device_attestation = 16;`
     */
    public fun clearDeviceAttestation() {
      _builder.clearDeviceAttestation()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.relay.v1.Relay.Mailbox.copy(block: `digitalkey.relay.v1`.MailboxKt.Dsl.() -> kotlin.Unit): digitalkey.relay.v1.Relay.Mailbox =
  `digitalkey.relay.v1`.MailboxKt.Dsl._create(this.toBuilder()).apply { block() }._build()

