// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: relay.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.relay.v1;

@kotlin.jvm.JvmName("-initializemailboxConfig")
public inline fun mailboxConfig(block: digitalkey.relay.v1.MailboxConfigKt.Dsl.() -> kotlin.Unit): digitalkey.relay.v1.Relay.MailboxConfig =
  digitalkey.relay.v1.MailboxConfigKt.Dsl._create(digitalkey.relay.v1.Relay.MailboxConfig.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.relay.v1.MailboxConfig`
 */
public object MailboxConfigKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.relay.v1.Relay.MailboxConfig.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.relay.v1.Relay.MailboxConfig.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.relay.v1.Relay.MailboxConfig = _builder.build()

    /**
     * ```
     * 应设为 RWD
     * ```
     *
     * `.digitalkey.relay.v1.AccessRights access_rights = 1;`
     */
    public var accessRights: digitalkey.relay.v1.Relay.AccessRights
      @kotlin.jvm.JvmName("getAccessRights")
        get() = _builder.accessRights
      @kotlin.jvm.JvmName("setAccessRights")
        set(value) {
        _builder.accessRights = value
      }
    public var accessRightsValue: kotlin.Int
      @kotlin.jvm.JvmName("getAccessRightsValue")
        get() = _builder.accessRightsValue
      @kotlin.jvm.JvmName("setAccessRightsValue")
        set(value) {
        _builder.accessRightsValue = value
      }
    /**
     * ```
     * 应设为 RWD
     * ```
     *
     * `.digitalkey.relay.v1.AccessRights access_rights = 1;`
     */
    public fun clearAccessRights() {
      _builder.clearAccessRights()
    }

    /**
     * ```
     * 邮箱过期时间
     * ```
     *
     * `int64 expiration_seconds = 2;`
     */
    public var expirationSeconds: kotlin.Long
      @kotlin.jvm.JvmName("getExpirationSeconds")
        get() = _builder.expirationSeconds
      @kotlin.jvm.JvmName("setExpirationSeconds")
        set(value) {
        _builder.expirationSeconds = value
      }
    /**
     * ```
     * 邮箱过期时间
     * ```
     *
     * `int64 expiration_seconds = 2;`
     */
    public fun clearExpirationSeconds() {
      _builder.clearExpirationSeconds()
    }

    /**
     * ```
     * 最大更新次数 (默认 10)
     * ```
     *
     * `int32 max_updates = 3;`
     */
    public var maxUpdates: kotlin.Int
      @kotlin.jvm.JvmName("getMaxUpdates")
        get() = _builder.maxUpdates
      @kotlin.jvm.JvmName("setMaxUpdates")
        set(value) {
        _builder.maxUpdates = value
      }
    /**
     * ```
     * 最大更新次数 (默认 10)
     * ```
     *
     * `int32 max_updates = 3;`
     */
    public fun clearMaxUpdates() {
      _builder.clearMaxUpdates()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.relay.v1.Relay.MailboxConfig.copy(block: `digitalkey.relay.v1`.MailboxConfigKt.Dsl.() -> kotlin.Unit): digitalkey.relay.v1.Relay.MailboxConfig =
  `digitalkey.relay.v1`.MailboxConfigKt.Dsl._create(this.toBuilder()).apply { block() }._build()

