// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: relay.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.relay.v1;

@kotlin.jvm.JvmName("-initializereadDisplayInformationFromMailboxResponse")
public inline fun readDisplayInformationFromMailboxResponse(block: digitalkey.relay.v1.ReadDisplayInformationFromMailboxResponseKt.Dsl.() -> kotlin.Unit): digitalkey.relay.v1.Relay.ReadDisplayInformationFromMailboxResponse =
  digitalkey.relay.v1.ReadDisplayInformationFromMailboxResponseKt.Dsl._create(digitalkey.relay.v1.Relay.ReadDisplayInformationFromMailboxResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * ReadDisplayInformationFromMailboxResponse
 * ```
 *
 * Protobuf type `digitalkey.relay.v1.ReadDisplayInformationFromMailboxResponse`
 */
public object ReadDisplayInformationFromMailboxResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.relay.v1.Relay.ReadDisplayInformationFromMailboxResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.relay.v1.Relay.ReadDisplayInformationFromMailboxResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.relay.v1.Relay.ReadDisplayInformationFromMailboxResponse = _builder.build()

    /**
     * `bytes display_info = 1;`
     */
    public var displayInfo: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getDisplayInfo")
        get() = _builder.displayInfo
      @kotlin.jvm.JvmName("setDisplayInfo")
        set(value) {
        _builder.displayInfo = value
      }
    /**
     * `bytes display_info = 1;`
     */
    public fun clearDisplayInfo() {
      _builder.clearDisplayInfo()
    }

    /**
     * `int64 version = 2;`
     */
    public var version: kotlin.Long
      @kotlin.jvm.JvmName("getVersion")
        get() = _builder.version
      @kotlin.jvm.JvmName("setVersion")
        set(value) {
        _builder.version = value
      }
    /**
     * `int64 version = 2;`
     */
    public fun clearVersion() {
      _builder.clearVersion()
    }

    /**
     * `string error_code = 3;`
     */
    public var errorCode: kotlin.String
      @kotlin.jvm.JvmName("getErrorCode")
        get() = _builder.errorCode
      @kotlin.jvm.JvmName("setErrorCode")
        set(value) {
        _builder.errorCode = value
      }
    /**
     * `string error_code = 3;`
     */
    public fun clearErrorCode() {
      _builder.clearErrorCode()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.relay.v1.Relay.ReadDisplayInformationFromMailboxResponse.copy(block: `digitalkey.relay.v1`.ReadDisplayInformationFromMailboxResponseKt.Dsl.() -> kotlin.Unit): digitalkey.relay.v1.Relay.ReadDisplayInformationFromMailboxResponse =
  `digitalkey.relay.v1`.ReadDisplayInformationFromMailboxResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

