// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: relay.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.relay.v1;

@kotlin.jvm.JvmName("-initializereadDisplayInformationFromMailboxRequest")
public inline fun readDisplayInformationFromMailboxRequest(block: digitalkey.relay.v1.ReadDisplayInformationFromMailboxRequestKt.Dsl.() -> kotlin.Unit): digitalkey.relay.v1.Relay.ReadDisplayInformationFromMailboxRequest =
  digitalkey.relay.v1.ReadDisplayInformationFromMailboxRequestKt.Dsl._create(digitalkey.relay.v1.Relay.ReadDisplayInformationFromMailboxRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * ReadDisplayInformationFromMailboxRequest
 * ```
 *
 * Protobuf type `digitalkey.relay.v1.ReadDisplayInformationFromMailboxRequest`
 */
public object ReadDisplayInformationFromMailboxRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.relay.v1.Relay.ReadDisplayInformationFromMailboxRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.relay.v1.Relay.ReadDisplayInformationFromMailboxRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.relay.v1.Relay.ReadDisplayInformationFromMailboxRequest = _builder.build()

    /**
     * `string mailbox_id = 1;`
     */
    public var mailboxId: kotlin.String
      @kotlin.jvm.JvmName("getMailboxId")
        get() = _builder.mailboxId
      @kotlin.jvm.JvmName("setMailboxId")
        set(value) {
        _builder.mailboxId = value
      }
    /**
     * `string mailbox_id = 1;`
     */
    public fun clearMailboxId() {
      _builder.clearMailboxId()
    }

    /**
     * `string device_id = 2;`
     */
    public var deviceId: kotlin.String
      @kotlin.jvm.JvmName("getDeviceId")
        get() = _builder.deviceId
      @kotlin.jvm.JvmName("setDeviceId")
        set(value) {
        _builder.deviceId = value
      }
    /**
     * `string device_id = 2;`
     */
    public fun clearDeviceId() {
      _builder.clearDeviceId()
    }

    /**
     * `string trace_id = 3;`
     */
    public var traceId: kotlin.String
      @kotlin.jvm.JvmName("getTraceId")
        get() = _builder.traceId
      @kotlin.jvm.JvmName("setTraceId")
        set(value) {
        _builder.traceId = value
      }
    /**
     * `string trace_id = 3;`
     */
    public fun clearTraceId() {
      _builder.clearTraceId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.relay.v1.Relay.ReadDisplayInformationFromMailboxRequest.copy(block: `digitalkey.relay.v1`.ReadDisplayInformationFromMailboxRequestKt.Dsl.() -> kotlin.Unit): digitalkey.relay.v1.Relay.ReadDisplayInformationFromMailboxRequest =
  `digitalkey.relay.v1`.ReadDisplayInformationFromMailboxRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

