// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: relay.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.relay.v1;

@kotlin.jvm.JvmName("-initializereadSecureContentFromMailboxResponse")
public inline fun readSecureContentFromMailboxResponse(block: digitalkey.relay.v1.ReadSecureContentFromMailboxResponseKt.Dsl.() -> kotlin.Unit): digitalkey.relay.v1.Relay.ReadSecureContentFromMailboxResponse =
  digitalkey.relay.v1.ReadSecureContentFromMailboxResponseKt.Dsl._create(digitalkey.relay.v1.Relay.ReadSecureContentFromMailboxResponse.newBuilder()).apply { block() }._build()
/**
 * ```
 * ReadSecureContentFromMailboxResponse
 * ```
 *
 * Protobuf type `digitalkey.relay.v1.ReadSecureContentFromMailboxResponse`
 */
public object ReadSecureContentFromMailboxResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.relay.v1.Relay.ReadSecureContentFromMailboxResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.relay.v1.Relay.ReadSecureContentFromMailboxResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.relay.v1.Relay.ReadSecureContentFromMailboxResponse = _builder.build()

    /**
     * ```
     * 加密内容
     * ```
     *
     * `bytes payload = 1;`
     */
    public var payload: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getPayload")
        get() = _builder.payload
      @kotlin.jvm.JvmName("setPayload")
        set(value) {
        _builder.payload = value
      }
    /**
     * ```
     * 加密内容
     * ```
     *
     * `bytes payload = 1;`
     */
    public fun clearPayload() {
      _builder.clearPayload()
    }

    /**
     * `int64 version = 2;`
     */
    public var version: kotlin.Long
      @kotlin.jvm.JvmName("getVersion")
        get() = _builder.version
      @kotlin.jvm.JvmName("setVersion")
        set(value) {
        _builder.version = value
      }
    /**
     * `int64 version = 2;`
     */
    public fun clearVersion() {
      _builder.clearVersion()
    }

    /**
     * `string error_code = 3;`
     */
    public var errorCode: kotlin.String
      @kotlin.jvm.JvmName("getErrorCode")
        get() = _builder.errorCode
      @kotlin.jvm.JvmName("setErrorCode")
        set(value) {
        _builder.errorCode = value
      }
    /**
     * `string error_code = 3;`
     */
    public fun clearErrorCode() {
      _builder.clearErrorCode()
    }

    /**
     * `string error_msg = 4;`
     */
    public var errorMsg: kotlin.String
      @kotlin.jvm.JvmName("getErrorMsg")
        get() = _builder.errorMsg
      @kotlin.jvm.JvmName("setErrorMsg")
        set(value) {
        _builder.errorMsg = value
      }
    /**
     * `string error_msg = 4;`
     */
    public fun clearErrorMsg() {
      _builder.clearErrorMsg()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.relay.v1.Relay.ReadSecureContentFromMailboxResponse.copy(block: `digitalkey.relay.v1`.ReadSecureContentFromMailboxResponseKt.Dsl.() -> kotlin.Unit): digitalkey.relay.v1.Relay.ReadSecureContentFromMailboxResponse =
  `digitalkey.relay.v1`.ReadSecureContentFromMailboxResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

