// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: relay.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.relay.v1;

@kotlin.jvm.JvmName("-initializerelinquishMailboxRequest")
public inline fun relinquishMailboxRequest(block: digitalkey.relay.v1.RelinquishMailboxRequestKt.Dsl.() -> kotlin.Unit): digitalkey.relay.v1.Relay.RelinquishMailboxRequest =
  digitalkey.relay.v1.RelinquishMailboxRequestKt.Dsl._create(digitalkey.relay.v1.Relay.RelinquishMailboxRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.relay.v1.RelinquishMailboxRequest`
 */
public object RelinquishMailboxRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.relay.v1.Relay.RelinquishMailboxRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.relay.v1.Relay.RelinquishMailboxRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.relay.v1.Relay.RelinquishMailboxRequest = _builder.build()

    /**
     * `string mailbox_id = 1;`
     */
    public var mailboxId: kotlin.String
      @kotlin.jvm.JvmName("getMailboxId")
        get() = _builder.mailboxId
      @kotlin.jvm.JvmName("setMailboxId")
        set(value) {
        _builder.mailboxId = value
      }
    /**
     * `string mailbox_id = 1;`
     */
    public fun clearMailboxId() {
      _builder.clearMailboxId()
    }

    /**
     * ```
     * 当前持有设备
     * ```
     *
     * `string from_device_id = 2;`
     */
    public var fromDeviceId: kotlin.String
      @kotlin.jvm.JvmName("getFromDeviceId")
        get() = _builder.fromDeviceId
      @kotlin.jvm.JvmName("setFromDeviceId")
        set(value) {
        _builder.fromDeviceId = value
      }
    /**
     * ```
     * 当前持有设备
     * ```
     *
     * `string from_device_id = 2;`
     */
    public fun clearFromDeviceId() {
      _builder.clearFromDeviceId()
    }

    /**
     * ```
     * 目标设备
     * ```
     *
     * `string to_device_id = 3;`
     */
    public var toDeviceId: kotlin.String
      @kotlin.jvm.JvmName("getToDeviceId")
        get() = _builder.toDeviceId
      @kotlin.jvm.JvmName("setToDeviceId")
        set(value) {
        _builder.toDeviceId = value
      }
    /**
     * ```
     * 目标设备
     * ```
     *
     * `string to_device_id = 3;`
     */
    public fun clearToDeviceId() {
      _builder.clearToDeviceId()
    }

    /**
     * `string trace_id = 4;`
     */
    public var traceId: kotlin.String
      @kotlin.jvm.JvmName("getTraceId")
        get() = _builder.traceId
      @kotlin.jvm.JvmName("setTraceId")
        set(value) {
        _builder.traceId = value
      }
    /**
     * `string trace_id = 4;`
     */
    public fun clearTraceId() {
      _builder.clearTraceId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.relay.v1.Relay.RelinquishMailboxRequest.copy(block: `digitalkey.relay.v1`.RelinquishMailboxRequestKt.Dsl.() -> kotlin.Unit): digitalkey.relay.v1.Relay.RelinquishMailboxRequest =
  `digitalkey.relay.v1`.RelinquishMailboxRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

