// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: relay.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.relay.v1;

@kotlin.jvm.JvmName("-initializerelinquishMailboxResponse")
public inline fun relinquishMailboxResponse(block: digitalkey.relay.v1.RelinquishMailboxResponseKt.Dsl.() -> kotlin.Unit): digitalkey.relay.v1.Relay.RelinquishMailboxResponse =
  digitalkey.relay.v1.RelinquishMailboxResponseKt.Dsl._create(digitalkey.relay.v1.Relay.RelinquishMailboxResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.relay.v1.RelinquishMailboxResponse`
 */
public object RelinquishMailboxResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.relay.v1.Relay.RelinquishMailboxResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.relay.v1.Relay.RelinquishMailboxResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.relay.v1.Relay.RelinquishMailboxResponse = _builder.build()

    /**
     * `bool success = 1;`
     */
    public var success: kotlin.Boolean
      @kotlin.jvm.JvmName("getSuccess")
        get() = _builder.success
      @kotlin.jvm.JvmName("setSuccess")
        set(value) {
        _builder.success = value
      }
    /**
     * `bool success = 1;`
     */
    public fun clearSuccess() {
      _builder.clearSuccess()
    }

    /**
     * `string error_code = 2;`
     */
    public var errorCode: kotlin.String
      @kotlin.jvm.JvmName("getErrorCode")
        get() = _builder.errorCode
      @kotlin.jvm.JvmName("setErrorCode")
        set(value) {
        _builder.errorCode = value
      }
    /**
     * `string error_code = 2;`
     */
    public fun clearErrorCode() {
      _builder.clearErrorCode()
    }

    /**
     * `string error_msg = 3;`
     */
    public var errorMsg: kotlin.String
      @kotlin.jvm.JvmName("getErrorMsg")
        get() = _builder.errorMsg
      @kotlin.jvm.JvmName("setErrorMsg")
        set(value) {
        _builder.errorMsg = value
      }
    /**
     * `string error_msg = 3;`
     */
    public fun clearErrorMsg() {
      _builder.clearErrorMsg()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.relay.v1.Relay.RelinquishMailboxResponse.copy(block: `digitalkey.relay.v1`.RelinquishMailboxResponseKt.Dsl.() -> kotlin.Unit): digitalkey.relay.v1.Relay.RelinquishMailboxResponse =
  `digitalkey.relay.v1`.RelinquishMailboxResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

