// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: relay.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.relay.v1;

@kotlin.jvm.JvmName("-initializeupdateMailboxRequest")
public inline fun updateMailboxRequest(block: digitalkey.relay.v1.UpdateMailboxRequestKt.Dsl.() -> kotlin.Unit): digitalkey.relay.v1.Relay.UpdateMailboxRequest =
  digitalkey.relay.v1.UpdateMailboxRequestKt.Dsl._create(digitalkey.relay.v1.Relay.UpdateMailboxRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.relay.v1.UpdateMailboxRequest`
 */
public object UpdateMailboxRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.relay.v1.Relay.UpdateMailboxRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.relay.v1.Relay.UpdateMailboxRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.relay.v1.Relay.UpdateMailboxRequest = _builder.build()

    /**
     * `string mailbox_id = 1;`
     */
    public var mailboxId: kotlin.String
      @kotlin.jvm.JvmName("getMailboxId")
        get() = _builder.mailboxId
      @kotlin.jvm.JvmName("setMailboxId")
        set(value) {
        _builder.mailboxId = value
      }
    /**
     * `string mailbox_id = 1;`
     */
    public fun clearMailboxId() {
      _builder.clearMailboxId()
    }

    /**
     * ```
     * 更新内容（KeySigningRequest / ImportRequest / Cancellation）
     * ```
     *
     * `bytes payload = 2;`
     */
    public var payload: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getPayload")
        get() = _builder.payload
      @kotlin.jvm.JvmName("setPayload")
        set(value) {
        _builder.payload = value
      }
    /**
     * ```
     * 更新内容（KeySigningRequest / ImportRequest / Cancellation）
     * ```
     *
     * `bytes payload = 2;`
     */
    public fun clearPayload() {
      _builder.clearPayload()
    }

    /**
     * ```
     * 1=KeyCreation, 2=KeySigning, 3=Import, 4=SenderCancel, 5=ReceiverCancel
     * ```
     *
     * `int32 sharing_data_type = 3;`
     */
    public var sharingDataType: kotlin.Int
      @kotlin.jvm.JvmName("getSharingDataType")
        get() = _builder.sharingDataType
      @kotlin.jvm.JvmName("setSharingDataType")
        set(value) {
        _builder.sharingDataType = value
      }
    /**
     * ```
     * 1=KeyCreation, 2=KeySigning, 3=Import, 4=SenderCancel, 5=ReceiverCancel
     * ```
     *
     * `int32 sharing_data_type = 3;`
     */
    public fun clearSharingDataType() {
      _builder.clearSharingDataType()
    }

    /**
     * ```
     * 更新方的 Push token
     * ```
     *
     * `string notification_token = 4;`
     */
    public var notificationToken: kotlin.String
      @kotlin.jvm.JvmName("getNotificationToken")
        get() = _builder.notificationToken
      @kotlin.jvm.JvmName("setNotificationToken")
        set(value) {
        _builder.notificationToken = value
      }
    /**
     * ```
     * 更新方的 Push token
     * ```
     *
     * `string notification_token = 4;`
     */
    public fun clearNotificationToken() {
      _builder.clearNotificationToken()
    }

    /**
     * `string updater_device_id = 5;`
     */
    public var updaterDeviceId: kotlin.String
      @kotlin.jvm.JvmName("getUpdaterDeviceId")
        get() = _builder.updaterDeviceId
      @kotlin.jvm.JvmName("setUpdaterDeviceId")
        set(value) {
        _builder.updaterDeviceId = value
      }
    /**
     * `string updater_device_id = 5;`
     */
    public fun clearUpdaterDeviceId() {
      _builder.clearUpdaterDeviceId()
    }

    /**
     * `string trace_id = 6;`
     */
    public var traceId: kotlin.String
      @kotlin.jvm.JvmName("getTraceId")
        get() = _builder.traceId
      @kotlin.jvm.JvmName("setTraceId")
        set(value) {
        _builder.traceId = value
      }
    /**
     * `string trace_id = 6;`
     */
    public fun clearTraceId() {
      _builder.clearTraceId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.relay.v1.Relay.UpdateMailboxRequest.copy(block: `digitalkey.relay.v1`.UpdateMailboxRequestKt.Dsl.() -> kotlin.Unit): digitalkey.relay.v1.Relay.UpdateMailboxRequest =
  `digitalkey.relay.v1`.UpdateMailboxRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

