// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: api/relay/v1/relay.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RelayService_CreateMailbox_FullMethodName          = "/digitalkey.relay.v1.RelayService/CreateMailbox"
	RelayService_UpdateMailbox_FullMethodName          = "/digitalkey.relay.v1.RelayService/UpdateMailbox"
	RelayService_DeleteMailbox_FullMethodName          = "/digitalkey.relay.v1.RelayService/DeleteMailbox"
	RelayService_ReadDisplayInformation_FullMethodName = "/digitalkey.relay.v1.RelayService/ReadDisplayInformation"
	RelayService_ReadSecureContent_FullMethodName      = "/digitalkey.relay.v1.RelayService/ReadSecureContent"
	RelayService_RelinquishMailbox_FullMethodName      = "/digitalkey.relay.v1.RelayService/RelinquishMailbox"
)

// RelayServiceClient is the client API for RelayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RelayServiceClient interface {
	// 11.3.4.1: CreateMailbox — 发送方创建分享邮箱
	CreateMailbox(ctx context.Context, in *CreateMailboxRequest, opts ...grpc.CallOption) (*CreateMailboxResponse, error)
	// 11.3.4.2: UpdateMailbox — 任一方更新邮箱内容
	UpdateMailbox(ctx context.Context, in *UpdateMailboxRequest, opts ...grpc.CallOption) (*UpdateMailboxResponse, error)
	// 11.3.4.3: DeleteMailbox — 删除邮箱
	DeleteMailbox(ctx context.Context, in *DeleteMailboxRequest, opts ...grpc.CallOption) (*DeleteMailboxResponse, error)
	// 11.3.4.4: ReadDisplayInformation — 读取展示信息
	ReadDisplayInformation(ctx context.Context, in *ReadDisplayInformationRequest, opts ...grpc.CallOption) (*ReadDisplayInformationResponse, error)
	// 11.3.4.5: ReadSecureContent — 读取加密内容
	ReadSecureContent(ctx context.Context, in *ReadSecureContentRequest, opts ...grpc.CallOption) (*ReadSecureContentResponse, error)
	// 11.3.4.6: RelinquishMailbox — 转移邮箱到另一设备
	RelinquishMailbox(ctx context.Context, in *RelinquishMailboxRequest, opts ...grpc.CallOption) (*RelinquishMailboxResponse, error)
}

type relayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRelayServiceClient(cc grpc.ClientConnInterface) RelayServiceClient {
	return &relayServiceClient{cc}
}

func (c *relayServiceClient) CreateMailbox(ctx context.Context, in *CreateMailboxRequest, opts ...grpc.CallOption) (*CreateMailboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMailboxResponse)
	err := c.cc.Invoke(ctx, RelayService_CreateMailbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayServiceClient) UpdateMailbox(ctx context.Context, in *UpdateMailboxRequest, opts ...grpc.CallOption) (*UpdateMailboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateMailboxResponse)
	err := c.cc.Invoke(ctx, RelayService_UpdateMailbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayServiceClient) DeleteMailbox(ctx context.Context, in *DeleteMailboxRequest, opts ...grpc.CallOption) (*DeleteMailboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteMailboxResponse)
	err := c.cc.Invoke(ctx, RelayService_DeleteMailbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayServiceClient) ReadDisplayInformation(ctx context.Context, in *ReadDisplayInformationRequest, opts ...grpc.CallOption) (*ReadDisplayInformationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadDisplayInformationResponse)
	err := c.cc.Invoke(ctx, RelayService_ReadDisplayInformation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayServiceClient) ReadSecureContent(ctx context.Context, in *ReadSecureContentRequest, opts ...grpc.CallOption) (*ReadSecureContentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadSecureContentResponse)
	err := c.cc.Invoke(ctx, RelayService_ReadSecureContent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *relayServiceClient) RelinquishMailbox(ctx context.Context, in *RelinquishMailboxRequest, opts ...grpc.CallOption) (*RelinquishMailboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RelinquishMailboxResponse)
	err := c.cc.Invoke(ctx, RelayService_RelinquishMailbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RelayServiceServer is the server API for RelayService service.
// All implementations must embed UnimplementedRelayServiceServer
// for forward compatibility.
type RelayServiceServer interface {
	// 11.3.4.1: CreateMailbox — 发送方创建分享邮箱
	CreateMailbox(context.Context, *CreateMailboxRequest) (*CreateMailboxResponse, error)
	// 11.3.4.2: UpdateMailbox — 任一方更新邮箱内容
	UpdateMailbox(context.Context, *UpdateMailboxRequest) (*UpdateMailboxResponse, error)
	// 11.3.4.3: DeleteMailbox — 删除邮箱
	DeleteMailbox(context.Context, *DeleteMailboxRequest) (*DeleteMailboxResponse, error)
	// 11.3.4.4: ReadDisplayInformation — 读取展示信息
	ReadDisplayInformation(context.Context, *ReadDisplayInformationRequest) (*ReadDisplayInformationResponse, error)
	// 11.3.4.5: ReadSecureContent — 读取加密内容
	ReadSecureContent(context.Context, *ReadSecureContentRequest) (*ReadSecureContentResponse, error)
	// 11.3.4.6: RelinquishMailbox — 转移邮箱到另一设备
	RelinquishMailbox(context.Context, *RelinquishMailboxRequest) (*RelinquishMailboxResponse, error)
	mustEmbedUnimplementedRelayServiceServer()
}

// UnimplementedRelayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRelayServiceServer struct{}

func (UnimplementedRelayServiceServer) CreateMailbox(context.Context, *CreateMailboxRequest) (*CreateMailboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMailbox not implemented")
}
func (UnimplementedRelayServiceServer) UpdateMailbox(context.Context, *UpdateMailboxRequest) (*UpdateMailboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateMailbox not implemented")
}
func (UnimplementedRelayServiceServer) DeleteMailbox(context.Context, *DeleteMailboxRequest) (*DeleteMailboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteMailbox not implemented")
}
func (UnimplementedRelayServiceServer) ReadDisplayInformation(context.Context, *ReadDisplayInformationRequest) (*ReadDisplayInformationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadDisplayInformation not implemented")
}
func (UnimplementedRelayServiceServer) ReadSecureContent(context.Context, *ReadSecureContentRequest) (*ReadSecureContentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadSecureContent not implemented")
}
func (UnimplementedRelayServiceServer) RelinquishMailbox(context.Context, *RelinquishMailboxRequest) (*RelinquishMailboxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RelinquishMailbox not implemented")
}
func (UnimplementedRelayServiceServer) mustEmbedUnimplementedRelayServiceServer() {}
func (UnimplementedRelayServiceServer) testEmbeddedByValue()                      {}

// UnsafeRelayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RelayServiceServer will
// result in compilation errors.
type UnsafeRelayServiceServer interface {
	mustEmbedUnimplementedRelayServiceServer()
}

func RegisterRelayServiceServer(s grpc.ServiceRegistrar, srv RelayServiceServer) {
	// If the following call panics, it indicates UnimplementedRelayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RelayService_ServiceDesc, srv)
}

func _RelayService_CreateMailbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMailboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServiceServer).CreateMailbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayService_CreateMailbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServiceServer).CreateMailbox(ctx, req.(*CreateMailboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayService_UpdateMailbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateMailboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServiceServer).UpdateMailbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayService_UpdateMailbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServiceServer).UpdateMailbox(ctx, req.(*UpdateMailboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayService_DeleteMailbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMailboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServiceServer).DeleteMailbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayService_DeleteMailbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServiceServer).DeleteMailbox(ctx, req.(*DeleteMailboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayService_ReadDisplayInformation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadDisplayInformationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServiceServer).ReadDisplayInformation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayService_ReadDisplayInformation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServiceServer).ReadDisplayInformation(ctx, req.(*ReadDisplayInformationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayService_ReadSecureContent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadSecureContentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServiceServer).ReadSecureContent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayService_ReadSecureContent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServiceServer).ReadSecureContent(ctx, req.(*ReadSecureContentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RelayService_RelinquishMailbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RelinquishMailboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RelayServiceServer).RelinquishMailbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RelayService_RelinquishMailbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RelayServiceServer).RelinquishMailbox(ctx, req.(*RelinquishMailboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RelayService_ServiceDesc is the grpc.ServiceDesc for RelayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RelayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "digitalkey.relay.v1.RelayService",
	HandlerType: (*RelayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateMailbox",
			Handler:    _RelayService_CreateMailbox_Handler,
		},
		{
			MethodName: "UpdateMailbox",
			Handler:    _RelayService_UpdateMailbox_Handler,
		},
		{
			MethodName: "DeleteMailbox",
			Handler:    _RelayService_DeleteMailbox_Handler,
		},
		{
			MethodName: "ReadDisplayInformation",
			Handler:    _RelayService_ReadDisplayInformation_Handler,
		},
		{
			MethodName: "ReadSecureContent",
			Handler:    _RelayService_ReadSecureContent_Handler,
		},
		{
			MethodName: "RelinquishMailbox",
			Handler:    _RelayService_RelinquishMailbox_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/relay/v1/relay.proto",
}
