apiVersion: apps/v1
kind: Deployment
metadata:
  name: yuledkcs-backend
  namespace: yuledkcs
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  template:
    spec:
      containers:
        - name: backend
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 10
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
