// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializeaccessLevel")
public inline fun accessLevel(block: com.yuledkcs.sdk.AccessLevelKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.AccessLevel =
  com.yuledkcs.sdk.AccessLevelKt.Dsl._create(com.yuledkcs.sdk.AccessLevel.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.sdk.v1.AccessLevel`
 */
public object AccessLevelKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.AccessLevel.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.AccessLevel.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.AccessLevel = _builder.build()

    /**
     * `bool lock = 1;`
     */
    public var lock: kotlin.Boolean
      @kotlin.jvm.JvmName("getLock")
        get() = _builder.lock
      @kotlin.jvm.JvmName("setLock")
        set(value) {
        _builder.lock = value
      }
    /**
     * `bool lock = 1;`
     */
    public fun clearLock() {
      _builder.clearLock()
    }

    /**
     * `bool unlock = 2;`
     */
    public var unlock: kotlin.Boolean
      @kotlin.jvm.JvmName("getUnlock")
        get() = _builder.unlock
      @kotlin.jvm.JvmName("setUnlock")
        set(value) {
        _builder.unlock = value
      }
    /**
     * `bool unlock = 2;`
     */
    public fun clearUnlock() {
      _builder.clearUnlock()
    }

    /**
     * `bool engine = 3;`
     */
    public var engine: kotlin.Boolean
      @kotlin.jvm.JvmName("getEngine")
        get() = _builder.engine
      @kotlin.jvm.JvmName("setEngine")
        set(value) {
        _builder.engine = value
      }
    /**
     * `bool engine = 3;`
     */
    public fun clearEngine() {
      _builder.clearEngine()
    }

    /**
     * `bool trunk = 4;`
     */
    public var trunk: kotlin.Boolean
      @kotlin.jvm.JvmName("getTrunk")
        get() = _builder.trunk
      @kotlin.jvm.JvmName("setTrunk")
        set(value) {
        _builder.trunk = value
      }
    /**
     * `bool trunk = 4;`
     */
    public fun clearTrunk() {
      _builder.clearTrunk()
    }

    /**
     * `bool window = 5;`
     */
    public var window: kotlin.Boolean
      @kotlin.jvm.JvmName("getWindow")
        get() = _builder.window
      @kotlin.jvm.JvmName("setWindow")
        set(value) {
        _builder.window = value
      }
    /**
     * `bool window = 5;`
     */
    public fun clearWindow() {
      _builder.clearWindow()
    }

    /**
     * `bool climate = 6;`
     */
    public var climate: kotlin.Boolean
      @kotlin.jvm.JvmName("getClimate")
        get() = _builder.climate
      @kotlin.jvm.JvmName("setClimate")
        set(value) {
        _builder.climate = value
      }
    /**
     * `bool climate = 6;`
     */
    public fun clearClimate() {
      _builder.clearClimate()
    }

    /**
     * `bool find = 7;`
     */
    public var find: kotlin.Boolean
      @kotlin.jvm.JvmName("getFind")
        get() = _builder.find
      @kotlin.jvm.JvmName("setFind")
        set(value) {
        _builder.find = value
      }
    /**
     * `bool find = 7;`
     */
    public fun clearFind() {
      _builder.clearFind()
    }

    /**
     * `bool seat = 8;`
     */
    public var seat: kotlin.Boolean
      @kotlin.jvm.JvmName("getSeat")
        get() = _builder.seat
      @kotlin.jvm.JvmName("setSeat")
        set(value) {
        _builder.seat = value
      }
    /**
     * `bool seat = 8;`
     */
    public fun clearSeat() {
      _builder.clearSeat()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.AccessLevel.copy(block: `com.yuledkcs.sdk`.AccessLevelKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.AccessLevel =
  `com.yuledkcs.sdk`.AccessLevelKt.Dsl._create(this.toBuilder()).apply { block() }._build()

