// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializeacceptShareRequest")
public inline fun acceptShareRequest(block: com.yuledkcs.sdk.AcceptShareRequestKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.AcceptShareRequest =
  com.yuledkcs.sdk.AcceptShareRequestKt.Dsl._create(com.yuledkcs.sdk.AcceptShareRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.sdk.v1.AcceptShareRequest`
 */
public object AcceptShareRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.AcceptShareRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.AcceptShareRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.AcceptShareRequest = _builder.build()

    /**
     * `string share_code = 1;`
     */
    public var shareCode: kotlin.String
      @kotlin.jvm.JvmName("getShareCode")
        get() = _builder.shareCode
      @kotlin.jvm.JvmName("setShareCode")
        set(value) {
        _builder.shareCode = value
      }
    /**
     * `string share_code = 1;`
     */
    public fun clearShareCode() {
      _builder.clearShareCode()
    }

    /**
     * ```
     * 以下由 SDK 自动填充
     * string      device_id     = 2;
     * string      user_id       = 3;
     * PhoneVendor vendor        = 4;
     * bytes       device_pubkey = 5;
     * ```
     *
     * `string trace_id = 6;`
     */
    public var traceId: kotlin.String
      @kotlin.jvm.JvmName("getTraceId")
        get() = _builder.traceId
      @kotlin.jvm.JvmName("setTraceId")
        set(value) {
        _builder.traceId = value
      }
    /**
     * ```
     * 以下由 SDK 自动填充
     * string      device_id     = 2;
     * string      user_id       = 3;
     * PhoneVendor vendor        = 4;
     * bytes       device_pubkey = 5;
     * ```
     *
     * `string trace_id = 6;`
     */
    public fun clearTraceId() {
      _builder.clearTraceId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.AcceptShareRequest.copy(block: `com.yuledkcs.sdk`.AcceptShareRequestKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.AcceptShareRequest =
  `com.yuledkcs.sdk`.AcceptShareRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

