// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializeacceptShareResponse")
public inline fun acceptShareResponse(block: com.yuledkcs.sdk.AcceptShareResponseKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.AcceptShareResponse =
  com.yuledkcs.sdk.AcceptShareResponseKt.Dsl._create(com.yuledkcs.sdk.AcceptShareResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.sdk.v1.AcceptShareResponse`
 */
public object AcceptShareResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.AcceptShareResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.AcceptShareResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.AcceptShareResponse = _builder.build()

    /**
     * `.digitalkey.sdk.v1.KeyItem key = 1;`
     */
    public var key: com.yuledkcs.sdk.KeyItem
      @kotlin.jvm.JvmName("getKey")
        get() = _builder.key
      @kotlin.jvm.JvmName("setKey")
        set(value) {
        _builder.key = value
      }
    /**
     * `.digitalkey.sdk.v1.KeyItem key = 1;`
     */
    public fun clearKey() {
      _builder.clearKey()
    }
    /**
     * `.digitalkey.sdk.v1.KeyItem key = 1;`
     * @return Whether the key field is set.
     */
    public fun hasKey(): kotlin.Boolean {
      return _builder.hasKey()
    }

    public val AcceptShareResponseKt.Dsl.keyOrNull: com.yuledkcs.sdk.KeyItem?
      get() = _builder.keyOrNull

    /**
     * `string error_code = 3;`
     */
    public var errorCode: kotlin.String
      @kotlin.jvm.JvmName("getErrorCode")
        get() = _builder.errorCode
      @kotlin.jvm.JvmName("setErrorCode")
        set(value) {
        _builder.errorCode = value
      }
    /**
     * `string error_code = 3;`
     */
    public fun clearErrorCode() {
      _builder.clearErrorCode()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.AcceptShareResponse.copy(block: `com.yuledkcs.sdk`.AcceptShareResponseKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.AcceptShareResponse =
  `com.yuledkcs.sdk`.AcceptShareResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.yuledkcs.sdk.AcceptShareResponseOrBuilder.keyOrNull: com.yuledkcs.sdk.KeyItem?
  get() = if (hasKey()) getKey() else null

