// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializebindKeyResponse")
public inline fun bindKeyResponse(block: com.yuledkcs.sdk.BindKeyResponseKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.BindKeyResponse =
  com.yuledkcs.sdk.BindKeyResponseKt.Dsl._create(com.yuledkcs.sdk.BindKeyResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.sdk.v1.BindKeyResponse`
 */
public object BindKeyResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.BindKeyResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.BindKeyResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.BindKeyResponse = _builder.build()

    /**
     * `string key_id = 1;`
     */
    public var keyId: kotlin.String
      @kotlin.jvm.JvmName("getKeyId")
        get() = _builder.keyId
      @kotlin.jvm.JvmName("setKeyId")
        set(value) {
        _builder.keyId = value
      }
    /**
     * `string key_id = 1;`
     */
    public fun clearKeyId() {
      _builder.clearKeyId()
    }

    /**
     * `string vehicle_id = 2;`
     */
    public var vehicleId: kotlin.String
      @kotlin.jvm.JvmName("getVehicleId")
        get() = _builder.vehicleId
      @kotlin.jvm.JvmName("setVehicleId")
        set(value) {
        _builder.vehicleId = value
      }
    /**
     * `string vehicle_id = 2;`
     */
    public fun clearVehicleId() {
      _builder.clearVehicleId()
    }

    /**
     * `string error_code = 4;`
     */
    public var errorCode: kotlin.String
      @kotlin.jvm.JvmName("getErrorCode")
        get() = _builder.errorCode
      @kotlin.jvm.JvmName("setErrorCode")
        set(value) {
        _builder.errorCode = value
      }
    /**
     * `string error_code = 4;`
     */
    public fun clearErrorCode() {
      _builder.clearErrorCode()
    }

    /**
     * `string error_msg = 5;`
     */
    public var errorMsg: kotlin.String
      @kotlin.jvm.JvmName("getErrorMsg")
        get() = _builder.errorMsg
      @kotlin.jvm.JvmName("setErrorMsg")
        set(value) {
        _builder.errorMsg = value
      }
    /**
     * `string error_msg = 5;`
     */
    public fun clearErrorMsg() {
      _builder.clearErrorMsg()
    }

    /**
     * ```
     * SDK 增强字段（非 Hub 返回，SDK 本地构建）:
     * ```
     *
     * `string vehicle_name = 20;`
     */
    public var vehicleName: kotlin.String
      @kotlin.jvm.JvmName("getVehicleName")
        get() = _builder.vehicleName
      @kotlin.jvm.JvmName("setVehicleName")
        set(value) {
        _builder.vehicleName = value
      }
    /**
     * ```
     * SDK 增强字段（非 Hub 返回，SDK 本地构建）:
     * ```
     *
     * `string vehicle_name = 20;`
     */
    public fun clearVehicleName() {
      _builder.clearVehicleName()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.BindKeyResponse.copy(block: `com.yuledkcs.sdk`.BindKeyResponseKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.BindKeyResponse =
  `com.yuledkcs.sdk`.BindKeyResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

