// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializebindKeyRequest")
public inline fun bindKeyRequest(block: com.yuledkcs.sdk.BindKeyRequestKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.BindKeyRequest =
  com.yuledkcs.sdk.BindKeyRequestKt.Dsl._create(com.yuledkcs.sdk.BindKeyRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * ⚠️ 注意: SDK 自动填充以下字段
 * device_id, user_id, vendor, protocol, key_type, device_pubkey, trace_id
 * App 只需传 vehicle_id + 业务参数
 * ```
 *
 * Protobuf type `digitalkey.sdk.v1.BindKeyRequest`
 */
public object BindKeyRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.BindKeyRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.BindKeyRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.BindKeyRequest = _builder.build()

    /**
     * `string vehicle_id = 1;`
     */
    public var vehicleId: kotlin.String
      @kotlin.jvm.JvmName("getVehicleId")
        get() = _builder.vehicleId
      @kotlin.jvm.JvmName("setVehicleId")
        set(value) {
        _builder.vehicleId = value
      }
    /**
     * `string vehicle_id = 1;`
     */
    public fun clearVehicleId() {
      _builder.clearVehicleId()
    }

    /**
     * ```
     * SDK 自动生成
     * ```
     *
     * `string trace_id = 11;`
     */
    public var traceId: kotlin.String
      @kotlin.jvm.JvmName("getTraceId")
        get() = _builder.traceId
      @kotlin.jvm.JvmName("setTraceId")
        set(value) {
        _builder.traceId = value
      }
    /**
     * ```
     * SDK 自动生成
     * ```
     *
     * `string trace_id = 11;`
     */
    public fun clearTraceId() {
      _builder.clearTraceId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.BindKeyRequest.copy(block: `com.yuledkcs.sdk`.BindKeyRequestKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.BindKeyRequest =
  `com.yuledkcs.sdk`.BindKeyRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

