// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializeclearRequest")
public inline fun clearRequest(block: com.yuledkcs.sdk.ClearRequestKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.ClearRequest =
  com.yuledkcs.sdk.ClearRequestKt.Dsl._create(com.yuledkcs.sdk.ClearRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.sdk.v1.ClearRequest`
 */
public object ClearRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.ClearRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.ClearRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.ClearRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.ClearRequest.copy(block: `com.yuledkcs.sdk`.ClearRequestKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.ClearRequest =
  `com.yuledkcs.sdk`.ClearRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

