// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializecreateShareResponse")
public inline fun createShareResponse(block: com.yuledkcs.sdk.CreateShareResponseKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.CreateShareResponse =
  com.yuledkcs.sdk.CreateShareResponseKt.Dsl._create(com.yuledkcs.sdk.CreateShareResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.sdk.v1.CreateShareResponse`
 */
public object CreateShareResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.CreateShareResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.CreateShareResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.CreateShareResponse = _builder.build()

    /**
     * `string share_id = 1;`
     */
    public var shareId: kotlin.String
      @kotlin.jvm.JvmName("getShareId")
        get() = _builder.shareId
      @kotlin.jvm.JvmName("setShareId")
        set(value) {
        _builder.shareId = value
      }
    /**
     * `string share_id = 1;`
     */
    public fun clearShareId() {
      _builder.clearShareId()
    }

    /**
     * ```
     * 6位数字分享码
     * ```
     *
     * `string share_code = 2;`
     */
    public var shareCode: kotlin.String
      @kotlin.jvm.JvmName("getShareCode")
        get() = _builder.shareCode
      @kotlin.jvm.JvmName("setShareCode")
        set(value) {
        _builder.shareCode = value
      }
    /**
     * ```
     * 6位数字分享码
     * ```
     *
     * `string share_code = 2;`
     */
    public fun clearShareCode() {
      _builder.clearShareCode()
    }

    /**
     * ```
     * CCC Mailbox URL（仅 CCC 协议返回）
     * ```
     *
     * `string sharing_url = 3;`
     */
    public var sharingUrl: kotlin.String
      @kotlin.jvm.JvmName("getSharingUrl")
        get() = _builder.sharingUrl
      @kotlin.jvm.JvmName("setSharingUrl")
        set(value) {
        _builder.sharingUrl = value
      }
    /**
     * ```
     * CCC Mailbox URL（仅 CCC 协议返回）
     * ```
     *
     * `string sharing_url = 3;`
     */
    public fun clearSharingUrl() {
      _builder.clearSharingUrl()
    }

    /**
     * `string error_code = 4;`
     */
    public var errorCode: kotlin.String
      @kotlin.jvm.JvmName("getErrorCode")
        get() = _builder.errorCode
      @kotlin.jvm.JvmName("setErrorCode")
        set(value) {
        _builder.errorCode = value
      }
    /**
     * `string error_code = 4;`
     */
    public fun clearErrorCode() {
      _builder.clearErrorCode()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.CreateShareResponse.copy(block: `com.yuledkcs.sdk`.CreateShareResponseKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.CreateShareResponse =
  `com.yuledkcs.sdk`.CreateShareResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

