// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializedisconnectResponse")
public inline fun disconnectResponse(block: com.yuledkcs.sdk.DisconnectResponseKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.DisconnectResponse =
  com.yuledkcs.sdk.DisconnectResponseKt.Dsl._create(com.yuledkcs.sdk.DisconnectResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.sdk.v1.DisconnectResponse`
 */
public object DisconnectResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.DisconnectResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.DisconnectResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.DisconnectResponse = _builder.build()

    /**
     * `bool success = 1;`
     */
    public var success: kotlin.Boolean
      @kotlin.jvm.JvmName("getSuccess")
        get() = _builder.success
      @kotlin.jvm.JvmName("setSuccess")
        set(value) {
        _builder.success = value
      }
    /**
     * `bool success = 1;`
     */
    public fun clearSuccess() {
      _builder.clearSuccess()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.DisconnectResponse.copy(block: `com.yuledkcs.sdk`.DisconnectResponseKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.DisconnectResponse =
  `com.yuledkcs.sdk`.DisconnectResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

