// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializegetKeyRequest")
public inline fun getKeyRequest(block: com.yuledkcs.sdk.GetKeyRequestKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.GetKeyRequest =
  com.yuledkcs.sdk.GetKeyRequestKt.Dsl._create(com.yuledkcs.sdk.GetKeyRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.sdk.v1.GetKeyRequest`
 */
public object GetKeyRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.GetKeyRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.GetKeyRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.GetKeyRequest = _builder.build()

    /**
     * `string key_id = 1;`
     */
    public var keyId: kotlin.String
      @kotlin.jvm.JvmName("getKeyId")
        get() = _builder.keyId
      @kotlin.jvm.JvmName("setKeyId")
        set(value) {
        _builder.keyId = value
      }
    /**
     * `string key_id = 1;`
     */
    public fun clearKeyId() {
      _builder.clearKeyId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.GetKeyRequest.copy(block: `com.yuledkcs.sdk`.GetKeyRequestKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.GetKeyRequest =
  `com.yuledkcs.sdk`.GetKeyRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

