// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializegetShareRequest")
public inline fun getShareRequest(block: com.yuledkcs.sdk.GetShareRequestKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.GetShareRequest =
  com.yuledkcs.sdk.GetShareRequestKt.Dsl._create(com.yuledkcs.sdk.GetShareRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.sdk.v1.GetShareRequest`
 */
public object GetShareRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.GetShareRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.GetShareRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.GetShareRequest = _builder.build()

    /**
     * `string share_id = 1;`
     */
    public var shareId: kotlin.String
      @kotlin.jvm.JvmName("getShareId")
        get() = _builder.shareId
      @kotlin.jvm.JvmName("setShareId")
        set(value) {
        _builder.shareId = value
      }
    /**
     * `string share_id = 1;`
     */
    public fun clearShareId() {
      _builder.clearShareId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.GetShareRequest.copy(block: `com.yuledkcs.sdk`.GetShareRequestKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.GetShareRequest =
  `com.yuledkcs.sdk`.GetShareRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

