// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializekeyItem")
public inline fun keyItem(block: com.yuledkcs.sdk.KeyItemKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.KeyItem =
  com.yuledkcs.sdk.KeyItemKt.Dsl._create(com.yuledkcs.sdk.KeyItem.newBuilder()).apply { block() }._build()
/**
 * ```
 * SDK 增强的钥匙视图（基于 Hub DigitalKey + 本地缓存）
 * ```
 *
 * Protobuf type `digitalkey.sdk.v1.KeyItem`
 */
public object KeyItemKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.KeyItem.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.KeyItem.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.KeyItem = _builder.build()

    /**
     * `string key_id = 1;`
     */
    public var keyId: kotlin.String
      @kotlin.jvm.JvmName("getKeyId")
        get() = _builder.keyId
      @kotlin.jvm.JvmName("setKeyId")
        set(value) {
        _builder.keyId = value
      }
    /**
     * `string key_id = 1;`
     */
    public fun clearKeyId() {
      _builder.clearKeyId()
    }

    /**
     * `string vehicle_id = 2;`
     */
    public var vehicleId: kotlin.String
      @kotlin.jvm.JvmName("getVehicleId")
        get() = _builder.vehicleId
      @kotlin.jvm.JvmName("setVehicleId")
        set(value) {
        _builder.vehicleId = value
      }
    /**
     * `string vehicle_id = 2;`
     */
    public fun clearVehicleId() {
      _builder.clearVehicleId()
    }

    /**
     * `string device_id = 3;`
     */
    public var deviceId: kotlin.String
      @kotlin.jvm.JvmName("getDeviceId")
        get() = _builder.deviceId
      @kotlin.jvm.JvmName("setDeviceId")
        set(value) {
        _builder.deviceId = value
      }
    /**
     * `string device_id = 3;`
     */
    public fun clearDeviceId() {
      _builder.clearDeviceId()
    }

    /**
     * ```
     * SDK 本地缓存（绑定时保存）
     * ```
     *
     * `string vehicle_name = 4;`
     */
    public var vehicleName: kotlin.String
      @kotlin.jvm.JvmName("getVehicleName")
        get() = _builder.vehicleName
      @kotlin.jvm.JvmName("setVehicleName")
        set(value) {
        _builder.vehicleName = value
      }
    /**
     * ```
     * SDK 本地缓存（绑定时保存）
     * ```
     *
     * `string vehicle_name = 4;`
     */
    public fun clearVehicleName() {
      _builder.clearVehicleName()
    }

    /**
     * ```
     * OWNER / FRIEND / SERVICE / TEMPORARY
     * ```
     *
     * `.digitalkey.sdk.v1.KeyType key_type = 5;`
     */
    public var keyType: com.yuledkcs.sdk.KeyType
      @kotlin.jvm.JvmName("getKeyType")
        get() = _builder.keyType
      @kotlin.jvm.JvmName("setKeyType")
        set(value) {
        _builder.keyType = value
      }
    public var keyTypeValue: kotlin.Int
      @kotlin.jvm.JvmName("getKeyTypeValue")
        get() = _builder.keyTypeValue
      @kotlin.jvm.JvmName("setKeyTypeValue")
        set(value) {
        _builder.keyTypeValue = value
      }
    /**
     * ```
     * OWNER / FRIEND / SERVICE / TEMPORARY
     * ```
     *
     * `.digitalkey.sdk.v1.KeyType key_type = 5;`
     */
    public fun clearKeyType() {
      _builder.clearKeyType()
    }

    /**
     * ```
     * CCC / ICCOA / ICCE
     * ```
     *
     * `.digitalkey.sdk.v1.Protocol protocol = 6;`
     */
    public var protocol: com.yuledkcs.sdk.Protocol
      @kotlin.jvm.JvmName("getProtocol")
        get() = _builder.protocol
      @kotlin.jvm.JvmName("setProtocol")
        set(value) {
        _builder.protocol = value
      }
    public var protocolValue: kotlin.Int
      @kotlin.jvm.JvmName("getProtocolValue")
        get() = _builder.protocolValue
      @kotlin.jvm.JvmName("setProtocolValue")
        set(value) {
        _builder.protocolValue = value
      }
    /**
     * ```
     * CCC / ICCOA / ICCE
     * ```
     *
     * `.digitalkey.sdk.v1.Protocol protocol = 6;`
     */
    public fun clearProtocol() {
      _builder.clearProtocol()
    }

    /**
     * ```
     * ACTIVE / SUSPENDED / REVOKED / EXPIRED
     * ```
     *
     * `string status = 7;`
     */
    public var status: kotlin.String
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    /**
     * ```
     * ACTIVE / SUSPENDED / REVOKED / EXPIRED
     * ```
     *
     * `string status = 7;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * ```
     * AccessLevel access_level = 8; (后续加)
     * ```
     *
     * `int64 valid_from = 9;`
     */
    public var validFrom: kotlin.Long
      @kotlin.jvm.JvmName("getValidFrom")
        get() = _builder.validFrom
      @kotlin.jvm.JvmName("setValidFrom")
        set(value) {
        _builder.validFrom = value
      }
    /**
     * ```
     * AccessLevel access_level = 8; (后续加)
     * ```
     *
     * `int64 valid_from = 9;`
     */
    public fun clearValidFrom() {
      _builder.clearValidFrom()
    }

    /**
     * `int64 valid_until = 10;`
     */
    public var validUntil: kotlin.Long
      @kotlin.jvm.JvmName("getValidUntil")
        get() = _builder.validUntil
      @kotlin.jvm.JvmName("setValidUntil")
        set(value) {
        _builder.validUntil = value
      }
    /**
     * `int64 valid_until = 10;`
     */
    public fun clearValidUntil() {
      _builder.clearValidUntil()
    }

    /**
     * `int64 created_at = 11;`
     */
    public var createdAt: kotlin.Long
      @kotlin.jvm.JvmName("getCreatedAt")
        get() = _builder.createdAt
      @kotlin.jvm.JvmName("setCreatedAt")
        set(value) {
        _builder.createdAt = value
      }
    /**
     * `int64 created_at = 11;`
     */
    public fun clearCreatedAt() {
      _builder.clearCreatedAt()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.KeyItem.copy(block: `com.yuledkcs.sdk`.KeyItemKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.KeyItem =
  `com.yuledkcs.sdk`.KeyItemKt.Dsl._create(this.toBuilder()).apply { block() }._build()

