// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializekeyStatusChange")
public inline fun keyStatusChange(block: com.yuledkcs.sdk.KeyStatusChangeKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.KeyStatusChange =
  com.yuledkcs.sdk.KeyStatusChangeKt.Dsl._create(com.yuledkcs.sdk.KeyStatusChange.newBuilder()).apply { block() }._build()
/**
 * ```
 * 钥匙状态变更
 * ```
 *
 * Protobuf type `digitalkey.sdk.v1.KeyStatusChange`
 */
public object KeyStatusChangeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.KeyStatusChange.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.KeyStatusChange.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.KeyStatusChange = _builder.build()

    /**
     * `string key_id = 1;`
     */
    public var keyId: kotlin.String
      @kotlin.jvm.JvmName("getKeyId")
        get() = _builder.keyId
      @kotlin.jvm.JvmName("setKeyId")
        set(value) {
        _builder.keyId = value
      }
    /**
     * `string key_id = 1;`
     */
    public fun clearKeyId() {
      _builder.clearKeyId()
    }

    /**
     * `string old_status = 2;`
     */
    public var oldStatus: kotlin.String
      @kotlin.jvm.JvmName("getOldStatus")
        get() = _builder.oldStatus
      @kotlin.jvm.JvmName("setOldStatus")
        set(value) {
        _builder.oldStatus = value
      }
    /**
     * `string old_status = 2;`
     */
    public fun clearOldStatus() {
      _builder.clearOldStatus()
    }

    /**
     * ```
     * REVOKED / SUSPENDED / EXPIRED / ACTIVE
     * ```
     *
     * `string new_status = 3;`
     */
    public var newStatus: kotlin.String
      @kotlin.jvm.JvmName("getNewStatus")
        get() = _builder.newStatus
      @kotlin.jvm.JvmName("setNewStatus")
        set(value) {
        _builder.newStatus = value
      }
    /**
     * ```
     * REVOKED / SUSPENDED / EXPIRED / ACTIVE
     * ```
     *
     * `string new_status = 3;`
     */
    public fun clearNewStatus() {
      _builder.clearNewStatus()
    }

    /**
     * `string reason = 4;`
     */
    public var reason: kotlin.String
      @kotlin.jvm.JvmName("getReason")
        get() = _builder.reason
      @kotlin.jvm.JvmName("setReason")
        set(value) {
        _builder.reason = value
      }
    /**
     * `string reason = 4;`
     */
    public fun clearReason() {
      _builder.clearReason()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.KeyStatusChange.copy(block: `com.yuledkcs.sdk`.KeyStatusChangeKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.KeyStatusChange =
  `com.yuledkcs.sdk`.KeyStatusChangeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

