// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializelistKeysRequest")
public inline fun listKeysRequest(block: com.yuledkcs.sdk.ListKeysRequestKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.ListKeysRequest =
  com.yuledkcs.sdk.ListKeysRequestKt.Dsl._create(com.yuledkcs.sdk.ListKeysRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.sdk.v1.ListKeysRequest`
 */
public object ListKeysRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.ListKeysRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.ListKeysRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.ListKeysRequest = _builder.build()

    /**
     * ```
     * 可选筛选
     * ```
     *
     * `string vehicle_id = 1;`
     */
    public var vehicleId: kotlin.String
      @kotlin.jvm.JvmName("getVehicleId")
        get() = _builder.vehicleId
      @kotlin.jvm.JvmName("setVehicleId")
        set(value) {
        _builder.vehicleId = value
      }
    /**
     * ```
     * 可选筛选
     * ```
     *
     * `string vehicle_id = 1;`
     */
    public fun clearVehicleId() {
      _builder.clearVehicleId()
    }

    /**
     * ```
     * 可选筛选
     * ```
     *
     * `.digitalkey.sdk.v1.KeyFilter status = 2;`
     */
    public var status: com.yuledkcs.sdk.KeyFilter
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    public var statusValue: kotlin.Int
      @kotlin.jvm.JvmName("getStatusValue")
        get() = _builder.statusValue
      @kotlin.jvm.JvmName("setStatusValue")
        set(value) {
        _builder.statusValue = value
      }
    /**
     * ```
     * 可选筛选
     * ```
     *
     * `.digitalkey.sdk.v1.KeyFilter status = 2;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.ListKeysRequest.copy(block: `com.yuledkcs.sdk`.ListKeysRequestKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.ListKeysRequest =
  `com.yuledkcs.sdk`.ListKeysRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

