// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializelocalKeysRequest")
public inline fun localKeysRequest(block: com.yuledkcs.sdk.LocalKeysRequestKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.LocalKeysRequest =
  com.yuledkcs.sdk.LocalKeysRequestKt.Dsl._create(com.yuledkcs.sdk.LocalKeysRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.sdk.v1.LocalKeysRequest`
 */
public object LocalKeysRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.LocalKeysRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.LocalKeysRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.LocalKeysRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.LocalKeysRequest.copy(block: `com.yuledkcs.sdk`.LocalKeysRequestKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.LocalKeysRequest =
  `com.yuledkcs.sdk`.LocalKeysRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

