// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializelocalKeysResponse")
public inline fun localKeysResponse(block: com.yuledkcs.sdk.LocalKeysResponseKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.LocalKeysResponse =
  com.yuledkcs.sdk.LocalKeysResponseKt.Dsl._create(com.yuledkcs.sdk.LocalKeysResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.sdk.v1.LocalKeysResponse`
 */
public object LocalKeysResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.LocalKeysResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.LocalKeysResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.LocalKeysResponse = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class KeysProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .digitalkey.sdk.v1.KeyItem keys = 1;`
     */
     public val keys: com.google.protobuf.kotlin.DslList<com.yuledkcs.sdk.KeyItem, KeysProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.keysList
      )
    /**
     * `repeated .digitalkey.sdk.v1.KeyItem keys = 1;`
     * @param value The keys to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addKeys")
    public fun com.google.protobuf.kotlin.DslList<com.yuledkcs.sdk.KeyItem, KeysProxy>.add(value: com.yuledkcs.sdk.KeyItem) {
      _builder.addKeys(value)
    }
    /**
     * `repeated .digitalkey.sdk.v1.KeyItem keys = 1;`
     * @param value The keys to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignKeys")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.yuledkcs.sdk.KeyItem, KeysProxy>.plusAssign(value: com.yuledkcs.sdk.KeyItem) {
      add(value)
    }
    /**
     * `repeated .digitalkey.sdk.v1.KeyItem keys = 1;`
     * @param values The keys to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllKeys")
    public fun com.google.protobuf.kotlin.DslList<com.yuledkcs.sdk.KeyItem, KeysProxy>.addAll(values: kotlin.collections.Iterable<com.yuledkcs.sdk.KeyItem>) {
      _builder.addAllKeys(values)
    }
    /**
     * `repeated .digitalkey.sdk.v1.KeyItem keys = 1;`
     * @param values The keys to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllKeys")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<com.yuledkcs.sdk.KeyItem, KeysProxy>.plusAssign(values: kotlin.collections.Iterable<com.yuledkcs.sdk.KeyItem>) {
      addAll(values)
    }
    /**
     * `repeated .digitalkey.sdk.v1.KeyItem keys = 1;`
     * @param index The index to set the value at.
     * @param value The keys to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setKeys")
    public operator fun com.google.protobuf.kotlin.DslList<com.yuledkcs.sdk.KeyItem, KeysProxy>.set(index: kotlin.Int, value: com.yuledkcs.sdk.KeyItem) {
      _builder.setKeys(index, value)
    }
    /**
     * `repeated .digitalkey.sdk.v1.KeyItem keys = 1;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearKeys")
    public fun com.google.protobuf.kotlin.DslList<com.yuledkcs.sdk.KeyItem, KeysProxy>.clear() {
      _builder.clearKeys()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.LocalKeysResponse.copy(block: `com.yuledkcs.sdk`.LocalKeysResponseKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.LocalKeysResponse =
  `com.yuledkcs.sdk`.LocalKeysResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

