// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializemailboxReadRequest")
public inline fun mailboxReadRequest(block: com.yuledkcs.sdk.MailboxReadRequestKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.MailboxReadRequest =
  com.yuledkcs.sdk.MailboxReadRequestKt.Dsl._create(com.yuledkcs.sdk.MailboxReadRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.sdk.v1.MailboxReadRequest`
 */
public object MailboxReadRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.MailboxReadRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.MailboxReadRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.MailboxReadRequest = _builder.build()

    /**
     * ```
     * 完整 URL（含 #secret，SDK 在 fragment 中提取 mailbox_id）
     * ```
     *
     * `string mailbox_url = 1;`
     */
    public var mailboxUrl: kotlin.String
      @kotlin.jvm.JvmName("getMailboxUrl")
        get() = _builder.mailboxUrl
      @kotlin.jvm.JvmName("setMailboxUrl")
        set(value) {
        _builder.mailboxUrl = value
      }
    /**
     * ```
     * 完整 URL（含 #secret，SDK 在 fragment 中提取 mailbox_id）
     * ```
     *
     * `string mailbox_url = 1;`
     */
    public fun clearMailboxUrl() {
      _builder.clearMailboxUrl()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.MailboxReadRequest.copy(block: `com.yuledkcs.sdk`.MailboxReadRequestKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.MailboxReadRequest =
  `com.yuledkcs.sdk`.MailboxReadRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

