// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializemailboxUpdateRequest")
public inline fun mailboxUpdateRequest(block: com.yuledkcs.sdk.MailboxUpdateRequestKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.MailboxUpdateRequest =
  com.yuledkcs.sdk.MailboxUpdateRequestKt.Dsl._create(com.yuledkcs.sdk.MailboxUpdateRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.sdk.v1.MailboxUpdateRequest`
 */
public object MailboxUpdateRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.MailboxUpdateRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.MailboxUpdateRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.MailboxUpdateRequest = _builder.build()

    /**
     * `string mailbox_id = 1;`
     */
    public var mailboxId: kotlin.String
      @kotlin.jvm.JvmName("getMailboxId")
        get() = _builder.mailboxId
      @kotlin.jvm.JvmName("setMailboxId")
        set(value) {
        _builder.mailboxId = value
      }
    /**
     * `string mailbox_id = 1;`
     */
    public fun clearMailboxId() {
      _builder.clearMailboxId()
    }

    /**
     * ```
     * 2=KeySigning 3=Import 4=Cancel
     * ```
     *
     * `int32 data_type = 2;`
     */
    public var dataType: kotlin.Int
      @kotlin.jvm.JvmName("getDataType")
        get() = _builder.dataType
      @kotlin.jvm.JvmName("setDataType")
        set(value) {
        _builder.dataType = value
      }
    /**
     * ```
     * 2=KeySigning 3=Import 4=Cancel
     * ```
     *
     * `int32 data_type = 2;`
     */
    public fun clearDataType() {
      _builder.clearDataType()
    }

    /**
     * ```
     * 端到端加密
     * ```
     *
     * `bytes payload = 3;`
     */
    public var payload: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getPayload")
        get() = _builder.payload
      @kotlin.jvm.JvmName("setPayload")
        set(value) {
        _builder.payload = value
      }
    /**
     * ```
     * 端到端加密
     * ```
     *
     * `bytes payload = 3;`
     */
    public fun clearPayload() {
      _builder.clearPayload()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.MailboxUpdateRequest.copy(block: `com.yuledkcs.sdk`.MailboxUpdateRequestKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.MailboxUpdateRequest =
  `com.yuledkcs.sdk`.MailboxUpdateRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

