// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializemailboxDeleteResponse")
public inline fun mailboxDeleteResponse(block: com.yuledkcs.sdk.MailboxDeleteResponseKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.MailboxDeleteResponse =
  com.yuledkcs.sdk.MailboxDeleteResponseKt.Dsl._create(com.yuledkcs.sdk.MailboxDeleteResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.sdk.v1.MailboxDeleteResponse`
 */
public object MailboxDeleteResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.MailboxDeleteResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.MailboxDeleteResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.MailboxDeleteResponse = _builder.build()

    /**
     * `bool success = 1;`
     */
    public var success: kotlin.Boolean
      @kotlin.jvm.JvmName("getSuccess")
        get() = _builder.success
      @kotlin.jvm.JvmName("setSuccess")
        set(value) {
        _builder.success = value
      }
    /**
     * `bool success = 1;`
     */
    public fun clearSuccess() {
      _builder.clearSuccess()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.MailboxDeleteResponse.copy(block: `com.yuledkcs.sdk`.MailboxDeleteResponseKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.MailboxDeleteResponse =
  `com.yuledkcs.sdk`.MailboxDeleteResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

