// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializemailboxDeleteRequest")
public inline fun mailboxDeleteRequest(block: com.yuledkcs.sdk.MailboxDeleteRequestKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.MailboxDeleteRequest =
  com.yuledkcs.sdk.MailboxDeleteRequestKt.Dsl._create(com.yuledkcs.sdk.MailboxDeleteRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.sdk.v1.MailboxDeleteRequest`
 */
public object MailboxDeleteRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.MailboxDeleteRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.MailboxDeleteRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.MailboxDeleteRequest = _builder.build()

    /**
     * `string mailbox_id = 1;`
     */
    public var mailboxId: kotlin.String
      @kotlin.jvm.JvmName("getMailboxId")
        get() = _builder.mailboxId
      @kotlin.jvm.JvmName("setMailboxId")
        set(value) {
        _builder.mailboxId = value
      }
    /**
     * `string mailbox_id = 1;`
     */
    public fun clearMailboxId() {
      _builder.clearMailboxId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.MailboxDeleteRequest.copy(block: `com.yuledkcs.sdk`.MailboxDeleteRequestKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.MailboxDeleteRequest =
  `com.yuledkcs.sdk`.MailboxDeleteRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

