// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializemailboxUpdateResponse")
public inline fun mailboxUpdateResponse(block: com.yuledkcs.sdk.MailboxUpdateResponseKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.MailboxUpdateResponse =
  com.yuledkcs.sdk.MailboxUpdateResponseKt.Dsl._create(com.yuledkcs.sdk.MailboxUpdateResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.sdk.v1.MailboxUpdateResponse`
 */
public object MailboxUpdateResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.MailboxUpdateResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.MailboxUpdateResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.MailboxUpdateResponse = _builder.build()

    /**
     * `int32 status = 1;`
     */
    public var status: kotlin.Int
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    /**
     * `int32 status = 1;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `int64 version = 2;`
     */
    public var version: kotlin.Long
      @kotlin.jvm.JvmName("getVersion")
        get() = _builder.version
      @kotlin.jvm.JvmName("setVersion")
        set(value) {
        _builder.version = value
      }
    /**
     * `int64 version = 2;`
     */
    public fun clearVersion() {
      _builder.clearVersion()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.MailboxUpdateResponse.copy(block: `com.yuledkcs.sdk`.MailboxUpdateResponseKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.MailboxUpdateResponse =
  `com.yuledkcs.sdk`.MailboxUpdateResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

