// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializerenewKeyRequest")
public inline fun renewKeyRequest(block: com.yuledkcs.sdk.RenewKeyRequestKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.RenewKeyRequest =
  com.yuledkcs.sdk.RenewKeyRequestKt.Dsl._create(com.yuledkcs.sdk.RenewKeyRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.sdk.v1.RenewKeyRequest`
 */
public object RenewKeyRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.RenewKeyRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.RenewKeyRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.RenewKeyRequest = _builder.build()

    /**
     * `string key_id = 1;`
     */
    public var keyId: kotlin.String
      @kotlin.jvm.JvmName("getKeyId")
        get() = _builder.keyId
      @kotlin.jvm.JvmName("setKeyId")
        set(value) {
        _builder.keyId = value
      }
    /**
     * `string key_id = 1;`
     */
    public fun clearKeyId() {
      _builder.clearKeyId()
    }

    /**
     * `int64 valid_until = 2;`
     */
    public var validUntil: kotlin.Long
      @kotlin.jvm.JvmName("getValidUntil")
        get() = _builder.validUntil
      @kotlin.jvm.JvmName("setValidUntil")
        set(value) {
        _builder.validUntil = value
      }
    /**
     * `int64 valid_until = 2;`
     */
    public fun clearValidUntil() {
      _builder.clearValidUntil()
    }

    /**
     * `string trace_id = 3;`
     */
    public var traceId: kotlin.String
      @kotlin.jvm.JvmName("getTraceId")
        get() = _builder.traceId
      @kotlin.jvm.JvmName("setTraceId")
        set(value) {
        _builder.traceId = value
      }
    /**
     * `string trace_id = 3;`
     */
    public fun clearTraceId() {
      _builder.clearTraceId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.RenewKeyRequest.copy(block: `com.yuledkcs.sdk`.RenewKeyRequestKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.RenewKeyRequest =
  `com.yuledkcs.sdk`.RenewKeyRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

