// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializeresumeKeyResponse")
public inline fun resumeKeyResponse(block: com.yuledkcs.sdk.ResumeKeyResponseKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.ResumeKeyResponse =
  com.yuledkcs.sdk.ResumeKeyResponseKt.Dsl._create(com.yuledkcs.sdk.ResumeKeyResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.sdk.v1.ResumeKeyResponse`
 */
public object ResumeKeyResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.ResumeKeyResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.ResumeKeyResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.ResumeKeyResponse = _builder.build()

    /**
     * `string error_code = 1;`
     */
    public var errorCode: kotlin.String
      @kotlin.jvm.JvmName("getErrorCode")
        get() = _builder.errorCode
      @kotlin.jvm.JvmName("setErrorCode")
        set(value) {
        _builder.errorCode = value
      }
    /**
     * `string error_code = 1;`
     */
    public fun clearErrorCode() {
      _builder.clearErrorCode()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.ResumeKeyResponse.copy(block: `com.yuledkcs.sdk`.ResumeKeyResponseKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.ResumeKeyResponse =
  `com.yuledkcs.sdk`.ResumeKeyResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

