// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializerevokeKeyResponse")
public inline fun revokeKeyResponse(block: com.yuledkcs.sdk.RevokeKeyResponseKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.RevokeKeyResponse =
  com.yuledkcs.sdk.RevokeKeyResponseKt.Dsl._create(com.yuledkcs.sdk.RevokeKeyResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.sdk.v1.RevokeKeyResponse`
 */
public object RevokeKeyResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.RevokeKeyResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.RevokeKeyResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.RevokeKeyResponse = _builder.build()

    /**
     * `string error_code = 1;`
     */
    public var errorCode: kotlin.String
      @kotlin.jvm.JvmName("getErrorCode")
        get() = _builder.errorCode
      @kotlin.jvm.JvmName("setErrorCode")
        set(value) {
        _builder.errorCode = value
      }
    /**
     * `string error_code = 1;`
     */
    public fun clearErrorCode() {
      _builder.clearErrorCode()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.RevokeKeyResponse.copy(block: `com.yuledkcs.sdk`.RevokeKeyResponseKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.RevokeKeyResponse =
  `com.yuledkcs.sdk`.RevokeKeyResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

