// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializescanRequest")
public inline fun scanRequest(block: com.yuledkcs.sdk.ScanRequestKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.ScanRequest =
  com.yuledkcs.sdk.ScanRequestKt.Dsl._create(com.yuledkcs.sdk.ScanRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.sdk.v1.ScanRequest`
 */
public object ScanRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.ScanRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.ScanRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.ScanRequest = _builder.build()

    /**
     * `int32 timeout_ms = 1;`
     */
    public var timeoutMs: kotlin.Int
      @kotlin.jvm.JvmName("getTimeoutMs")
        get() = _builder.timeoutMs
      @kotlin.jvm.JvmName("setTimeoutMs")
        set(value) {
        _builder.timeoutMs = value
      }
    /**
     * `int32 timeout_ms = 1;`
     */
    public fun clearTimeoutMs() {
      _builder.clearTimeoutMs()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.ScanRequest.copy(block: `com.yuledkcs.sdk`.ScanRequestKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.ScanRequest =
  `com.yuledkcs.sdk`.ScanRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

