// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializeshareNotification")
public inline fun shareNotification(block: com.yuledkcs.sdk.ShareNotificationKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.ShareNotification =
  com.yuledkcs.sdk.ShareNotificationKt.Dsl._create(com.yuledkcs.sdk.ShareNotification.newBuilder()).apply { block() }._build()
/**
 * ```
 * 收到新分享
 * ```
 *
 * Protobuf type `digitalkey.sdk.v1.ShareNotification`
 */
public object ShareNotificationKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.ShareNotification.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.ShareNotification.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.ShareNotification = _builder.build()

    /**
     * `string share_code = 1;`
     */
    public var shareCode: kotlin.String
      @kotlin.jvm.JvmName("getShareCode")
        get() = _builder.shareCode
      @kotlin.jvm.JvmName("setShareCode")
        set(value) {
        _builder.shareCode = value
      }
    /**
     * `string share_code = 1;`
     */
    public fun clearShareCode() {
      _builder.clearShareCode()
    }

    /**
     * `string from_user_id = 2;`
     */
    public var fromUserId: kotlin.String
      @kotlin.jvm.JvmName("getFromUserId")
        get() = _builder.fromUserId
      @kotlin.jvm.JvmName("setFromUserId")
        set(value) {
        _builder.fromUserId = value
      }
    /**
     * `string from_user_id = 2;`
     */
    public fun clearFromUserId() {
      _builder.clearFromUserId()
    }

    /**
     * `string vehicle_id = 3;`
     */
    public var vehicleId: kotlin.String
      @kotlin.jvm.JvmName("getVehicleId")
        get() = _builder.vehicleId
      @kotlin.jvm.JvmName("setVehicleId")
        set(value) {
        _builder.vehicleId = value
      }
    /**
     * `string vehicle_id = 3;`
     */
    public fun clearVehicleId() {
      _builder.clearVehicleId()
    }

    /**
     * ```
     * CCC 协议时可用
     * ```
     *
     * `string sharing_url = 4;`
     */
    public var sharingUrl: kotlin.String
      @kotlin.jvm.JvmName("getSharingUrl")
        get() = _builder.sharingUrl
      @kotlin.jvm.JvmName("setSharingUrl")
        set(value) {
        _builder.sharingUrl = value
      }
    /**
     * ```
     * CCC 协议时可用
     * ```
     *
     * `string sharing_url = 4;`
     */
    public fun clearSharingUrl() {
      _builder.clearSharingUrl()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.ShareNotification.copy(block: `com.yuledkcs.sdk`.ShareNotificationKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.ShareNotification =
  `com.yuledkcs.sdk`.ShareNotificationKt.Dsl._create(this.toBuilder()).apply { block() }._build()

