// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializestatusRequest")
public inline fun statusRequest(block: com.yuledkcs.sdk.StatusRequestKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.StatusRequest =
  com.yuledkcs.sdk.StatusRequestKt.Dsl._create(com.yuledkcs.sdk.StatusRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.sdk.v1.StatusRequest`
 */
public object StatusRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.StatusRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.StatusRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.StatusRequest = _builder.build()

    /**
     * `string vehicle_id = 1;`
     */
    public var vehicleId: kotlin.String
      @kotlin.jvm.JvmName("getVehicleId")
        get() = _builder.vehicleId
      @kotlin.jvm.JvmName("setVehicleId")
        set(value) {
        _builder.vehicleId = value
      }
    /**
     * `string vehicle_id = 1;`
     */
    public fun clearVehicleId() {
      _builder.clearVehicleId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.StatusRequest.copy(block: `com.yuledkcs.sdk`.StatusRequestKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.StatusRequest =
  `com.yuledkcs.sdk`.StatusRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

