// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializesyncRequest")
public inline fun syncRequest(block: com.yuledkcs.sdk.SyncRequestKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.SyncRequest =
  com.yuledkcs.sdk.SyncRequestKt.Dsl._create(com.yuledkcs.sdk.SyncRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.sdk.v1.SyncRequest`
 */
public object SyncRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.SyncRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.SyncRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.SyncRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.SyncRequest.copy(block: `com.yuledkcs.sdk`.SyncRequestKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.SyncRequest =
  `com.yuledkcs.sdk`.SyncRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

