// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializesyncResponse")
public inline fun syncResponse(block: com.yuledkcs.sdk.SyncResponseKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.SyncResponse =
  com.yuledkcs.sdk.SyncResponseKt.Dsl._create(com.yuledkcs.sdk.SyncResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.sdk.v1.SyncResponse`
 */
public object SyncResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.SyncResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.SyncResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.SyncResponse = _builder.build()

    /**
     * `int32 updated_count = 1;`
     */
    public var updatedCount: kotlin.Int
      @kotlin.jvm.JvmName("getUpdatedCount")
        get() = _builder.updatedCount
      @kotlin.jvm.JvmName("setUpdatedCount")
        set(value) {
        _builder.updatedCount = value
      }
    /**
     * `int32 updated_count = 1;`
     */
    public fun clearUpdatedCount() {
      _builder.clearUpdatedCount()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class ChangedKeyIdsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated string changed_key_ids = 2;`
     * @return A list containing the changedKeyIds.
     */
    public val changedKeyIds: com.google.protobuf.kotlin.DslList<kotlin.String, ChangedKeyIdsProxy>
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
      get() = com.google.protobuf.kotlin.DslList(
        _builder.changedKeyIdsList
      )
    /**
     * `repeated string changed_key_ids = 2;`
     * @param value The changedKeyIds to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addChangedKeyIds")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ChangedKeyIdsProxy>.add(value: kotlin.String) {
      _builder.addChangedKeyIds(value)
    }
    /**
     * `repeated string changed_key_ids = 2;`
     * @param value The changedKeyIds to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignChangedKeyIds")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ChangedKeyIdsProxy>.plusAssign(value: kotlin.String) {
      add(value)
    }
    /**
     * `repeated string changed_key_ids = 2;`
     * @param values The changedKeyIds to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllChangedKeyIds")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ChangedKeyIdsProxy>.addAll(values: kotlin.collections.Iterable<kotlin.String>) {
      _builder.addAllChangedKeyIds(values)
    }
    /**
     * `repeated string changed_key_ids = 2;`
     * @param values The changedKeyIds to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllChangedKeyIds")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ChangedKeyIdsProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.String>) {
      addAll(values)
    }
    /**
     * `repeated string changed_key_ids = 2;`
     * @param index The index to set the value at.
     * @param value The changedKeyIds to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setChangedKeyIds")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.String, ChangedKeyIdsProxy>.set(index: kotlin.Int, value: kotlin.String) {
      _builder.setChangedKeyIds(index, value)
    }/**
     * `repeated string changed_key_ids = 2;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setChangedKeyIds")
    public fun com.google.protobuf.kotlin.DslList<kotlin.String, ChangedKeyIdsProxy>.clear() {
      _builder.clearChangedKeyIds()
    }}
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.SyncResponse.copy(block: `com.yuledkcs.sdk`.SyncResponseKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.SyncResponse =
  `com.yuledkcs.sdk`.SyncResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

