// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializeunbindKeyRequest")
public inline fun unbindKeyRequest(block: com.yuledkcs.sdk.UnbindKeyRequestKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.UnbindKeyRequest =
  com.yuledkcs.sdk.UnbindKeyRequestKt.Dsl._create(com.yuledkcs.sdk.UnbindKeyRequest.newBuilder()).apply { block() }._build()
/**
 * ```
 * 解绑/挂起/恢复/撤销 共用 KeyId 模式
 * ```
 *
 * Protobuf type `digitalkey.sdk.v1.UnbindKeyRequest`
 */
public object UnbindKeyRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.UnbindKeyRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.UnbindKeyRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.UnbindKeyRequest = _builder.build()

    /**
     * `string key_id = 1;`
     */
    public var keyId: kotlin.String
      @kotlin.jvm.JvmName("getKeyId")
        get() = _builder.keyId
      @kotlin.jvm.JvmName("setKeyId")
        set(value) {
        _builder.keyId = value
      }
    /**
     * `string key_id = 1;`
     */
    public fun clearKeyId() {
      _builder.clearKeyId()
    }

    /**
     * `string trace_id = 2;`
     */
    public var traceId: kotlin.String
      @kotlin.jvm.JvmName("getTraceId")
        get() = _builder.traceId
      @kotlin.jvm.JvmName("setTraceId")
        set(value) {
        _builder.traceId = value
      }
    /**
     * `string trace_id = 2;`
     */
    public fun clearTraceId() {
      _builder.clearTraceId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.UnbindKeyRequest.copy(block: `com.yuledkcs.sdk`.UnbindKeyRequestKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.UnbindKeyRequest =
  `com.yuledkcs.sdk`.UnbindKeyRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

