// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializevehicleAlert")
public inline fun vehicleAlert(block: com.yuledkcs.sdk.VehicleAlertKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.VehicleAlert =
  com.yuledkcs.sdk.VehicleAlertKt.Dsl._create(com.yuledkcs.sdk.VehicleAlert.newBuilder()).apply { block() }._build()
/**
 * ```
 * 车辆告警
 * ```
 *
 * Protobuf type `digitalkey.sdk.v1.VehicleAlert`
 */
public object VehicleAlertKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.VehicleAlert.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.VehicleAlert.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.VehicleAlert = _builder.build()

    /**
     * `string vehicle_id = 1;`
     */
    public var vehicleId: kotlin.String
      @kotlin.jvm.JvmName("getVehicleId")
        get() = _builder.vehicleId
      @kotlin.jvm.JvmName("setVehicleId")
        set(value) {
        _builder.vehicleId = value
      }
    /**
     * `string vehicle_id = 1;`
     */
    public fun clearVehicleId() {
      _builder.clearVehicleId()
    }

    /**
     * ```
     * alarm / tow / crash / battery_low
     * ```
     *
     * `string alert_type = 2;`
     */
    public var alertType: kotlin.String
      @kotlin.jvm.JvmName("getAlertType")
        get() = _builder.alertType
      @kotlin.jvm.JvmName("setAlertType")
        set(value) {
        _builder.alertType = value
      }
    /**
     * ```
     * alarm / tow / crash / battery_low
     * ```
     *
     * `string alert_type = 2;`
     */
    public fun clearAlertType() {
      _builder.clearAlertType()
    }

    /**
     * `string message = 3;`
     */
    public var message: kotlin.String
      @kotlin.jvm.JvmName("getMessage")
        get() = _builder.message
      @kotlin.jvm.JvmName("setMessage")
        set(value) {
        _builder.message = value
      }
    /**
     * `string message = 3;`
     */
    public fun clearMessage() {
      _builder.clearMessage()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.VehicleAlert.copy(block: `com.yuledkcs.sdk`.VehicleAlertKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.VehicleAlert =
  `com.yuledkcs.sdk`.VehicleAlertKt.Dsl._create(this.toBuilder()).apply { block() }._build()

