// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializevehicleAdvertise")
public inline fun vehicleAdvertise(block: com.yuledkcs.sdk.VehicleAdvertiseKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.VehicleAdvertise =
  com.yuledkcs.sdk.VehicleAdvertiseKt.Dsl._create(com.yuledkcs.sdk.VehicleAdvertise.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.sdk.v1.VehicleAdvertise`
 */
public object VehicleAdvertiseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.VehicleAdvertise.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.VehicleAdvertise.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.VehicleAdvertise = _builder.build()

    /**
     * `string vehicle_id = 1;`
     */
    public var vehicleId: kotlin.String
      @kotlin.jvm.JvmName("getVehicleId")
        get() = _builder.vehicleId
      @kotlin.jvm.JvmName("setVehicleId")
        set(value) {
        _builder.vehicleId = value
      }
    /**
     * `string vehicle_id = 1;`
     */
    public fun clearVehicleId() {
      _builder.clearVehicleId()
    }

    /**
     * `int32 rssi = 2;`
     */
    public var rssi: kotlin.Int
      @kotlin.jvm.JvmName("getRssi")
        get() = _builder.rssi
      @kotlin.jvm.JvmName("setRssi")
        set(value) {
        _builder.rssi = value
      }
    /**
     * `int32 rssi = 2;`
     */
    public fun clearRssi() {
      _builder.clearRssi()
    }

    /**
     * ```
     * CCC / ICCOA / ICCE
     * ```
     *
     * `int32 protocol = 3;`
     */
    public var protocol: kotlin.Int
      @kotlin.jvm.JvmName("getProtocol")
        get() = _builder.protocol
      @kotlin.jvm.JvmName("setProtocol")
        set(value) {
        _builder.protocol = value
      }
    /**
     * ```
     * CCC / ICCOA / ICCE
     * ```
     *
     * `int32 protocol = 3;`
     */
    public fun clearProtocol() {
      _builder.clearProtocol()
    }

    /**
     * `bool supports_uwb = 4;`
     */
    public var supportsUwb: kotlin.Boolean
      @kotlin.jvm.JvmName("getSupportsUwb")
        get() = _builder.supportsUwb
      @kotlin.jvm.JvmName("setSupportsUwb")
        set(value) {
        _builder.supportsUwb = value
      }
    /**
     * `bool supports_uwb = 4;`
     */
    public fun clearSupportsUwb() {
      _builder.clearSupportsUwb()
    }

    /**
     * `bytes manufacturer_data = 5;`
     */
    public var manufacturerData: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getManufacturerData")
        get() = _builder.manufacturerData
      @kotlin.jvm.JvmName("setManufacturerData")
        set(value) {
        _builder.manufacturerData = value
      }
    /**
     * `bytes manufacturer_data = 5;`
     */
    public fun clearManufacturerData() {
      _builder.clearManufacturerData()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.VehicleAdvertise.copy(block: `com.yuledkcs.sdk`.VehicleAdvertiseKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.VehicleAdvertise =
  `com.yuledkcs.sdk`.VehicleAdvertiseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

