// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializevehicleStatus")
public inline fun vehicleStatus(block: com.yuledkcs.sdk.VehicleStatusKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.VehicleStatus =
  com.yuledkcs.sdk.VehicleStatusKt.Dsl._create(com.yuledkcs.sdk.VehicleStatus.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.sdk.v1.VehicleStatus`
 */
public object VehicleStatusKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.VehicleStatus.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.VehicleStatus.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.VehicleStatus = _builder.build()

    /**
     * `bool locked = 1;`
     */
    public var locked: kotlin.Boolean
      @kotlin.jvm.JvmName("getLocked")
        get() = _builder.locked
      @kotlin.jvm.JvmName("setLocked")
        set(value) {
        _builder.locked = value
      }
    /**
     * `bool locked = 1;`
     */
    public fun clearLocked() {
      _builder.clearLocked()
    }

    /**
     * `bool engine_on = 2;`
     */
    public var engineOn: kotlin.Boolean
      @kotlin.jvm.JvmName("getEngineOn")
        get() = _builder.engineOn
      @kotlin.jvm.JvmName("setEngineOn")
        set(value) {
        _builder.engineOn = value
      }
    /**
     * `bool engine_on = 2;`
     */
    public fun clearEngineOn() {
      _builder.clearEngineOn()
    }

    /**
     * `int32 battery_pct = 3;`
     */
    public var batteryPct: kotlin.Int
      @kotlin.jvm.JvmName("getBatteryPct")
        get() = _builder.batteryPct
      @kotlin.jvm.JvmName("setBatteryPct")
        set(value) {
        _builder.batteryPct = value
      }
    /**
     * `int32 battery_pct = 3;`
     */
    public fun clearBatteryPct() {
      _builder.clearBatteryPct()
    }

    /**
     * `string error = 5;`
     */
    public var error: kotlin.String
      @kotlin.jvm.JvmName("getError")
        get() = _builder.error
      @kotlin.jvm.JvmName("setError")
        set(value) {
        _builder.error = value
      }
    /**
     * `string error = 5;`
     */
    public fun clearError() {
      _builder.clearError()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.VehicleStatus.copy(block: `com.yuledkcs.sdk`.VehicleStatusKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.VehicleStatus =
  `com.yuledkcs.sdk`.VehicleStatusKt.Dsl._create(this.toBuilder()).apply { block() }._build()

