// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: sdk.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package com.yuledkcs.sdk;

@kotlin.jvm.JvmName("-initializevehicleStatusUpdate")
public inline fun vehicleStatusUpdate(block: com.yuledkcs.sdk.VehicleStatusUpdateKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.VehicleStatusUpdate =
  com.yuledkcs.sdk.VehicleStatusUpdateKt.Dsl._create(com.yuledkcs.sdk.VehicleStatusUpdate.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.sdk.v1.VehicleStatusUpdate`
 */
public object VehicleStatusUpdateKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.yuledkcs.sdk.VehicleStatusUpdate.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: com.yuledkcs.sdk.VehicleStatusUpdate.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): com.yuledkcs.sdk.VehicleStatusUpdate = _builder.build()

    /**
     * `string vehicle_id = 1;`
     */
    public var vehicleId: kotlin.String
      @kotlin.jvm.JvmName("getVehicleId")
        get() = _builder.vehicleId
      @kotlin.jvm.JvmName("setVehicleId")
        set(value) {
        _builder.vehicleId = value
      }
    /**
     * `string vehicle_id = 1;`
     */
    public fun clearVehicleId() {
      _builder.clearVehicleId()
    }

    /**
     * `int32 lock_status = 2;`
     */
    public var lockStatus: kotlin.Int
      @kotlin.jvm.JvmName("getLockStatus")
        get() = _builder.lockStatus
      @kotlin.jvm.JvmName("setLockStatus")
        set(value) {
        _builder.lockStatus = value
      }
    /**
     * `int32 lock_status = 2;`
     */
    public fun clearLockStatus() {
      _builder.clearLockStatus()
    }

    /**
     * `int32 engine_status = 3;`
     */
    public var engineStatus: kotlin.Int
      @kotlin.jvm.JvmName("getEngineStatus")
        get() = _builder.engineStatus
      @kotlin.jvm.JvmName("setEngineStatus")
        set(value) {
        _builder.engineStatus = value
      }
    /**
     * `int32 engine_status = 3;`
     */
    public fun clearEngineStatus() {
      _builder.clearEngineStatus()
    }

    /**
     * `int32 battery_pct = 6;`
     */
    public var batteryPct: kotlin.Int
      @kotlin.jvm.JvmName("getBatteryPct")
        get() = _builder.batteryPct
      @kotlin.jvm.JvmName("setBatteryPct")
        set(value) {
        _builder.batteryPct = value
      }
    /**
     * `int32 battery_pct = 6;`
     */
    public fun clearBatteryPct() {
      _builder.clearBatteryPct()
    }

    /**
     * `double latitude = 9;`
     */
    public var latitude: kotlin.Double
      @kotlin.jvm.JvmName("getLatitude")
        get() = _builder.latitude
      @kotlin.jvm.JvmName("setLatitude")
        set(value) {
        _builder.latitude = value
      }
    /**
     * `double latitude = 9;`
     */
    public fun clearLatitude() {
      _builder.clearLatitude()
    }

    /**
     * `double longitude = 10;`
     */
    public var longitude: kotlin.Double
      @kotlin.jvm.JvmName("getLongitude")
        get() = _builder.longitude
      @kotlin.jvm.JvmName("setLongitude")
        set(value) {
        _builder.longitude = value
      }
    /**
     * `double longitude = 10;`
     */
    public fun clearLongitude() {
      _builder.clearLongitude()
    }

    /**
     * `int64 timestamp = 11;`
     */
    public var timestamp: kotlin.Long
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `int64 timestamp = 11;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.yuledkcs.sdk.VehicleStatusUpdate.copy(block: `com.yuledkcs.sdk`.VehicleStatusUpdateKt.Dsl.() -> kotlin.Unit): com.yuledkcs.sdk.VehicleStatusUpdate =
  `com.yuledkcs.sdk`.VehicleStatusUpdateKt.Dsl._create(this.toBuilder()).apply { block() }._build()

