// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: relay.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - digitalkey.relay.v1.RelayService

/// Namespace containing generated types for the "digitalkey.relay.v1.RelayService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Digitalkey_Relay_V1_RelayService: Sendable {
    /// Service descriptor for the "digitalkey.relay.v1.RelayService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "digitalkey.relay.v1.RelayService")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "CreateMailbox" metadata.
        public enum CreateMailbox: Sendable {
            /// Request type for "CreateMailbox".
            public typealias Input = Digitalkey_Relay_V1_CreateMailboxRequest
            /// Response type for "CreateMailbox".
            public typealias Output = Digitalkey_Relay_V1_CreateMailboxResponse
            /// Descriptor for "CreateMailbox".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "digitalkey.relay.v1.RelayService"),
                method: "CreateMailbox",
                type: .unary
            )
        }
        /// Namespace for "UpdateMailbox" metadata.
        public enum UpdateMailbox: Sendable {
            /// Request type for "UpdateMailbox".
            public typealias Input = Digitalkey_Relay_V1_UpdateMailboxRequest
            /// Response type for "UpdateMailbox".
            public typealias Output = Digitalkey_Relay_V1_UpdateMailboxResponse
            /// Descriptor for "UpdateMailbox".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "digitalkey.relay.v1.RelayService"),
                method: "UpdateMailbox",
                type: .unary
            )
        }
        /// Namespace for "DeleteMailbox" metadata.
        public enum DeleteMailbox: Sendable {
            /// Request type for "DeleteMailbox".
            public typealias Input = Digitalkey_Relay_V1_DeleteMailboxRequest
            /// Response type for "DeleteMailbox".
            public typealias Output = Digitalkey_Relay_V1_DeleteMailboxResponse
            /// Descriptor for "DeleteMailbox".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "digitalkey.relay.v1.RelayService"),
                method: "DeleteMailbox",
                type: .unary
            )
        }
        /// Namespace for "ReadDisplayInformationFromMailbox" metadata.
        public enum ReadDisplayInformationFromMailbox: Sendable {
            /// Request type for "ReadDisplayInformationFromMailbox".
            public typealias Input = Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxRequest
            /// Response type for "ReadDisplayInformationFromMailbox".
            public typealias Output = Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxResponse
            /// Descriptor for "ReadDisplayInformationFromMailbox".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "digitalkey.relay.v1.RelayService"),
                method: "ReadDisplayInformationFromMailbox",
                type: .unary
            )
        }
        /// Namespace for "ReadSecureContentFromMailbox" metadata.
        public enum ReadSecureContentFromMailbox: Sendable {
            /// Request type for "ReadSecureContentFromMailbox".
            public typealias Input = Digitalkey_Relay_V1_ReadSecureContentFromMailboxRequest
            /// Response type for "ReadSecureContentFromMailbox".
            public typealias Output = Digitalkey_Relay_V1_ReadSecureContentFromMailboxResponse
            /// Descriptor for "ReadSecureContentFromMailbox".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "digitalkey.relay.v1.RelayService"),
                method: "ReadSecureContentFromMailbox",
                type: .unary
            )
        }
        /// Namespace for "RelinquishMailbox" metadata.
        public enum RelinquishMailbox: Sendable {
            /// Request type for "RelinquishMailbox".
            public typealias Input = Digitalkey_Relay_V1_RelinquishMailboxRequest
            /// Response type for "RelinquishMailbox".
            public typealias Output = Digitalkey_Relay_V1_RelinquishMailboxResponse
            /// Descriptor for "RelinquishMailbox".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "digitalkey.relay.v1.RelayService"),
                method: "RelinquishMailbox",
                type: .unary
            )
        }
        /// Descriptors for all methods in the "digitalkey.relay.v1.RelayService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            CreateMailbox.descriptor,
            UpdateMailbox.descriptor,
            DeleteMailbox.descriptor,
            ReadDisplayInformationFromMailbox.descriptor,
            ReadSecureContentFromMailbox.descriptor,
            RelinquishMailbox.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "digitalkey.relay.v1.RelayService" service.
    public static let digitalkey_relay_v1_RelayService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "digitalkey.relay.v1.RelayService")
}

// MARK: digitalkey.relay.v1.RelayService (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Digitalkey_Relay_V1_RelayService {
    /// Streaming variant of the service protocol for the "digitalkey.relay.v1.RelayService" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "CreateMailbox" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 11.3.4.1: CreateMailbox — 发送方创建分享邮箱
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Digitalkey_Relay_V1_CreateMailboxRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Digitalkey_Relay_V1_CreateMailboxResponse` messages.
        func createMailbox(
            request: GRPCCore.StreamingServerRequest<Digitalkey_Relay_V1_CreateMailboxRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Digitalkey_Relay_V1_CreateMailboxResponse>

        /// Handle the "UpdateMailbox" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 11.3.4.2: UpdateMailbox — 任一方更新邮箱内容
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Digitalkey_Relay_V1_UpdateMailboxRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Digitalkey_Relay_V1_UpdateMailboxResponse` messages.
        func updateMailbox(
            request: GRPCCore.StreamingServerRequest<Digitalkey_Relay_V1_UpdateMailboxRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Digitalkey_Relay_V1_UpdateMailboxResponse>

        /// Handle the "DeleteMailbox" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 11.3.4.3: DeleteMailbox — 删除邮箱
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Digitalkey_Relay_V1_DeleteMailboxRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Digitalkey_Relay_V1_DeleteMailboxResponse` messages.
        func deleteMailbox(
            request: GRPCCore.StreamingServerRequest<Digitalkey_Relay_V1_DeleteMailboxRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Digitalkey_Relay_V1_DeleteMailboxResponse>

        /// Handle the "ReadDisplayInformationFromMailbox" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 11.3.4.4: ReadDisplayInformationFromMailbox — 读取展示信息
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxResponse` messages.
        func readDisplayInformationFromMailbox(
            request: GRPCCore.StreamingServerRequest<Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxResponse>

        /// Handle the "ReadSecureContentFromMailbox" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 11.3.4.5: ReadSecureContentFromMailbox — 读取加密内容
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Digitalkey_Relay_V1_ReadSecureContentFromMailboxRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Digitalkey_Relay_V1_ReadSecureContentFromMailboxResponse` messages.
        func readSecureContentFromMailbox(
            request: GRPCCore.StreamingServerRequest<Digitalkey_Relay_V1_ReadSecureContentFromMailboxRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Digitalkey_Relay_V1_ReadSecureContentFromMailboxResponse>

        /// Handle the "RelinquishMailbox" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 11.3.4.6: RelinquishMailbox — 转移邮箱到另一设备
        ///
        /// - Parameters:
        ///   - request: A streaming request of `Digitalkey_Relay_V1_RelinquishMailboxRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `Digitalkey_Relay_V1_RelinquishMailboxResponse` messages.
        func relinquishMailbox(
            request: GRPCCore.StreamingServerRequest<Digitalkey_Relay_V1_RelinquishMailboxRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<Digitalkey_Relay_V1_RelinquishMailboxResponse>
    }

    /// Service protocol for the "digitalkey.relay.v1.RelayService" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: Digitalkey_Relay_V1_RelayService.StreamingServiceProtocol {
        /// Handle the "CreateMailbox" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 11.3.4.1: CreateMailbox — 发送方创建分享邮箱
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Digitalkey_Relay_V1_CreateMailboxRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Digitalkey_Relay_V1_CreateMailboxResponse` message.
        func createMailbox(
            request: GRPCCore.ServerRequest<Digitalkey_Relay_V1_CreateMailboxRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Digitalkey_Relay_V1_CreateMailboxResponse>

        /// Handle the "UpdateMailbox" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 11.3.4.2: UpdateMailbox — 任一方更新邮箱内容
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Digitalkey_Relay_V1_UpdateMailboxRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Digitalkey_Relay_V1_UpdateMailboxResponse` message.
        func updateMailbox(
            request: GRPCCore.ServerRequest<Digitalkey_Relay_V1_UpdateMailboxRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Digitalkey_Relay_V1_UpdateMailboxResponse>

        /// Handle the "DeleteMailbox" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 11.3.4.3: DeleteMailbox — 删除邮箱
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Digitalkey_Relay_V1_DeleteMailboxRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Digitalkey_Relay_V1_DeleteMailboxResponse` message.
        func deleteMailbox(
            request: GRPCCore.ServerRequest<Digitalkey_Relay_V1_DeleteMailboxRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Digitalkey_Relay_V1_DeleteMailboxResponse>

        /// Handle the "ReadDisplayInformationFromMailbox" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 11.3.4.4: ReadDisplayInformationFromMailbox — 读取展示信息
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxResponse` message.
        func readDisplayInformationFromMailbox(
            request: GRPCCore.ServerRequest<Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxResponse>

        /// Handle the "ReadSecureContentFromMailbox" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 11.3.4.5: ReadSecureContentFromMailbox — 读取加密内容
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Digitalkey_Relay_V1_ReadSecureContentFromMailboxRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Digitalkey_Relay_V1_ReadSecureContentFromMailboxResponse` message.
        func readSecureContentFromMailbox(
            request: GRPCCore.ServerRequest<Digitalkey_Relay_V1_ReadSecureContentFromMailboxRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Digitalkey_Relay_V1_ReadSecureContentFromMailboxResponse>

        /// Handle the "RelinquishMailbox" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 11.3.4.6: RelinquishMailbox — 转移邮箱到另一设备
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Digitalkey_Relay_V1_RelinquishMailboxRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `Digitalkey_Relay_V1_RelinquishMailboxResponse` message.
        func relinquishMailbox(
            request: GRPCCore.ServerRequest<Digitalkey_Relay_V1_RelinquishMailboxRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<Digitalkey_Relay_V1_RelinquishMailboxResponse>
    }

    /// Simple service protocol for the "digitalkey.relay.v1.RelayService" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: Digitalkey_Relay_V1_RelayService.ServiceProtocol {
        /// Handle the "CreateMailbox" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 11.3.4.1: CreateMailbox — 发送方创建分享邮箱
        ///
        /// - Parameters:
        ///   - request: A `Digitalkey_Relay_V1_CreateMailboxRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Digitalkey_Relay_V1_CreateMailboxResponse` to respond with.
        func createMailbox(
            request: Digitalkey_Relay_V1_CreateMailboxRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Digitalkey_Relay_V1_CreateMailboxResponse

        /// Handle the "UpdateMailbox" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 11.3.4.2: UpdateMailbox — 任一方更新邮箱内容
        ///
        /// - Parameters:
        ///   - request: A `Digitalkey_Relay_V1_UpdateMailboxRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Digitalkey_Relay_V1_UpdateMailboxResponse` to respond with.
        func updateMailbox(
            request: Digitalkey_Relay_V1_UpdateMailboxRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Digitalkey_Relay_V1_UpdateMailboxResponse

        /// Handle the "DeleteMailbox" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 11.3.4.3: DeleteMailbox — 删除邮箱
        ///
        /// - Parameters:
        ///   - request: A `Digitalkey_Relay_V1_DeleteMailboxRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Digitalkey_Relay_V1_DeleteMailboxResponse` to respond with.
        func deleteMailbox(
            request: Digitalkey_Relay_V1_DeleteMailboxRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Digitalkey_Relay_V1_DeleteMailboxResponse

        /// Handle the "ReadDisplayInformationFromMailbox" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 11.3.4.4: ReadDisplayInformationFromMailbox — 读取展示信息
        ///
        /// - Parameters:
        ///   - request: A `Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxResponse` to respond with.
        func readDisplayInformationFromMailbox(
            request: Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxResponse

        /// Handle the "ReadSecureContentFromMailbox" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 11.3.4.5: ReadSecureContentFromMailbox — 读取加密内容
        ///
        /// - Parameters:
        ///   - request: A `Digitalkey_Relay_V1_ReadSecureContentFromMailboxRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Digitalkey_Relay_V1_ReadSecureContentFromMailboxResponse` to respond with.
        func readSecureContentFromMailbox(
            request: Digitalkey_Relay_V1_ReadSecureContentFromMailboxRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Digitalkey_Relay_V1_ReadSecureContentFromMailboxResponse

        /// Handle the "RelinquishMailbox" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 11.3.4.6: RelinquishMailbox — 转移邮箱到另一设备
        ///
        /// - Parameters:
        ///   - request: A `Digitalkey_Relay_V1_RelinquishMailboxRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `Digitalkey_Relay_V1_RelinquishMailboxResponse` to respond with.
        func relinquishMailbox(
            request: Digitalkey_Relay_V1_RelinquishMailboxRequest,
            context: GRPCCore.ServerContext
        ) async throws -> Digitalkey_Relay_V1_RelinquishMailboxResponse
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Digitalkey_Relay_V1_RelayService.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: Digitalkey_Relay_V1_RelayService.Method.CreateMailbox.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Digitalkey_Relay_V1_CreateMailboxRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Digitalkey_Relay_V1_CreateMailboxResponse>(),
            handler: { request, context in
                try await self.createMailbox(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Digitalkey_Relay_V1_RelayService.Method.UpdateMailbox.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Digitalkey_Relay_V1_UpdateMailboxRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Digitalkey_Relay_V1_UpdateMailboxResponse>(),
            handler: { request, context in
                try await self.updateMailbox(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Digitalkey_Relay_V1_RelayService.Method.DeleteMailbox.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Digitalkey_Relay_V1_DeleteMailboxRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Digitalkey_Relay_V1_DeleteMailboxResponse>(),
            handler: { request, context in
                try await self.deleteMailbox(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Digitalkey_Relay_V1_RelayService.Method.ReadDisplayInformationFromMailbox.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxResponse>(),
            handler: { request, context in
                try await self.readDisplayInformationFromMailbox(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Digitalkey_Relay_V1_RelayService.Method.ReadSecureContentFromMailbox.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Digitalkey_Relay_V1_ReadSecureContentFromMailboxRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Digitalkey_Relay_V1_ReadSecureContentFromMailboxResponse>(),
            handler: { request, context in
                try await self.readSecureContentFromMailbox(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: Digitalkey_Relay_V1_RelayService.Method.RelinquishMailbox.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<Digitalkey_Relay_V1_RelinquishMailboxRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<Digitalkey_Relay_V1_RelinquishMailboxResponse>(),
            handler: { request, context in
                try await self.relinquishMailbox(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Digitalkey_Relay_V1_RelayService.ServiceProtocol {
    public func createMailbox(
        request: GRPCCore.StreamingServerRequest<Digitalkey_Relay_V1_CreateMailboxRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Digitalkey_Relay_V1_CreateMailboxResponse> {
        let response = try await self.createMailbox(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func updateMailbox(
        request: GRPCCore.StreamingServerRequest<Digitalkey_Relay_V1_UpdateMailboxRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Digitalkey_Relay_V1_UpdateMailboxResponse> {
        let response = try await self.updateMailbox(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func deleteMailbox(
        request: GRPCCore.StreamingServerRequest<Digitalkey_Relay_V1_DeleteMailboxRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Digitalkey_Relay_V1_DeleteMailboxResponse> {
        let response = try await self.deleteMailbox(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func readDisplayInformationFromMailbox(
        request: GRPCCore.StreamingServerRequest<Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxResponse> {
        let response = try await self.readDisplayInformationFromMailbox(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func readSecureContentFromMailbox(
        request: GRPCCore.StreamingServerRequest<Digitalkey_Relay_V1_ReadSecureContentFromMailboxRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Digitalkey_Relay_V1_ReadSecureContentFromMailboxResponse> {
        let response = try await self.readSecureContentFromMailbox(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func relinquishMailbox(
        request: GRPCCore.StreamingServerRequest<Digitalkey_Relay_V1_RelinquishMailboxRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<Digitalkey_Relay_V1_RelinquishMailboxResponse> {
        let response = try await self.relinquishMailbox(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Digitalkey_Relay_V1_RelayService.SimpleServiceProtocol {
    public func createMailbox(
        request: GRPCCore.ServerRequest<Digitalkey_Relay_V1_CreateMailboxRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Digitalkey_Relay_V1_CreateMailboxResponse> {
        return GRPCCore.ServerResponse<Digitalkey_Relay_V1_CreateMailboxResponse>(
            message: try await self.createMailbox(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func updateMailbox(
        request: GRPCCore.ServerRequest<Digitalkey_Relay_V1_UpdateMailboxRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Digitalkey_Relay_V1_UpdateMailboxResponse> {
        return GRPCCore.ServerResponse<Digitalkey_Relay_V1_UpdateMailboxResponse>(
            message: try await self.updateMailbox(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func deleteMailbox(
        request: GRPCCore.ServerRequest<Digitalkey_Relay_V1_DeleteMailboxRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Digitalkey_Relay_V1_DeleteMailboxResponse> {
        return GRPCCore.ServerResponse<Digitalkey_Relay_V1_DeleteMailboxResponse>(
            message: try await self.deleteMailbox(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func readDisplayInformationFromMailbox(
        request: GRPCCore.ServerRequest<Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxResponse> {
        return GRPCCore.ServerResponse<Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxResponse>(
            message: try await self.readDisplayInformationFromMailbox(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func readSecureContentFromMailbox(
        request: GRPCCore.ServerRequest<Digitalkey_Relay_V1_ReadSecureContentFromMailboxRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Digitalkey_Relay_V1_ReadSecureContentFromMailboxResponse> {
        return GRPCCore.ServerResponse<Digitalkey_Relay_V1_ReadSecureContentFromMailboxResponse>(
            message: try await self.readSecureContentFromMailbox(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func relinquishMailbox(
        request: GRPCCore.ServerRequest<Digitalkey_Relay_V1_RelinquishMailboxRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<Digitalkey_Relay_V1_RelinquishMailboxResponse> {
        return GRPCCore.ServerResponse<Digitalkey_Relay_V1_RelinquishMailboxResponse>(
            message: try await self.relinquishMailbox(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }
}

// MARK: digitalkey.relay.v1.RelayService (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Digitalkey_Relay_V1_RelayService {
    /// Generated client protocol for the "digitalkey.relay.v1.RelayService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "CreateMailbox" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 11.3.4.1: CreateMailbox — 发送方创建分享邮箱
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Digitalkey_Relay_V1_CreateMailboxRequest` message.
        ///   - serializer: A serializer for `Digitalkey_Relay_V1_CreateMailboxRequest` messages.
        ///   - deserializer: A deserializer for `Digitalkey_Relay_V1_CreateMailboxResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func createMailbox<Result>(
            request: GRPCCore.ClientRequest<Digitalkey_Relay_V1_CreateMailboxRequest>,
            serializer: some GRPCCore.MessageSerializer<Digitalkey_Relay_V1_CreateMailboxRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Digitalkey_Relay_V1_CreateMailboxResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Digitalkey_Relay_V1_CreateMailboxResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "UpdateMailbox" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 11.3.4.2: UpdateMailbox — 任一方更新邮箱内容
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Digitalkey_Relay_V1_UpdateMailboxRequest` message.
        ///   - serializer: A serializer for `Digitalkey_Relay_V1_UpdateMailboxRequest` messages.
        ///   - deserializer: A deserializer for `Digitalkey_Relay_V1_UpdateMailboxResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func updateMailbox<Result>(
            request: GRPCCore.ClientRequest<Digitalkey_Relay_V1_UpdateMailboxRequest>,
            serializer: some GRPCCore.MessageSerializer<Digitalkey_Relay_V1_UpdateMailboxRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Digitalkey_Relay_V1_UpdateMailboxResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Digitalkey_Relay_V1_UpdateMailboxResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "DeleteMailbox" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 11.3.4.3: DeleteMailbox — 删除邮箱
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Digitalkey_Relay_V1_DeleteMailboxRequest` message.
        ///   - serializer: A serializer for `Digitalkey_Relay_V1_DeleteMailboxRequest` messages.
        ///   - deserializer: A deserializer for `Digitalkey_Relay_V1_DeleteMailboxResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func deleteMailbox<Result>(
            request: GRPCCore.ClientRequest<Digitalkey_Relay_V1_DeleteMailboxRequest>,
            serializer: some GRPCCore.MessageSerializer<Digitalkey_Relay_V1_DeleteMailboxRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Digitalkey_Relay_V1_DeleteMailboxResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Digitalkey_Relay_V1_DeleteMailboxResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "ReadDisplayInformationFromMailbox" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 11.3.4.4: ReadDisplayInformationFromMailbox — 读取展示信息
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxRequest` message.
        ///   - serializer: A serializer for `Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxRequest` messages.
        ///   - deserializer: A deserializer for `Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func readDisplayInformationFromMailbox<Result>(
            request: GRPCCore.ClientRequest<Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxRequest>,
            serializer: some GRPCCore.MessageSerializer<Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "ReadSecureContentFromMailbox" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 11.3.4.5: ReadSecureContentFromMailbox — 读取加密内容
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Digitalkey_Relay_V1_ReadSecureContentFromMailboxRequest` message.
        ///   - serializer: A serializer for `Digitalkey_Relay_V1_ReadSecureContentFromMailboxRequest` messages.
        ///   - deserializer: A deserializer for `Digitalkey_Relay_V1_ReadSecureContentFromMailboxResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func readSecureContentFromMailbox<Result>(
            request: GRPCCore.ClientRequest<Digitalkey_Relay_V1_ReadSecureContentFromMailboxRequest>,
            serializer: some GRPCCore.MessageSerializer<Digitalkey_Relay_V1_ReadSecureContentFromMailboxRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Digitalkey_Relay_V1_ReadSecureContentFromMailboxResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Digitalkey_Relay_V1_ReadSecureContentFromMailboxResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "RelinquishMailbox" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 11.3.4.6: RelinquishMailbox — 转移邮箱到另一设备
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Digitalkey_Relay_V1_RelinquishMailboxRequest` message.
        ///   - serializer: A serializer for `Digitalkey_Relay_V1_RelinquishMailboxRequest` messages.
        ///   - deserializer: A deserializer for `Digitalkey_Relay_V1_RelinquishMailboxResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func relinquishMailbox<Result>(
            request: GRPCCore.ClientRequest<Digitalkey_Relay_V1_RelinquishMailboxRequest>,
            serializer: some GRPCCore.MessageSerializer<Digitalkey_Relay_V1_RelinquishMailboxRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Digitalkey_Relay_V1_RelinquishMailboxResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Digitalkey_Relay_V1_RelinquishMailboxResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "digitalkey.relay.v1.RelayService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "CreateMailbox" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 11.3.4.1: CreateMailbox — 发送方创建分享邮箱
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Digitalkey_Relay_V1_CreateMailboxRequest` message.
        ///   - serializer: A serializer for `Digitalkey_Relay_V1_CreateMailboxRequest` messages.
        ///   - deserializer: A deserializer for `Digitalkey_Relay_V1_CreateMailboxResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func createMailbox<Result>(
            request: GRPCCore.ClientRequest<Digitalkey_Relay_V1_CreateMailboxRequest>,
            serializer: some GRPCCore.MessageSerializer<Digitalkey_Relay_V1_CreateMailboxRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Digitalkey_Relay_V1_CreateMailboxResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Digitalkey_Relay_V1_CreateMailboxResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Digitalkey_Relay_V1_RelayService.Method.CreateMailbox.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "UpdateMailbox" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 11.3.4.2: UpdateMailbox — 任一方更新邮箱内容
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Digitalkey_Relay_V1_UpdateMailboxRequest` message.
        ///   - serializer: A serializer for `Digitalkey_Relay_V1_UpdateMailboxRequest` messages.
        ///   - deserializer: A deserializer for `Digitalkey_Relay_V1_UpdateMailboxResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func updateMailbox<Result>(
            request: GRPCCore.ClientRequest<Digitalkey_Relay_V1_UpdateMailboxRequest>,
            serializer: some GRPCCore.MessageSerializer<Digitalkey_Relay_V1_UpdateMailboxRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Digitalkey_Relay_V1_UpdateMailboxResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Digitalkey_Relay_V1_UpdateMailboxResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Digitalkey_Relay_V1_RelayService.Method.UpdateMailbox.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "DeleteMailbox" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 11.3.4.3: DeleteMailbox — 删除邮箱
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Digitalkey_Relay_V1_DeleteMailboxRequest` message.
        ///   - serializer: A serializer for `Digitalkey_Relay_V1_DeleteMailboxRequest` messages.
        ///   - deserializer: A deserializer for `Digitalkey_Relay_V1_DeleteMailboxResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func deleteMailbox<Result>(
            request: GRPCCore.ClientRequest<Digitalkey_Relay_V1_DeleteMailboxRequest>,
            serializer: some GRPCCore.MessageSerializer<Digitalkey_Relay_V1_DeleteMailboxRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Digitalkey_Relay_V1_DeleteMailboxResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Digitalkey_Relay_V1_DeleteMailboxResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Digitalkey_Relay_V1_RelayService.Method.DeleteMailbox.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "ReadDisplayInformationFromMailbox" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 11.3.4.4: ReadDisplayInformationFromMailbox — 读取展示信息
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxRequest` message.
        ///   - serializer: A serializer for `Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxRequest` messages.
        ///   - deserializer: A deserializer for `Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func readDisplayInformationFromMailbox<Result>(
            request: GRPCCore.ClientRequest<Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxRequest>,
            serializer: some GRPCCore.MessageSerializer<Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Digitalkey_Relay_V1_RelayService.Method.ReadDisplayInformationFromMailbox.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "ReadSecureContentFromMailbox" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 11.3.4.5: ReadSecureContentFromMailbox — 读取加密内容
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Digitalkey_Relay_V1_ReadSecureContentFromMailboxRequest` message.
        ///   - serializer: A serializer for `Digitalkey_Relay_V1_ReadSecureContentFromMailboxRequest` messages.
        ///   - deserializer: A deserializer for `Digitalkey_Relay_V1_ReadSecureContentFromMailboxResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func readSecureContentFromMailbox<Result>(
            request: GRPCCore.ClientRequest<Digitalkey_Relay_V1_ReadSecureContentFromMailboxRequest>,
            serializer: some GRPCCore.MessageSerializer<Digitalkey_Relay_V1_ReadSecureContentFromMailboxRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Digitalkey_Relay_V1_ReadSecureContentFromMailboxResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Digitalkey_Relay_V1_ReadSecureContentFromMailboxResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Digitalkey_Relay_V1_RelayService.Method.ReadSecureContentFromMailbox.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "RelinquishMailbox" method.
        ///
        /// > Source IDL Documentation:
        /// >
        /// > 11.3.4.6: RelinquishMailbox — 转移邮箱到另一设备
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Digitalkey_Relay_V1_RelinquishMailboxRequest` message.
        ///   - serializer: A serializer for `Digitalkey_Relay_V1_RelinquishMailboxRequest` messages.
        ///   - deserializer: A deserializer for `Digitalkey_Relay_V1_RelinquishMailboxResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func relinquishMailbox<Result>(
            request: GRPCCore.ClientRequest<Digitalkey_Relay_V1_RelinquishMailboxRequest>,
            serializer: some GRPCCore.MessageSerializer<Digitalkey_Relay_V1_RelinquishMailboxRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Digitalkey_Relay_V1_RelinquishMailboxResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Digitalkey_Relay_V1_RelinquishMailboxResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Digitalkey_Relay_V1_RelayService.Method.RelinquishMailbox.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Digitalkey_Relay_V1_RelayService.ClientProtocol {
    /// Call the "CreateMailbox" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > 11.3.4.1: CreateMailbox — 发送方创建分享邮箱
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Digitalkey_Relay_V1_CreateMailboxRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func createMailbox<Result>(
        request: GRPCCore.ClientRequest<Digitalkey_Relay_V1_CreateMailboxRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Digitalkey_Relay_V1_CreateMailboxResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.createMailbox(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Digitalkey_Relay_V1_CreateMailboxRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Digitalkey_Relay_V1_CreateMailboxResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UpdateMailbox" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > 11.3.4.2: UpdateMailbox — 任一方更新邮箱内容
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Digitalkey_Relay_V1_UpdateMailboxRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func updateMailbox<Result>(
        request: GRPCCore.ClientRequest<Digitalkey_Relay_V1_UpdateMailboxRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Digitalkey_Relay_V1_UpdateMailboxResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.updateMailbox(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Digitalkey_Relay_V1_UpdateMailboxRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Digitalkey_Relay_V1_UpdateMailboxResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "DeleteMailbox" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > 11.3.4.3: DeleteMailbox — 删除邮箱
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Digitalkey_Relay_V1_DeleteMailboxRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func deleteMailbox<Result>(
        request: GRPCCore.ClientRequest<Digitalkey_Relay_V1_DeleteMailboxRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Digitalkey_Relay_V1_DeleteMailboxResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.deleteMailbox(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Digitalkey_Relay_V1_DeleteMailboxRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Digitalkey_Relay_V1_DeleteMailboxResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ReadDisplayInformationFromMailbox" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > 11.3.4.4: ReadDisplayInformationFromMailbox — 读取展示信息
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func readDisplayInformationFromMailbox<Result>(
        request: GRPCCore.ClientRequest<Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.readDisplayInformationFromMailbox(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ReadSecureContentFromMailbox" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > 11.3.4.5: ReadSecureContentFromMailbox — 读取加密内容
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Digitalkey_Relay_V1_ReadSecureContentFromMailboxRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func readSecureContentFromMailbox<Result>(
        request: GRPCCore.ClientRequest<Digitalkey_Relay_V1_ReadSecureContentFromMailboxRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Digitalkey_Relay_V1_ReadSecureContentFromMailboxResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.readSecureContentFromMailbox(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Digitalkey_Relay_V1_ReadSecureContentFromMailboxRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Digitalkey_Relay_V1_ReadSecureContentFromMailboxResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "RelinquishMailbox" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > 11.3.4.6: RelinquishMailbox — 转移邮箱到另一设备
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Digitalkey_Relay_V1_RelinquishMailboxRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func relinquishMailbox<Result>(
        request: GRPCCore.ClientRequest<Digitalkey_Relay_V1_RelinquishMailboxRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Digitalkey_Relay_V1_RelinquishMailboxResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.relinquishMailbox(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Digitalkey_Relay_V1_RelinquishMailboxRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Digitalkey_Relay_V1_RelinquishMailboxResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Digitalkey_Relay_V1_RelayService.ClientProtocol {
    /// Call the "CreateMailbox" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > 11.3.4.1: CreateMailbox — 发送方创建分享邮箱
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func createMailbox<Result>(
        _ message: Digitalkey_Relay_V1_CreateMailboxRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Digitalkey_Relay_V1_CreateMailboxResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Digitalkey_Relay_V1_CreateMailboxRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.createMailbox(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "UpdateMailbox" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > 11.3.4.2: UpdateMailbox — 任一方更新邮箱内容
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func updateMailbox<Result>(
        _ message: Digitalkey_Relay_V1_UpdateMailboxRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Digitalkey_Relay_V1_UpdateMailboxResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Digitalkey_Relay_V1_UpdateMailboxRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.updateMailbox(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "DeleteMailbox" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > 11.3.4.3: DeleteMailbox — 删除邮箱
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func deleteMailbox<Result>(
        _ message: Digitalkey_Relay_V1_DeleteMailboxRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Digitalkey_Relay_V1_DeleteMailboxResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Digitalkey_Relay_V1_DeleteMailboxRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.deleteMailbox(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ReadDisplayInformationFromMailbox" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > 11.3.4.4: ReadDisplayInformationFromMailbox — 读取展示信息
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func readDisplayInformationFromMailbox<Result>(
        _ message: Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.readDisplayInformationFromMailbox(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ReadSecureContentFromMailbox" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > 11.3.4.5: ReadSecureContentFromMailbox — 读取加密内容
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func readSecureContentFromMailbox<Result>(
        _ message: Digitalkey_Relay_V1_ReadSecureContentFromMailboxRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Digitalkey_Relay_V1_ReadSecureContentFromMailboxResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Digitalkey_Relay_V1_ReadSecureContentFromMailboxRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.readSecureContentFromMailbox(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "RelinquishMailbox" method.
    ///
    /// > Source IDL Documentation:
    /// >
    /// > 11.3.4.6: RelinquishMailbox — 转移邮箱到另一设备
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func relinquishMailbox<Result>(
        _ message: Digitalkey_Relay_V1_RelinquishMailboxRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Digitalkey_Relay_V1_RelinquishMailboxResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Digitalkey_Relay_V1_RelinquishMailboxRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.relinquishMailbox(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}