// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: relay.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated enum Digitalkey_Relay_V1_MailboxStatus: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0

  /// 已创建
  case created // = 1

  /// 发送方更新
  case updatedBySender // = 2

  /// 接收方更新
  case updatedByReceiver // = 3

  /// 完成
  case completed // = 4

  /// 任一方取消
  case cancelled // = 5

  /// TTL 超时
  case expired // = 6
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .created
    case 2: self = .updatedBySender
    case 3: self = .updatedByReceiver
    case 4: self = .completed
    case 5: self = .cancelled
    case 6: self = .expired
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .created: return 1
    case .updatedBySender: return 2
    case .updatedByReceiver: return 3
    case .completed: return 4
    case .cancelled: return 5
    case .expired: return 6
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Digitalkey_Relay_V1_MailboxStatus] = [
    .unspecified,
    .created,
    .updatedBySender,
    .updatedByReceiver,
    .completed,
    .cancelled,
    .expired,
  ]

}

public nonisolated enum Digitalkey_Relay_V1_AccessRights: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0

  /// R
  case read // = 1

  /// W
  case write // = 2

  /// R
  case readWrite // = 3

  /// RWD — CCC 规范要求
  case readWriteDelete // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .read
    case 2: self = .write
    case 3: self = .readWrite
    case 4: self = .readWriteDelete
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .read: return 1
    case .write: return 2
    case .readWrite: return 3
    case .readWriteDelete: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Digitalkey_Relay_V1_AccessRights] = [
    .unspecified,
    .read,
    .write,
    .readWrite,
    .readWriteDelete,
  ]

}

public nonisolated struct Digitalkey_Relay_V1_MailboxConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 应设为 RWD
  public var accessRights: Digitalkey_Relay_V1_AccessRights = .unspecified

  /// 邮箱过期时间
  public var expirationSeconds: Int64 = 0

  /// 最大更新次数 (默认 10)
  public var maxUpdates: Int32 = 0

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Digitalkey_Relay_V1_CreateMailboxRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 加密的 provisioning info (JSON format per §11.3)
  public var payload: Data = Data()

  /// 展示信息（车品牌、型号等）
  public var displayInfo: Data = Data()

  /// 发送方 Push 通知 token
  public var notificationToken: String = String()

  public var senderDeviceID: String = String()

  /// e.g. "apple", "samsung"
  public var senderVendor: String = String()

  public var config: Digitalkey_Relay_V1_MailboxConfig {
    get {_config ?? Digitalkey_Relay_V1_MailboxConfig()}
    set {_config = newValue}
  }
  /// Returns true if `config` has been explicitly set.
  public var hasConfig: Bool {self._config != nil}
  /// Clears the value of `config`. Subsequent reads from it will return its default value.
  public mutating func clearConfig() {self._config = nil}

  public var traceID: String = String()

  /// §11.3.5: sender device attestation for cross-OEM auth
  public var deviceAttestation: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _config: Digitalkey_Relay_V1_MailboxConfig? = nil
}

public nonisolated struct Digitalkey_Relay_V1_CreateMailboxResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var mailboxID: String = String()

  /// 完整分享 URL（含 Secret fragment）
  public var sharingURL: String = String()

  /// unix millis
  public var expiresAt: Int64 = 0

  public var errorCode: String = String()

  public var errorMsg: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Digitalkey_Relay_V1_UpdateMailboxRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var mailboxID: String = String()

  /// 更新内容（KeySigningRequest / ImportRequest / Cancellation）
  public var payload: Data = Data()

  /// 1=KeyCreation, 2=KeySigning, 3=Import, 4=SenderCancel, 5=ReceiverCancel
  public var sharingDataType: Int32 = 0

  /// 更新方的 Push token
  public var notificationToken: String = String()

  public var updaterDeviceID: String = String()

  public var traceID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Digitalkey_Relay_V1_UpdateMailboxResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var status: Digitalkey_Relay_V1_MailboxStatus = .unspecified

  /// 乐观锁版本号
  public var version: Int64 = 0

  public var errorCode: String = String()

  public var errorMsg: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Digitalkey_Relay_V1_DeleteMailboxRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var mailboxID: String = String()

  /// "completed" / "cancelled" / "expired"
  public var reason: String = String()

  public var deleterDeviceID: String = String()

  public var traceID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Digitalkey_Relay_V1_DeleteMailboxResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var success: Bool = false

  public var errorCode: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// ReadDisplayInformationFromMailboxRequest
public nonisolated struct Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var mailboxID: String = String()

  public var deviceID: String = String()

  public var traceID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// ReadDisplayInformationFromMailboxResponse
public nonisolated struct Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var displayInfo: Data = Data()

  public var version: Int64 = 0

  public var errorCode: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// ReadSecureContentFromMailboxRequest
public nonisolated struct Digitalkey_Relay_V1_ReadSecureContentFromMailboxRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var mailboxID: String = String()

  public var deviceID: String = String()

  public var traceID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// ReadSecureContentFromMailboxResponse
public nonisolated struct Digitalkey_Relay_V1_ReadSecureContentFromMailboxResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 加密内容
  public var payload: Data = Data()

  public var version: Int64 = 0

  public var errorCode: String = String()

  public var errorMsg: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Digitalkey_Relay_V1_RelinquishMailboxRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var mailboxID: String = String()

  /// 当前持有设备
  public var fromDeviceID: String = String()

  /// 目标设备
  public var toDeviceID: String = String()

  public var traceID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Digitalkey_Relay_V1_RelinquishMailboxResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var success: Bool = false

  public var errorCode: String = String()

  public var errorMsg: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public nonisolated struct Digitalkey_Relay_V1_Mailbox: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var mailboxID: String = String()

  public var status: Digitalkey_Relay_V1_MailboxStatus = .unspecified

  public var senderDeviceID: String = String()

  public var senderVendor: String = String()

  /// 发送方 push token
  public var notificationToken: String = String()

  public var displayInfo: Data = Data()

  /// unix millis
  public var createdAt: Int64 = 0

  public var expiresAt: Int64 = 0

  public var updatedAt: Int64 = 0

  public var version: Int64 = 0

  public var sharingURL: String = String()

  /// 接收方设备 ID（Relinquish 后更新）
  public var receiverDeviceID: String = String()

  /// 接收方厂商
  public var receiverVendor: String = String()

  /// 当前更新次数
  public var updateCount: Int32 = 0

  /// 最大更新次数
  public var maxUpdates: Int32 = 0

  /// §11.3.5: sender device attestation (persisted)
  public var deviceAttestation: Data = Data()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "digitalkey.relay.v1"

nonisolated extension Digitalkey_Relay_V1_MailboxStatus: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0MAILBOX_STATUS_UNSPECIFIED\0\u{1}CREATED\0\u{1}UPDATED_BY_SENDER\0\u{1}UPDATED_BY_RECEIVER\0\u{1}COMPLETED\0\u{1}CANCELLED\0\u{1}EXPIRED\0")
}

nonisolated extension Digitalkey_Relay_V1_AccessRights: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0ACCESS_RIGHTS_UNSPECIFIED\0\u{1}READ\0\u{1}WRITE\0\u{1}READ_WRITE\0\u{1}READ_WRITE_DELETE\0")
}

nonisolated extension Digitalkey_Relay_V1_MailboxConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MailboxConfig"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}access_rights\0\u{3}expiration_seconds\0\u{3}max_updates\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.accessRights) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.expirationSeconds) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.maxUpdates) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.accessRights != .unspecified {
      try visitor.visitSingularEnumField(value: self.accessRights, fieldNumber: 1)
    }
    if self.expirationSeconds != 0 {
      try visitor.visitSingularInt64Field(value: self.expirationSeconds, fieldNumber: 2)
    }
    if self.maxUpdates != 0 {
      try visitor.visitSingularInt32Field(value: self.maxUpdates, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Digitalkey_Relay_V1_MailboxConfig, rhs: Digitalkey_Relay_V1_MailboxConfig) -> Bool {
    if lhs.accessRights != rhs.accessRights {return false}
    if lhs.expirationSeconds != rhs.expirationSeconds {return false}
    if lhs.maxUpdates != rhs.maxUpdates {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Digitalkey_Relay_V1_CreateMailboxRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CreateMailboxRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}payload\0\u{3}display_info\0\u{3}notification_token\0\u{3}sender_device_id\0\u{3}sender_vendor\0\u{1}config\0\u{3}trace_id\0\u{3}device_attestation\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.payload) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.displayInfo) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.notificationToken) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.senderDeviceID) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.senderVendor) }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._config) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.traceID) }()
      case 8: try { try decoder.decodeSingularBytesField(value: &self.deviceAttestation) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.payload.isEmpty {
      try visitor.visitSingularBytesField(value: self.payload, fieldNumber: 1)
    }
    if !self.displayInfo.isEmpty {
      try visitor.visitSingularBytesField(value: self.displayInfo, fieldNumber: 2)
    }
    if !self.notificationToken.isEmpty {
      try visitor.visitSingularStringField(value: self.notificationToken, fieldNumber: 3)
    }
    if !self.senderDeviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.senderDeviceID, fieldNumber: 4)
    }
    if !self.senderVendor.isEmpty {
      try visitor.visitSingularStringField(value: self.senderVendor, fieldNumber: 5)
    }
    try { if let v = self._config {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    if !self.traceID.isEmpty {
      try visitor.visitSingularStringField(value: self.traceID, fieldNumber: 7)
    }
    if !self.deviceAttestation.isEmpty {
      try visitor.visitSingularBytesField(value: self.deviceAttestation, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Digitalkey_Relay_V1_CreateMailboxRequest, rhs: Digitalkey_Relay_V1_CreateMailboxRequest) -> Bool {
    if lhs.payload != rhs.payload {return false}
    if lhs.displayInfo != rhs.displayInfo {return false}
    if lhs.notificationToken != rhs.notificationToken {return false}
    if lhs.senderDeviceID != rhs.senderDeviceID {return false}
    if lhs.senderVendor != rhs.senderVendor {return false}
    if lhs._config != rhs._config {return false}
    if lhs.traceID != rhs.traceID {return false}
    if lhs.deviceAttestation != rhs.deviceAttestation {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Digitalkey_Relay_V1_CreateMailboxResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CreateMailboxResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}mailbox_id\0\u{3}sharing_url\0\u{3}expires_at\0\u{3}error_code\0\u{3}error_msg\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.mailboxID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.sharingURL) }()
      case 3: try { try decoder.decodeSingularInt64Field(value: &self.expiresAt) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.errorCode) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.errorMsg) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.mailboxID.isEmpty {
      try visitor.visitSingularStringField(value: self.mailboxID, fieldNumber: 1)
    }
    if !self.sharingURL.isEmpty {
      try visitor.visitSingularStringField(value: self.sharingURL, fieldNumber: 2)
    }
    if self.expiresAt != 0 {
      try visitor.visitSingularInt64Field(value: self.expiresAt, fieldNumber: 3)
    }
    if !self.errorCode.isEmpty {
      try visitor.visitSingularStringField(value: self.errorCode, fieldNumber: 4)
    }
    if !self.errorMsg.isEmpty {
      try visitor.visitSingularStringField(value: self.errorMsg, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Digitalkey_Relay_V1_CreateMailboxResponse, rhs: Digitalkey_Relay_V1_CreateMailboxResponse) -> Bool {
    if lhs.mailboxID != rhs.mailboxID {return false}
    if lhs.sharingURL != rhs.sharingURL {return false}
    if lhs.expiresAt != rhs.expiresAt {return false}
    if lhs.errorCode != rhs.errorCode {return false}
    if lhs.errorMsg != rhs.errorMsg {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Digitalkey_Relay_V1_UpdateMailboxRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UpdateMailboxRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}mailbox_id\0\u{1}payload\0\u{3}sharing_data_type\0\u{3}notification_token\0\u{3}updater_device_id\0\u{3}trace_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.mailboxID) }()
      case 2: try { try decoder.decodeSingularBytesField(value: &self.payload) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.sharingDataType) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.notificationToken) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.updaterDeviceID) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.traceID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.mailboxID.isEmpty {
      try visitor.visitSingularStringField(value: self.mailboxID, fieldNumber: 1)
    }
    if !self.payload.isEmpty {
      try visitor.visitSingularBytesField(value: self.payload, fieldNumber: 2)
    }
    if self.sharingDataType != 0 {
      try visitor.visitSingularInt32Field(value: self.sharingDataType, fieldNumber: 3)
    }
    if !self.notificationToken.isEmpty {
      try visitor.visitSingularStringField(value: self.notificationToken, fieldNumber: 4)
    }
    if !self.updaterDeviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.updaterDeviceID, fieldNumber: 5)
    }
    if !self.traceID.isEmpty {
      try visitor.visitSingularStringField(value: self.traceID, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Digitalkey_Relay_V1_UpdateMailboxRequest, rhs: Digitalkey_Relay_V1_UpdateMailboxRequest) -> Bool {
    if lhs.mailboxID != rhs.mailboxID {return false}
    if lhs.payload != rhs.payload {return false}
    if lhs.sharingDataType != rhs.sharingDataType {return false}
    if lhs.notificationToken != rhs.notificationToken {return false}
    if lhs.updaterDeviceID != rhs.updaterDeviceID {return false}
    if lhs.traceID != rhs.traceID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Digitalkey_Relay_V1_UpdateMailboxResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UpdateMailboxResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}status\0\u{1}version\0\u{3}error_code\0\u{3}error_msg\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.status) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.version) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.errorCode) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.errorMsg) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.status != .unspecified {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 1)
    }
    if self.version != 0 {
      try visitor.visitSingularInt64Field(value: self.version, fieldNumber: 2)
    }
    if !self.errorCode.isEmpty {
      try visitor.visitSingularStringField(value: self.errorCode, fieldNumber: 3)
    }
    if !self.errorMsg.isEmpty {
      try visitor.visitSingularStringField(value: self.errorMsg, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Digitalkey_Relay_V1_UpdateMailboxResponse, rhs: Digitalkey_Relay_V1_UpdateMailboxResponse) -> Bool {
    if lhs.status != rhs.status {return false}
    if lhs.version != rhs.version {return false}
    if lhs.errorCode != rhs.errorCode {return false}
    if lhs.errorMsg != rhs.errorMsg {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Digitalkey_Relay_V1_DeleteMailboxRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeleteMailboxRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}mailbox_id\0\u{1}reason\0\u{3}deleter_device_id\0\u{3}trace_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.mailboxID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.reason) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.deleterDeviceID) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.traceID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.mailboxID.isEmpty {
      try visitor.visitSingularStringField(value: self.mailboxID, fieldNumber: 1)
    }
    if !self.reason.isEmpty {
      try visitor.visitSingularStringField(value: self.reason, fieldNumber: 2)
    }
    if !self.deleterDeviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deleterDeviceID, fieldNumber: 3)
    }
    if !self.traceID.isEmpty {
      try visitor.visitSingularStringField(value: self.traceID, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Digitalkey_Relay_V1_DeleteMailboxRequest, rhs: Digitalkey_Relay_V1_DeleteMailboxRequest) -> Bool {
    if lhs.mailboxID != rhs.mailboxID {return false}
    if lhs.reason != rhs.reason {return false}
    if lhs.deleterDeviceID != rhs.deleterDeviceID {return false}
    if lhs.traceID != rhs.traceID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Digitalkey_Relay_V1_DeleteMailboxResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeleteMailboxResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}success\0\u{3}error_code\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.errorCode) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 1)
    }
    if !self.errorCode.isEmpty {
      try visitor.visitSingularStringField(value: self.errorCode, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Digitalkey_Relay_V1_DeleteMailboxResponse, rhs: Digitalkey_Relay_V1_DeleteMailboxResponse) -> Bool {
    if lhs.success != rhs.success {return false}
    if lhs.errorCode != rhs.errorCode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ReadDisplayInformationFromMailboxRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}mailbox_id\0\u{3}device_id\0\u{3}trace_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.mailboxID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.traceID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.mailboxID.isEmpty {
      try visitor.visitSingularStringField(value: self.mailboxID, fieldNumber: 1)
    }
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 2)
    }
    if !self.traceID.isEmpty {
      try visitor.visitSingularStringField(value: self.traceID, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxRequest, rhs: Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxRequest) -> Bool {
    if lhs.mailboxID != rhs.mailboxID {return false}
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.traceID != rhs.traceID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ReadDisplayInformationFromMailboxResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}display_info\0\u{1}version\0\u{3}error_code\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.displayInfo) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.version) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.errorCode) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.displayInfo.isEmpty {
      try visitor.visitSingularBytesField(value: self.displayInfo, fieldNumber: 1)
    }
    if self.version != 0 {
      try visitor.visitSingularInt64Field(value: self.version, fieldNumber: 2)
    }
    if !self.errorCode.isEmpty {
      try visitor.visitSingularStringField(value: self.errorCode, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxResponse, rhs: Digitalkey_Relay_V1_ReadDisplayInformationFromMailboxResponse) -> Bool {
    if lhs.displayInfo != rhs.displayInfo {return false}
    if lhs.version != rhs.version {return false}
    if lhs.errorCode != rhs.errorCode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Digitalkey_Relay_V1_ReadSecureContentFromMailboxRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ReadSecureContentFromMailboxRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}mailbox_id\0\u{3}device_id\0\u{3}trace_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.mailboxID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.deviceID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.traceID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.mailboxID.isEmpty {
      try visitor.visitSingularStringField(value: self.mailboxID, fieldNumber: 1)
    }
    if !self.deviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.deviceID, fieldNumber: 2)
    }
    if !self.traceID.isEmpty {
      try visitor.visitSingularStringField(value: self.traceID, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Digitalkey_Relay_V1_ReadSecureContentFromMailboxRequest, rhs: Digitalkey_Relay_V1_ReadSecureContentFromMailboxRequest) -> Bool {
    if lhs.mailboxID != rhs.mailboxID {return false}
    if lhs.deviceID != rhs.deviceID {return false}
    if lhs.traceID != rhs.traceID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Digitalkey_Relay_V1_ReadSecureContentFromMailboxResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ReadSecureContentFromMailboxResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}payload\0\u{1}version\0\u{3}error_code\0\u{3}error_msg\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.payload) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self.version) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.errorCode) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.errorMsg) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.payload.isEmpty {
      try visitor.visitSingularBytesField(value: self.payload, fieldNumber: 1)
    }
    if self.version != 0 {
      try visitor.visitSingularInt64Field(value: self.version, fieldNumber: 2)
    }
    if !self.errorCode.isEmpty {
      try visitor.visitSingularStringField(value: self.errorCode, fieldNumber: 3)
    }
    if !self.errorMsg.isEmpty {
      try visitor.visitSingularStringField(value: self.errorMsg, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Digitalkey_Relay_V1_ReadSecureContentFromMailboxResponse, rhs: Digitalkey_Relay_V1_ReadSecureContentFromMailboxResponse) -> Bool {
    if lhs.payload != rhs.payload {return false}
    if lhs.version != rhs.version {return false}
    if lhs.errorCode != rhs.errorCode {return false}
    if lhs.errorMsg != rhs.errorMsg {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Digitalkey_Relay_V1_RelinquishMailboxRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RelinquishMailboxRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}mailbox_id\0\u{3}from_device_id\0\u{3}to_device_id\0\u{3}trace_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.mailboxID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.fromDeviceID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.toDeviceID) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.traceID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.mailboxID.isEmpty {
      try visitor.visitSingularStringField(value: self.mailboxID, fieldNumber: 1)
    }
    if !self.fromDeviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.fromDeviceID, fieldNumber: 2)
    }
    if !self.toDeviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.toDeviceID, fieldNumber: 3)
    }
    if !self.traceID.isEmpty {
      try visitor.visitSingularStringField(value: self.traceID, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Digitalkey_Relay_V1_RelinquishMailboxRequest, rhs: Digitalkey_Relay_V1_RelinquishMailboxRequest) -> Bool {
    if lhs.mailboxID != rhs.mailboxID {return false}
    if lhs.fromDeviceID != rhs.fromDeviceID {return false}
    if lhs.toDeviceID != rhs.toDeviceID {return false}
    if lhs.traceID != rhs.traceID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Digitalkey_Relay_V1_RelinquishMailboxResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RelinquishMailboxResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}success\0\u{3}error_code\0\u{3}error_msg\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.success) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.errorCode) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.errorMsg) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.success != false {
      try visitor.visitSingularBoolField(value: self.success, fieldNumber: 1)
    }
    if !self.errorCode.isEmpty {
      try visitor.visitSingularStringField(value: self.errorCode, fieldNumber: 2)
    }
    if !self.errorMsg.isEmpty {
      try visitor.visitSingularStringField(value: self.errorMsg, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Digitalkey_Relay_V1_RelinquishMailboxResponse, rhs: Digitalkey_Relay_V1_RelinquishMailboxResponse) -> Bool {
    if lhs.success != rhs.success {return false}
    if lhs.errorCode != rhs.errorCode {return false}
    if lhs.errorMsg != rhs.errorMsg {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

nonisolated extension Digitalkey_Relay_V1_Mailbox: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Mailbox"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}mailbox_id\0\u{1}status\0\u{3}sender_device_id\0\u{3}sender_vendor\0\u{3}notification_token\0\u{3}display_info\0\u{3}created_at\0\u{3}expires_at\0\u{3}updated_at\0\u{1}version\0\u{3}sharing_url\0\u{3}receiver_device_id\0\u{3}receiver_vendor\0\u{3}update_count\0\u{3}max_updates\0\u{3}device_attestation\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.mailboxID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.status) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.senderDeviceID) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.senderVendor) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.notificationToken) }()
      case 6: try { try decoder.decodeSingularBytesField(value: &self.displayInfo) }()
      case 7: try { try decoder.decodeSingularInt64Field(value: &self.createdAt) }()
      case 8: try { try decoder.decodeSingularInt64Field(value: &self.expiresAt) }()
      case 9: try { try decoder.decodeSingularInt64Field(value: &self.updatedAt) }()
      case 10: try { try decoder.decodeSingularInt64Field(value: &self.version) }()
      case 11: try { try decoder.decodeSingularStringField(value: &self.sharingURL) }()
      case 12: try { try decoder.decodeSingularStringField(value: &self.receiverDeviceID) }()
      case 13: try { try decoder.decodeSingularStringField(value: &self.receiverVendor) }()
      case 14: try { try decoder.decodeSingularInt32Field(value: &self.updateCount) }()
      case 15: try { try decoder.decodeSingularInt32Field(value: &self.maxUpdates) }()
      case 16: try { try decoder.decodeSingularBytesField(value: &self.deviceAttestation) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.mailboxID.isEmpty {
      try visitor.visitSingularStringField(value: self.mailboxID, fieldNumber: 1)
    }
    if self.status != .unspecified {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 2)
    }
    if !self.senderDeviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.senderDeviceID, fieldNumber: 3)
    }
    if !self.senderVendor.isEmpty {
      try visitor.visitSingularStringField(value: self.senderVendor, fieldNumber: 4)
    }
    if !self.notificationToken.isEmpty {
      try visitor.visitSingularStringField(value: self.notificationToken, fieldNumber: 5)
    }
    if !self.displayInfo.isEmpty {
      try visitor.visitSingularBytesField(value: self.displayInfo, fieldNumber: 6)
    }
    if self.createdAt != 0 {
      try visitor.visitSingularInt64Field(value: self.createdAt, fieldNumber: 7)
    }
    if self.expiresAt != 0 {
      try visitor.visitSingularInt64Field(value: self.expiresAt, fieldNumber: 8)
    }
    if self.updatedAt != 0 {
      try visitor.visitSingularInt64Field(value: self.updatedAt, fieldNumber: 9)
    }
    if self.version != 0 {
      try visitor.visitSingularInt64Field(value: self.version, fieldNumber: 10)
    }
    if !self.sharingURL.isEmpty {
      try visitor.visitSingularStringField(value: self.sharingURL, fieldNumber: 11)
    }
    if !self.receiverDeviceID.isEmpty {
      try visitor.visitSingularStringField(value: self.receiverDeviceID, fieldNumber: 12)
    }
    if !self.receiverVendor.isEmpty {
      try visitor.visitSingularStringField(value: self.receiverVendor, fieldNumber: 13)
    }
    if self.updateCount != 0 {
      try visitor.visitSingularInt32Field(value: self.updateCount, fieldNumber: 14)
    }
    if self.maxUpdates != 0 {
      try visitor.visitSingularInt32Field(value: self.maxUpdates, fieldNumber: 15)
    }
    if !self.deviceAttestation.isEmpty {
      try visitor.visitSingularBytesField(value: self.deviceAttestation, fieldNumber: 16)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Digitalkey_Relay_V1_Mailbox, rhs: Digitalkey_Relay_V1_Mailbox) -> Bool {
    if lhs.mailboxID != rhs.mailboxID {return false}
    if lhs.status != rhs.status {return false}
    if lhs.senderDeviceID != rhs.senderDeviceID {return false}
    if lhs.senderVendor != rhs.senderVendor {return false}
    if lhs.notificationToken != rhs.notificationToken {return false}
    if lhs.displayInfo != rhs.displayInfo {return false}
    if lhs.createdAt != rhs.createdAt {return false}
    if lhs.expiresAt != rhs.expiresAt {return false}
    if lhs.updatedAt != rhs.updatedAt {return false}
    if lhs.version != rhs.version {return false}
    if lhs.sharingURL != rhs.sharingURL {return false}
    if lhs.receiverDeviceID != rhs.receiverDeviceID {return false}
    if lhs.receiverVendor != rhs.receiverVendor {return false}
    if lhs.updateCount != rhs.updateCount {return false}
    if lhs.maxUpdates != rhs.maxUpdates {return false}
    if lhs.deviceAttestation != rhs.deviceAttestation {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
