// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hub.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.hub.v1;

@kotlin.jvm.JvmName("-initializeacceptShareResponse")
public inline fun acceptShareResponse(block: digitalkey.hub.v1.AcceptShareResponseKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.AcceptShareResponse =
  digitalkey.hub.v1.AcceptShareResponseKt.Dsl._create(digitalkey.hub.v1.Hub.AcceptShareResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.hub.v1.AcceptShareResponse`
 */
public object AcceptShareResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.hub.v1.Hub.AcceptShareResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.hub.v1.Hub.AcceptShareResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.hub.v1.Hub.AcceptShareResponse = _builder.build()

    /**
     * `.digitalkey.hub.v1.DigitalKey key = 1;`
     */
    public var key: digitalkey.hub.v1.Hub.DigitalKey
      @kotlin.jvm.JvmName("getKey")
        get() = _builder.key
      @kotlin.jvm.JvmName("setKey")
        set(value) {
        _builder.key = value
      }
    /**
     * `.digitalkey.hub.v1.DigitalKey key = 1;`
     */
    public fun clearKey() {
      _builder.clearKey()
    }
    /**
     * `.digitalkey.hub.v1.DigitalKey key = 1;`
     * @return Whether the key field is set.
     */
    public fun hasKey(): kotlin.Boolean {
      return _builder.hasKey()
    }

    public val AcceptShareResponseKt.Dsl.keyOrNull: digitalkey.hub.v1.Hub.DigitalKey?
      get() = _builder.keyOrNull

    /**
     * `bytes shared_secret = 2;`
     */
    public var sharedSecret: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getSharedSecret")
        get() = _builder.sharedSecret
      @kotlin.jvm.JvmName("setSharedSecret")
        set(value) {
        _builder.sharedSecret = value
      }
    /**
     * `bytes shared_secret = 2;`
     */
    public fun clearSharedSecret() {
      _builder.clearSharedSecret()
    }

    /**
     * `string error_code = 3;`
     */
    public var errorCode: kotlin.String
      @kotlin.jvm.JvmName("getErrorCode")
        get() = _builder.errorCode
      @kotlin.jvm.JvmName("setErrorCode")
        set(value) {
        _builder.errorCode = value
      }
    /**
     * `string error_code = 3;`
     */
    public fun clearErrorCode() {
      _builder.clearErrorCode()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.hub.v1.Hub.AcceptShareResponse.copy(block: `digitalkey.hub.v1`.AcceptShareResponseKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.AcceptShareResponse =
  `digitalkey.hub.v1`.AcceptShareResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val digitalkey.hub.v1.Hub.AcceptShareResponseOrBuilder.keyOrNull: digitalkey.hub.v1.Hub.DigitalKey?
  get() = if (hasKey()) getKey() else null

