// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hub.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.hub.v1;

@kotlin.jvm.JvmName("-initializeacceptShareRequest")
public inline fun acceptShareRequest(block: digitalkey.hub.v1.AcceptShareRequestKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.AcceptShareRequest =
  digitalkey.hub.v1.AcceptShareRequestKt.Dsl._create(digitalkey.hub.v1.Hub.AcceptShareRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.hub.v1.AcceptShareRequest`
 */
public object AcceptShareRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.hub.v1.Hub.AcceptShareRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.hub.v1.Hub.AcceptShareRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.hub.v1.Hub.AcceptShareRequest = _builder.build()

    /**
     * `string share_code = 1;`
     */
    public var shareCode: kotlin.String
      @kotlin.jvm.JvmName("getShareCode")
        get() = _builder.shareCode
      @kotlin.jvm.JvmName("setShareCode")
        set(value) {
        _builder.shareCode = value
      }
    /**
     * `string share_code = 1;`
     */
    public fun clearShareCode() {
      _builder.clearShareCode()
    }

    /**
     * `string device_id = 2;`
     */
    public var deviceId: kotlin.String
      @kotlin.jvm.JvmName("getDeviceId")
        get() = _builder.deviceId
      @kotlin.jvm.JvmName("setDeviceId")
        set(value) {
        _builder.deviceId = value
      }
    /**
     * `string device_id = 2;`
     */
    public fun clearDeviceId() {
      _builder.clearDeviceId()
    }

    /**
     * `string user_id = 3;`
     */
    public var userId: kotlin.String
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `string user_id = 3;`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * `.digitalkey.hub.v1.PhoneVendor vendor = 4;`
     */
    public var vendor: digitalkey.hub.v1.Hub.PhoneVendor
      @kotlin.jvm.JvmName("getVendor")
        get() = _builder.vendor
      @kotlin.jvm.JvmName("setVendor")
        set(value) {
        _builder.vendor = value
      }
    public var vendorValue: kotlin.Int
      @kotlin.jvm.JvmName("getVendorValue")
        get() = _builder.vendorValue
      @kotlin.jvm.JvmName("setVendorValue")
        set(value) {
        _builder.vendorValue = value
      }
    /**
     * `.digitalkey.hub.v1.PhoneVendor vendor = 4;`
     */
    public fun clearVendor() {
      _builder.clearVendor()
    }

    /**
     * `bytes device_pubkey = 5;`
     */
    public var devicePubkey: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getDevicePubkey")
        get() = _builder.devicePubkey
      @kotlin.jvm.JvmName("setDevicePubkey")
        set(value) {
        _builder.devicePubkey = value
      }
    /**
     * `bytes device_pubkey = 5;`
     */
    public fun clearDevicePubkey() {
      _builder.clearDevicePubkey()
    }

    /**
     * `string trace_id = 6;`
     */
    public var traceId: kotlin.String
      @kotlin.jvm.JvmName("getTraceId")
        get() = _builder.traceId
      @kotlin.jvm.JvmName("setTraceId")
        set(value) {
        _builder.traceId = value
      }
    /**
     * `string trace_id = 6;`
     */
    public fun clearTraceId() {
      _builder.clearTraceId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.hub.v1.Hub.AcceptShareRequest.copy(block: `digitalkey.hub.v1`.AcceptShareRequestKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.AcceptShareRequest =
  `digitalkey.hub.v1`.AcceptShareRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

