// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hub.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.hub.v1;

@kotlin.jvm.JvmName("-initializeadapterStatus")
public inline fun adapterStatus(block: digitalkey.hub.v1.AdapterStatusKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.AdapterStatus =
  digitalkey.hub.v1.AdapterStatusKt.Dsl._create(digitalkey.hub.v1.Hub.AdapterStatus.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.hub.v1.AdapterStatus`
 */
public object AdapterStatusKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.hub.v1.Hub.AdapterStatus.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.hub.v1.Hub.AdapterStatus.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.hub.v1.Hub.AdapterStatus = _builder.build()

    /**
     * `string vendor = 1;`
     */
    public var vendor: kotlin.String
      @kotlin.jvm.JvmName("getVendor")
        get() = _builder.vendor
      @kotlin.jvm.JvmName("setVendor")
        set(value) {
        _builder.vendor = value
      }
    /**
     * `string vendor = 1;`
     */
    public fun clearVendor() {
      _builder.clearVendor()
    }

    /**
     * `string protocol = 2;`
     */
    public var protocol: kotlin.String
      @kotlin.jvm.JvmName("getProtocol")
        get() = _builder.protocol
      @kotlin.jvm.JvmName("setProtocol")
        set(value) {
        _builder.protocol = value
      }
    /**
     * `string protocol = 2;`
     */
    public fun clearProtocol() {
      _builder.clearProtocol()
    }

    /**
     * `bool healthy = 3;`
     */
    public var healthy: kotlin.Boolean
      @kotlin.jvm.JvmName("getHealthy")
        get() = _builder.healthy
      @kotlin.jvm.JvmName("setHealthy")
        set(value) {
        _builder.healthy = value
      }
    /**
     * `bool healthy = 3;`
     */
    public fun clearHealthy() {
      _builder.clearHealthy()
    }

    /**
     * `int64 last_check_ms = 4;`
     */
    public var lastCheckMs: kotlin.Long
      @kotlin.jvm.JvmName("getLastCheckMs")
        get() = _builder.lastCheckMs
      @kotlin.jvm.JvmName("setLastCheckMs")
        set(value) {
        _builder.lastCheckMs = value
      }
    /**
     * `int64 last_check_ms = 4;`
     */
    public fun clearLastCheckMs() {
      _builder.clearLastCheckMs()
    }

    /**
     * `string error_msg = 5;`
     */
    public var errorMsg: kotlin.String
      @kotlin.jvm.JvmName("getErrorMsg")
        get() = _builder.errorMsg
      @kotlin.jvm.JvmName("setErrorMsg")
        set(value) {
        _builder.errorMsg = value
      }
    /**
     * `string error_msg = 5;`
     */
    public fun clearErrorMsg() {
      _builder.clearErrorMsg()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.hub.v1.Hub.AdapterStatus.copy(block: `digitalkey.hub.v1`.AdapterStatusKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.AdapterStatus =
  `digitalkey.hub.v1`.AdapterStatusKt.Dsl._create(this.toBuilder()).apply { block() }._build()

