// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hub.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.hub.v1;

@kotlin.jvm.JvmName("-initializebindKeyRequest")
public inline fun bindKeyRequest(block: digitalkey.hub.v1.BindKeyRequestKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.BindKeyRequest =
  digitalkey.hub.v1.BindKeyRequestKt.Dsl._create(digitalkey.hub.v1.Hub.BindKeyRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.hub.v1.BindKeyRequest`
 */
public object BindKeyRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.hub.v1.Hub.BindKeyRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.hub.v1.Hub.BindKeyRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.hub.v1.Hub.BindKeyRequest = _builder.build()

    /**
     * `string vehicle_id = 1;`
     */
    public var vehicleId: kotlin.String
      @kotlin.jvm.JvmName("getVehicleId")
        get() = _builder.vehicleId
      @kotlin.jvm.JvmName("setVehicleId")
        set(value) {
        _builder.vehicleId = value
      }
    /**
     * `string vehicle_id = 1;`
     */
    public fun clearVehicleId() {
      _builder.clearVehicleId()
    }

    /**
     * `string device_id = 2;`
     */
    public var deviceId: kotlin.String
      @kotlin.jvm.JvmName("getDeviceId")
        get() = _builder.deviceId
      @kotlin.jvm.JvmName("setDeviceId")
        set(value) {
        _builder.deviceId = value
      }
    /**
     * `string device_id = 2;`
     */
    public fun clearDeviceId() {
      _builder.clearDeviceId()
    }

    /**
     * `string user_id = 3;`
     */
    public var userId: kotlin.String
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `string user_id = 3;`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * `.digitalkey.hub.v1.PhoneVendor vendor = 4;`
     */
    public var vendor: digitalkey.hub.v1.Hub.PhoneVendor
      @kotlin.jvm.JvmName("getVendor")
        get() = _builder.vendor
      @kotlin.jvm.JvmName("setVendor")
        set(value) {
        _builder.vendor = value
      }
    public var vendorValue: kotlin.Int
      @kotlin.jvm.JvmName("getVendorValue")
        get() = _builder.vendorValue
      @kotlin.jvm.JvmName("setVendorValue")
        set(value) {
        _builder.vendorValue = value
      }
    /**
     * `.digitalkey.hub.v1.PhoneVendor vendor = 4;`
     */
    public fun clearVendor() {
      _builder.clearVendor()
    }

    /**
     * `.digitalkey.hub.v1.Protocol protocol = 5;`
     */
    public var protocol: digitalkey.hub.v1.Hub.Protocol
      @kotlin.jvm.JvmName("getProtocol")
        get() = _builder.protocol
      @kotlin.jvm.JvmName("setProtocol")
        set(value) {
        _builder.protocol = value
      }
    public var protocolValue: kotlin.Int
      @kotlin.jvm.JvmName("getProtocolValue")
        get() = _builder.protocolValue
      @kotlin.jvm.JvmName("setProtocolValue")
        set(value) {
        _builder.protocolValue = value
      }
    /**
     * `.digitalkey.hub.v1.Protocol protocol = 5;`
     */
    public fun clearProtocol() {
      _builder.clearProtocol()
    }

    /**
     * `.digitalkey.hub.v1.KeyType key_type = 6;`
     */
    public var keyType: digitalkey.hub.v1.Hub.KeyType
      @kotlin.jvm.JvmName("getKeyType")
        get() = _builder.keyType
      @kotlin.jvm.JvmName("setKeyType")
        set(value) {
        _builder.keyType = value
      }
    public var keyTypeValue: kotlin.Int
      @kotlin.jvm.JvmName("getKeyTypeValue")
        get() = _builder.keyTypeValue
      @kotlin.jvm.JvmName("setKeyTypeValue")
        set(value) {
        _builder.keyTypeValue = value
      }
    /**
     * `.digitalkey.hub.v1.KeyType key_type = 6;`
     */
    public fun clearKeyType() {
      _builder.clearKeyType()
    }

    /**
     * `.digitalkey.hub.v1.AccessLevel access_level = 7;`
     */
    public var accessLevel: digitalkey.hub.v1.Hub.AccessLevel
      @kotlin.jvm.JvmName("getAccessLevel")
        get() = _builder.accessLevel
      @kotlin.jvm.JvmName("setAccessLevel")
        set(value) {
        _builder.accessLevel = value
      }
    /**
     * `.digitalkey.hub.v1.AccessLevel access_level = 7;`
     */
    public fun clearAccessLevel() {
      _builder.clearAccessLevel()
    }
    /**
     * `.digitalkey.hub.v1.AccessLevel access_level = 7;`
     * @return Whether the accessLevel field is set.
     */
    public fun hasAccessLevel(): kotlin.Boolean {
      return _builder.hasAccessLevel()
    }

    public val BindKeyRequestKt.Dsl.accessLevelOrNull: digitalkey.hub.v1.Hub.AccessLevel?
      get() = _builder.accessLevelOrNull

    /**
     * ```
     * 设备SE公钥 (DER)
     * ```
     *
     * `bytes device_pubkey = 8;`
     */
    public var devicePubkey: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getDevicePubkey")
        get() = _builder.devicePubkey
      @kotlin.jvm.JvmName("setDevicePubkey")
        set(value) {
        _builder.devicePubkey = value
      }
    /**
     * ```
     * 设备SE公钥 (DER)
     * ```
     *
     * `bytes device_pubkey = 8;`
     */
    public fun clearDevicePubkey() {
      _builder.clearDevicePubkey()
    }

    /**
     * `int64 valid_from = 9;`
     */
    public var validFrom: kotlin.Long
      @kotlin.jvm.JvmName("getValidFrom")
        get() = _builder.validFrom
      @kotlin.jvm.JvmName("setValidFrom")
        set(value) {
        _builder.validFrom = value
      }
    /**
     * `int64 valid_from = 9;`
     */
    public fun clearValidFrom() {
      _builder.clearValidFrom()
    }

    /**
     * `int64 valid_until = 10;`
     */
    public var validUntil: kotlin.Long
      @kotlin.jvm.JvmName("getValidUntil")
        get() = _builder.validUntil
      @kotlin.jvm.JvmName("setValidUntil")
        set(value) {
        _builder.validUntil = value
      }
    /**
     * `int64 valid_until = 10;`
     */
    public fun clearValidUntil() {
      _builder.clearValidUntil()
    }

    /**
     * `string trace_id = 11;`
     */
    public var traceId: kotlin.String
      @kotlin.jvm.JvmName("getTraceId")
        get() = _builder.traceId
      @kotlin.jvm.JvmName("setTraceId")
        set(value) {
        _builder.traceId = value
      }
    /**
     * `string trace_id = 11;`
     */
    public fun clearTraceId() {
      _builder.clearTraceId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.hub.v1.Hub.BindKeyRequest.copy(block: `digitalkey.hub.v1`.BindKeyRequestKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.BindKeyRequest =
  `digitalkey.hub.v1`.BindKeyRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val digitalkey.hub.v1.Hub.BindKeyRequestOrBuilder.accessLevelOrNull: digitalkey.hub.v1.Hub.AccessLevel?
  get() = if (hasAccessLevel()) getAccessLevel() else null

