// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hub.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.hub.v1;

@kotlin.jvm.JvmName("-initializecallbackRequest")
public inline fun callbackRequest(block: digitalkey.hub.v1.CallbackRequestKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.CallbackRequest =
  digitalkey.hub.v1.CallbackRequestKt.Dsl._create(digitalkey.hub.v1.Hub.CallbackRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.hub.v1.CallbackRequest`
 */
public object CallbackRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.hub.v1.Hub.CallbackRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.hub.v1.Hub.CallbackRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.hub.v1.Hub.CallbackRequest = _builder.build()

    /**
     * `.digitalkey.hub.v1.PhoneVendor vendor = 1;`
     */
    public var vendor: digitalkey.hub.v1.Hub.PhoneVendor
      @kotlin.jvm.JvmName("getVendor")
        get() = _builder.vendor
      @kotlin.jvm.JvmName("setVendor")
        set(value) {
        _builder.vendor = value
      }
    public var vendorValue: kotlin.Int
      @kotlin.jvm.JvmName("getVendorValue")
        get() = _builder.vendorValue
      @kotlin.jvm.JvmName("setVendorValue")
        set(value) {
        _builder.vendorValue = value
      }
    /**
     * `.digitalkey.hub.v1.PhoneVendor vendor = 1;`
     */
    public fun clearVendor() {
      _builder.clearVendor()
    }

    /**
     * `.digitalkey.hub.v1.Protocol protocol = 2;`
     */
    public var protocol: digitalkey.hub.v1.Hub.Protocol
      @kotlin.jvm.JvmName("getProtocol")
        get() = _builder.protocol
      @kotlin.jvm.JvmName("setProtocol")
        set(value) {
        _builder.protocol = value
      }
    public var protocolValue: kotlin.Int
      @kotlin.jvm.JvmName("getProtocolValue")
        get() = _builder.protocolValue
      @kotlin.jvm.JvmName("setProtocolValue")
        set(value) {
        _builder.protocolValue = value
      }
    /**
     * `.digitalkey.hub.v1.Protocol protocol = 2;`
     */
    public fun clearProtocol() {
      _builder.clearProtocol()
    }

    /**
     * `string operation = 3;`
     */
    public var operation: kotlin.String
      @kotlin.jvm.JvmName("getOperation")
        get() = _builder.operation
      @kotlin.jvm.JvmName("setOperation")
        set(value) {
        _builder.operation = value
      }
    /**
     * `string operation = 3;`
     */
    public fun clearOperation() {
      _builder.clearOperation()
    }

    /**
     * `bytes payload = 4;`
     */
    public var payload: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getPayload")
        get() = _builder.payload
      @kotlin.jvm.JvmName("setPayload")
        set(value) {
        _builder.payload = value
      }
    /**
     * `bytes payload = 4;`
     */
    public fun clearPayload() {
      _builder.clearPayload()
    }

    /**
     * `string callback_id = 5;`
     */
    public var callbackId: kotlin.String
      @kotlin.jvm.JvmName("getCallbackId")
        get() = _builder.callbackId
      @kotlin.jvm.JvmName("setCallbackId")
        set(value) {
        _builder.callbackId = value
      }
    /**
     * `string callback_id = 5;`
     */
    public fun clearCallbackId() {
      _builder.clearCallbackId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.hub.v1.Hub.CallbackRequest.copy(block: `digitalkey.hub.v1`.CallbackRequestKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.CallbackRequest =
  `digitalkey.hub.v1`.CallbackRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

