// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hub.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.hub.v1;

@kotlin.jvm.JvmName("-initializecancelShareRequest")
public inline fun cancelShareRequest(block: digitalkey.hub.v1.CancelShareRequestKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.CancelShareRequest =
  digitalkey.hub.v1.CancelShareRequestKt.Dsl._create(digitalkey.hub.v1.Hub.CancelShareRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.hub.v1.CancelShareRequest`
 */
public object CancelShareRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.hub.v1.Hub.CancelShareRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.hub.v1.Hub.CancelShareRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.hub.v1.Hub.CancelShareRequest = _builder.build()

    /**
     * `string share_id = 1;`
     */
    public var shareId: kotlin.String
      @kotlin.jvm.JvmName("getShareId")
        get() = _builder.shareId
      @kotlin.jvm.JvmName("setShareId")
        set(value) {
        _builder.shareId = value
      }
    /**
     * `string share_id = 1;`
     */
    public fun clearShareId() {
      _builder.clearShareId()
    }

    /**
     * `string trace_id = 2;`
     */
    public var traceId: kotlin.String
      @kotlin.jvm.JvmName("getTraceId")
        get() = _builder.traceId
      @kotlin.jvm.JvmName("setTraceId")
        set(value) {
        _builder.traceId = value
      }
    /**
     * `string trace_id = 2;`
     */
    public fun clearTraceId() {
      _builder.clearTraceId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.hub.v1.Hub.CancelShareRequest.copy(block: `digitalkey.hub.v1`.CancelShareRequestKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.CancelShareRequest =
  `digitalkey.hub.v1`.CancelShareRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

