// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hub.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.hub.v1;

@kotlin.jvm.JvmName("-initializecontrolCommandResponse")
public inline fun controlCommandResponse(block: digitalkey.hub.v1.ControlCommandResponseKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.ControlCommandResponse =
  digitalkey.hub.v1.ControlCommandResponseKt.Dsl._create(digitalkey.hub.v1.Hub.ControlCommandResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.hub.v1.ControlCommandResponse`
 */
public object ControlCommandResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.hub.v1.Hub.ControlCommandResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.hub.v1.Hub.ControlCommandResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.hub.v1.Hub.ControlCommandResponse = _builder.build()

    /**
     * `string cmd_id = 1;`
     */
    public var cmdId: kotlin.String
      @kotlin.jvm.JvmName("getCmdId")
        get() = _builder.cmdId
      @kotlin.jvm.JvmName("setCmdId")
        set(value) {
        _builder.cmdId = value
      }
    /**
     * `string cmd_id = 1;`
     */
    public fun clearCmdId() {
      _builder.clearCmdId()
    }

    /**
     * `int32 result_code = 2;`
     */
    public var resultCode: kotlin.Int
      @kotlin.jvm.JvmName("getResultCode")
        get() = _builder.resultCode
      @kotlin.jvm.JvmName("setResultCode")
        set(value) {
        _builder.resultCode = value
      }
    /**
     * `int32 result_code = 2;`
     */
    public fun clearResultCode() {
      _builder.clearResultCode()
    }

    /**
     * `string error_msg = 3;`
     */
    public var errorMsg: kotlin.String
      @kotlin.jvm.JvmName("getErrorMsg")
        get() = _builder.errorMsg
      @kotlin.jvm.JvmName("setErrorMsg")
        set(value) {
        _builder.errorMsg = value
      }
    /**
     * `string error_msg = 3;`
     */
    public fun clearErrorMsg() {
      _builder.clearErrorMsg()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.hub.v1.Hub.ControlCommandResponse.copy(block: `digitalkey.hub.v1`.ControlCommandResponseKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.ControlCommandResponse =
  `digitalkey.hub.v1`.ControlCommandResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

