// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hub.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.hub.v1;

@kotlin.jvm.JvmName("-initializecontrolCommandRequest")
public inline fun controlCommandRequest(block: digitalkey.hub.v1.ControlCommandRequestKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.ControlCommandRequest =
  digitalkey.hub.v1.ControlCommandRequestKt.Dsl._create(digitalkey.hub.v1.Hub.ControlCommandRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.hub.v1.ControlCommandRequest`
 */
public object ControlCommandRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.hub.v1.Hub.ControlCommandRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.hub.v1.Hub.ControlCommandRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.hub.v1.Hub.ControlCommandRequest = _builder.build()

    /**
     * `string vehicle_id = 1;`
     */
    public var vehicleId: kotlin.String
      @kotlin.jvm.JvmName("getVehicleId")
        get() = _builder.vehicleId
      @kotlin.jvm.JvmName("setVehicleId")
        set(value) {
        _builder.vehicleId = value
      }
    /**
     * `string vehicle_id = 1;`
     */
    public fun clearVehicleId() {
      _builder.clearVehicleId()
    }

    /**
     * `string user_id = 2;`
     */
    public var userId: kotlin.String
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `string user_id = 2;`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * `string key_id = 3;`
     */
    public var keyId: kotlin.String
      @kotlin.jvm.JvmName("getKeyId")
        get() = _builder.keyId
      @kotlin.jvm.JvmName("setKeyId")
        set(value) {
        _builder.keyId = value
      }
    /**
     * `string key_id = 3;`
     */
    public fun clearKeyId() {
      _builder.clearKeyId()
    }

    /**
     * ```
     * unlock/lock/engine_on/engine_off/trunk/climate/find
     * ```
     *
     * `string action = 4;`
     */
    public var action: kotlin.String
      @kotlin.jvm.JvmName("getAction")
        get() = _builder.action
      @kotlin.jvm.JvmName("setAction")
        set(value) {
        _builder.action = value
      }
    /**
     * ```
     * unlock/lock/engine_on/engine_off/trunk/climate/find
     * ```
     *
     * `string action = 4;`
     */
    public fun clearAction() {
      _builder.clearAction()
    }

    /**
     * ```
     * JSON params
     * ```
     *
     * `bytes params = 5;`
     */
    public var params: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getParams")
        get() = _builder.params
      @kotlin.jvm.JvmName("setParams")
        set(value) {
        _builder.params = value
      }
    /**
     * ```
     * JSON params
     * ```
     *
     * `bytes params = 5;`
     */
    public fun clearParams() {
      _builder.clearParams()
    }

    /**
     * ```
     * 1=NFC 2=BLE 3=UWB 4=Remote 5=Edge
     * ```
     *
     * `int32 source = 6;`
     */
    public var source: kotlin.Int
      @kotlin.jvm.JvmName("getSource")
        get() = _builder.source
      @kotlin.jvm.JvmName("setSource")
        set(value) {
        _builder.source = value
      }
    /**
     * ```
     * 1=NFC 2=BLE 3=UWB 4=Remote 5=Edge
     * ```
     *
     * `int32 source = 6;`
     */
    public fun clearSource() {
      _builder.clearSource()
    }

    /**
     * `string trace_id = 7;`
     */
    public var traceId: kotlin.String
      @kotlin.jvm.JvmName("getTraceId")
        get() = _builder.traceId
      @kotlin.jvm.JvmName("setTraceId")
        set(value) {
        _builder.traceId = value
      }
    /**
     * `string trace_id = 7;`
     */
    public fun clearTraceId() {
      _builder.clearTraceId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.hub.v1.Hub.ControlCommandRequest.copy(block: `digitalkey.hub.v1`.ControlCommandRequestKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.ControlCommandRequest =
  `digitalkey.hub.v1`.ControlCommandRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

