// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hub.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.hub.v1;

@kotlin.jvm.JvmName("-initializecreateShareResponse")
public inline fun createShareResponse(block: digitalkey.hub.v1.CreateShareResponseKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.CreateShareResponse =
  digitalkey.hub.v1.CreateShareResponseKt.Dsl._create(digitalkey.hub.v1.Hub.CreateShareResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.hub.v1.CreateShareResponse`
 */
public object CreateShareResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.hub.v1.Hub.CreateShareResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.hub.v1.Hub.CreateShareResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.hub.v1.Hub.CreateShareResponse = _builder.build()

    /**
     * `string share_id = 1;`
     */
    public var shareId: kotlin.String
      @kotlin.jvm.JvmName("getShareId")
        get() = _builder.shareId
      @kotlin.jvm.JvmName("setShareId")
        set(value) {
        _builder.shareId = value
      }
    /**
     * `string share_id = 1;`
     */
    public fun clearShareId() {
      _builder.clearShareId()
    }

    /**
     * ```
     * 6位数字分享码 (为空to_user_id时生成)
     * ```
     *
     * `string share_code = 2;`
     */
    public var shareCode: kotlin.String
      @kotlin.jvm.JvmName("getShareCode")
        get() = _builder.shareCode
      @kotlin.jvm.JvmName("setShareCode")
        set(value) {
        _builder.shareCode = value
      }
    /**
     * ```
     * 6位数字分享码 (为空to_user_id时生成)
     * ```
     *
     * `string share_code = 2;`
     */
    public fun clearShareCode() {
      _builder.clearShareCode()
    }

    /**
     * ```
     * CCC Mailbox sharing URL (仅CCC协议使用)
     * ```
     *
     * `string sharing_url = 3;`
     */
    public var sharingUrl: kotlin.String
      @kotlin.jvm.JvmName("getSharingUrl")
        get() = _builder.sharingUrl
      @kotlin.jvm.JvmName("setSharingUrl")
        set(value) {
        _builder.sharingUrl = value
      }
    /**
     * ```
     * CCC Mailbox sharing URL (仅CCC协议使用)
     * ```
     *
     * `string sharing_url = 3;`
     */
    public fun clearSharingUrl() {
      _builder.clearSharingUrl()
    }

    /**
     * `string error_code = 4;`
     */
    public var errorCode: kotlin.String
      @kotlin.jvm.JvmName("getErrorCode")
        get() = _builder.errorCode
      @kotlin.jvm.JvmName("setErrorCode")
        set(value) {
        _builder.errorCode = value
      }
    /**
     * `string error_code = 4;`
     */
    public fun clearErrorCode() {
      _builder.clearErrorCode()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.hub.v1.Hub.CreateShareResponse.copy(block: `digitalkey.hub.v1`.CreateShareResponseKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.CreateShareResponse =
  `digitalkey.hub.v1`.CreateShareResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

