// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hub.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.hub.v1;

@kotlin.jvm.JvmName("-initializedigitalKey")
public inline fun digitalKey(block: digitalkey.hub.v1.DigitalKeyKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.DigitalKey =
  digitalkey.hub.v1.DigitalKeyKt.Dsl._create(digitalkey.hub.v1.Hub.DigitalKey.newBuilder()).apply { block() }._build()
/**
 * ```
 * 统一密钥模型
 * ```
 *
 * Protobuf type `digitalkey.hub.v1.DigitalKey`
 */
public object DigitalKeyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.hub.v1.Hub.DigitalKey.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.hub.v1.Hub.DigitalKey.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.hub.v1.Hub.DigitalKey = _builder.build()

    /**
     * `string key_id = 1;`
     */
    public var keyId: kotlin.String
      @kotlin.jvm.JvmName("getKeyId")
        get() = _builder.keyId
      @kotlin.jvm.JvmName("setKeyId")
        set(value) {
        _builder.keyId = value
      }
    /**
     * `string key_id = 1;`
     */
    public fun clearKeyId() {
      _builder.clearKeyId()
    }

    /**
     * `string vehicle_id = 2;`
     */
    public var vehicleId: kotlin.String
      @kotlin.jvm.JvmName("getVehicleId")
        get() = _builder.vehicleId
      @kotlin.jvm.JvmName("setVehicleId")
        set(value) {
        _builder.vehicleId = value
      }
    /**
     * `string vehicle_id = 2;`
     */
    public fun clearVehicleId() {
      _builder.clearVehicleId()
    }

    /**
     * `string device_id = 3;`
     */
    public var deviceId: kotlin.String
      @kotlin.jvm.JvmName("getDeviceId")
        get() = _builder.deviceId
      @kotlin.jvm.JvmName("setDeviceId")
        set(value) {
        _builder.deviceId = value
      }
    /**
     * `string device_id = 3;`
     */
    public fun clearDeviceId() {
      _builder.clearDeviceId()
    }

    /**
     * `string user_id = 4;`
     */
    public var userId: kotlin.String
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `string user_id = 4;`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * `.digitalkey.hub.v1.KeyType key_type = 5;`
     */
    public var keyType: digitalkey.hub.v1.Hub.KeyType
      @kotlin.jvm.JvmName("getKeyType")
        get() = _builder.keyType
      @kotlin.jvm.JvmName("setKeyType")
        set(value) {
        _builder.keyType = value
      }
    public var keyTypeValue: kotlin.Int
      @kotlin.jvm.JvmName("getKeyTypeValue")
        get() = _builder.keyTypeValue
      @kotlin.jvm.JvmName("setKeyTypeValue")
        set(value) {
        _builder.keyTypeValue = value
      }
    /**
     * `.digitalkey.hub.v1.KeyType key_type = 5;`
     */
    public fun clearKeyType() {
      _builder.clearKeyType()
    }

    /**
     * `.digitalkey.hub.v1.Protocol protocol = 6;`
     */
    public var protocol: digitalkey.hub.v1.Hub.Protocol
      @kotlin.jvm.JvmName("getProtocol")
        get() = _builder.protocol
      @kotlin.jvm.JvmName("setProtocol")
        set(value) {
        _builder.protocol = value
      }
    public var protocolValue: kotlin.Int
      @kotlin.jvm.JvmName("getProtocolValue")
        get() = _builder.protocolValue
      @kotlin.jvm.JvmName("setProtocolValue")
        set(value) {
        _builder.protocolValue = value
      }
    /**
     * `.digitalkey.hub.v1.Protocol protocol = 6;`
     */
    public fun clearProtocol() {
      _builder.clearProtocol()
    }

    /**
     * `.digitalkey.hub.v1.AccessLevel access_level = 7;`
     */
    public var accessLevel: digitalkey.hub.v1.Hub.AccessLevel
      @kotlin.jvm.JvmName("getAccessLevel")
        get() = _builder.accessLevel
      @kotlin.jvm.JvmName("setAccessLevel")
        set(value) {
        _builder.accessLevel = value
      }
    /**
     * `.digitalkey.hub.v1.AccessLevel access_level = 7;`
     */
    public fun clearAccessLevel() {
      _builder.clearAccessLevel()
    }
    /**
     * `.digitalkey.hub.v1.AccessLevel access_level = 7;`
     * @return Whether the accessLevel field is set.
     */
    public fun hasAccessLevel(): kotlin.Boolean {
      return _builder.hasAccessLevel()
    }

    public val DigitalKeyKt.Dsl.accessLevelOrNull: digitalkey.hub.v1.Hub.AccessLevel?
      get() = _builder.accessLevelOrNull

    /**
     * ```
     * mm, 0=无限制
     * ```
     *
     * `int32 distance_limit = 8;`
     */
    public var distanceLimit: kotlin.Int
      @kotlin.jvm.JvmName("getDistanceLimit")
        get() = _builder.distanceLimit
      @kotlin.jvm.JvmName("setDistanceLimit")
        set(value) {
        _builder.distanceLimit = value
      }
    /**
     * ```
     * mm, 0=无限制
     * ```
     *
     * `int32 distance_limit = 8;`
     */
    public fun clearDistanceLimit() {
      _builder.clearDistanceLimit()
    }

    /**
     * `.digitalkey.hub.v1.TimeRestriction time_restriction = 9;`
     */
    public var timeRestriction: digitalkey.hub.v1.Hub.TimeRestriction
      @kotlin.jvm.JvmName("getTimeRestriction")
        get() = _builder.timeRestriction
      @kotlin.jvm.JvmName("setTimeRestriction")
        set(value) {
        _builder.timeRestriction = value
      }
    /**
     * `.digitalkey.hub.v1.TimeRestriction time_restriction = 9;`
     */
    public fun clearTimeRestriction() {
      _builder.clearTimeRestriction()
    }
    /**
     * `.digitalkey.hub.v1.TimeRestriction time_restriction = 9;`
     * @return Whether the timeRestriction field is set.
     */
    public fun hasTimeRestriction(): kotlin.Boolean {
      return _builder.hasTimeRestriction()
    }

    public val DigitalKeyKt.Dsl.timeRestrictionOrNull: digitalkey.hub.v1.Hub.TimeRestriction?
      get() = _builder.timeRestrictionOrNull

    /**
     * `int32 max_uses = 10;`
     */
    public var maxUses: kotlin.Int
      @kotlin.jvm.JvmName("getMaxUses")
        get() = _builder.maxUses
      @kotlin.jvm.JvmName("setMaxUses")
        set(value) {
        _builder.maxUses = value
      }
    /**
     * `int32 max_uses = 10;`
     */
    public fun clearMaxUses() {
      _builder.clearMaxUses()
    }

    /**
     * `int32 used_count = 11;`
     */
    public var usedCount: kotlin.Int
      @kotlin.jvm.JvmName("getUsedCount")
        get() = _builder.usedCount
      @kotlin.jvm.JvmName("setUsedCount")
        set(value) {
        _builder.usedCount = value
      }
    /**
     * `int32 used_count = 11;`
     */
    public fun clearUsedCount() {
      _builder.clearUsedCount()
    }

    /**
     * `int32 key_version = 12;`
     */
    public var keyVersion: kotlin.Int
      @kotlin.jvm.JvmName("getKeyVersion")
        get() = _builder.keyVersion
      @kotlin.jvm.JvmName("setKeyVersion")
        set(value) {
        _builder.keyVersion = value
      }
    /**
     * `int32 key_version = 12;`
     */
    public fun clearKeyVersion() {
      _builder.clearKeyVersion()
    }

    /**
     * `.digitalkey.hub.v1.KeyStatus status = 13;`
     */
    public var status: digitalkey.hub.v1.Hub.KeyStatus
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    public var statusValue: kotlin.Int
      @kotlin.jvm.JvmName("getStatusValue")
        get() = _builder.statusValue
      @kotlin.jvm.JvmName("setStatusValue")
        set(value) {
        _builder.statusValue = value
      }
    /**
     * `.digitalkey.hub.v1.KeyStatus status = 13;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * ```
     * unix timestamp
     * ```
     *
     * `int64 valid_from = 14;`
     */
    public var validFrom: kotlin.Long
      @kotlin.jvm.JvmName("getValidFrom")
        get() = _builder.validFrom
      @kotlin.jvm.JvmName("setValidFrom")
        set(value) {
        _builder.validFrom = value
      }
    /**
     * ```
     * unix timestamp
     * ```
     *
     * `int64 valid_from = 14;`
     */
    public fun clearValidFrom() {
      _builder.clearValidFrom()
    }

    /**
     * `int64 valid_until = 15;`
     */
    public var validUntil: kotlin.Long
      @kotlin.jvm.JvmName("getValidUntil")
        get() = _builder.validUntil
      @kotlin.jvm.JvmName("setValidUntil")
        set(value) {
        _builder.validUntil = value
      }
    /**
     * `int64 valid_until = 15;`
     */
    public fun clearValidUntil() {
      _builder.clearValidUntil()
    }

    /**
     * `int64 created_at = 16;`
     */
    public var createdAt: kotlin.Long
      @kotlin.jvm.JvmName("getCreatedAt")
        get() = _builder.createdAt
      @kotlin.jvm.JvmName("setCreatedAt")
        set(value) {
        _builder.createdAt = value
      }
    /**
     * `int64 created_at = 16;`
     */
    public fun clearCreatedAt() {
      _builder.clearCreatedAt()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.hub.v1.Hub.DigitalKey.copy(block: `digitalkey.hub.v1`.DigitalKeyKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.DigitalKey =
  `digitalkey.hub.v1`.DigitalKeyKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val digitalkey.hub.v1.Hub.DigitalKeyOrBuilder.accessLevelOrNull: digitalkey.hub.v1.Hub.AccessLevel?
  get() = if (hasAccessLevel()) getAccessLevel() else null

public val digitalkey.hub.v1.Hub.DigitalKeyOrBuilder.timeRestrictionOrNull: digitalkey.hub.v1.Hub.TimeRestriction?
  get() = if (hasTimeRestriction()) getTimeRestriction() else null

