// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hub.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.hub.v1;

@kotlin.jvm.JvmName("-initializeforwardResponse")
public inline fun forwardResponse(block: digitalkey.hub.v1.ForwardResponseKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.ForwardResponse =
  digitalkey.hub.v1.ForwardResponseKt.Dsl._create(digitalkey.hub.v1.Hub.ForwardResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.hub.v1.ForwardResponse`
 */
public object ForwardResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.hub.v1.Hub.ForwardResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.hub.v1.Hub.ForwardResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.hub.v1.Hub.ForwardResponse = _builder.build()

    /**
     * ```
     * 厂商响应 (协议转换后)
     * ```
     *
     * `bytes payload = 1;`
     */
    public var payload: com.google.protobuf.ByteString
      @kotlin.jvm.JvmName("getPayload")
        get() = _builder.payload
      @kotlin.jvm.JvmName("setPayload")
        set(value) {
        _builder.payload = value
      }
    /**
     * ```
     * 厂商响应 (协议转换后)
     * ```
     *
     * `bytes payload = 1;`
     */
    public fun clearPayload() {
      _builder.clearPayload()
    }

    /**
     * `string error_code = 2;`
     */
    public var errorCode: kotlin.String
      @kotlin.jvm.JvmName("getErrorCode")
        get() = _builder.errorCode
      @kotlin.jvm.JvmName("setErrorCode")
        set(value) {
        _builder.errorCode = value
      }
    /**
     * `string error_code = 2;`
     */
    public fun clearErrorCode() {
      _builder.clearErrorCode()
    }

    /**
     * `string error_msg = 3;`
     */
    public var errorMsg: kotlin.String
      @kotlin.jvm.JvmName("getErrorMsg")
        get() = _builder.errorMsg
      @kotlin.jvm.JvmName("setErrorMsg")
        set(value) {
        _builder.errorMsg = value
      }
    /**
     * `string error_msg = 3;`
     */
    public fun clearErrorMsg() {
      _builder.clearErrorMsg()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.hub.v1.Hub.ForwardResponse.copy(block: `digitalkey.hub.v1`.ForwardResponseKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.ForwardResponse =
  `digitalkey.hub.v1`.ForwardResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

