// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hub.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.hub.v1;

@kotlin.jvm.JvmName("-initializegetKeyRequest")
public inline fun getKeyRequest(block: digitalkey.hub.v1.GetKeyRequestKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.GetKeyRequest =
  digitalkey.hub.v1.GetKeyRequestKt.Dsl._create(digitalkey.hub.v1.Hub.GetKeyRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.hub.v1.GetKeyRequest`
 */
public object GetKeyRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.hub.v1.Hub.GetKeyRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.hub.v1.Hub.GetKeyRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.hub.v1.Hub.GetKeyRequest = _builder.build()

    /**
     * `string key_id = 1;`
     */
    public var keyId: kotlin.String
      @kotlin.jvm.JvmName("getKeyId")
        get() = _builder.keyId
      @kotlin.jvm.JvmName("setKeyId")
        set(value) {
        _builder.keyId = value
      }
    /**
     * `string key_id = 1;`
     */
    public fun clearKeyId() {
      _builder.clearKeyId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.hub.v1.Hub.GetKeyRequest.copy(block: `digitalkey.hub.v1`.GetKeyRequestKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.GetKeyRequest =
  `digitalkey.hub.v1`.GetKeyRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

