// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hub.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.hub.v1;

@kotlin.jvm.JvmName("-initializegetKeyResponse")
public inline fun getKeyResponse(block: digitalkey.hub.v1.GetKeyResponseKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.GetKeyResponse =
  digitalkey.hub.v1.GetKeyResponseKt.Dsl._create(digitalkey.hub.v1.Hub.GetKeyResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.hub.v1.GetKeyResponse`
 */
public object GetKeyResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.hub.v1.Hub.GetKeyResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.hub.v1.Hub.GetKeyResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.hub.v1.Hub.GetKeyResponse = _builder.build()

    /**
     * `.digitalkey.hub.v1.DigitalKey key = 1;`
     */
    public var key: digitalkey.hub.v1.Hub.DigitalKey
      @kotlin.jvm.JvmName("getKey")
        get() = _builder.key
      @kotlin.jvm.JvmName("setKey")
        set(value) {
        _builder.key = value
      }
    /**
     * `.digitalkey.hub.v1.DigitalKey key = 1;`
     */
    public fun clearKey() {
      _builder.clearKey()
    }
    /**
     * `.digitalkey.hub.v1.DigitalKey key = 1;`
     * @return Whether the key field is set.
     */
    public fun hasKey(): kotlin.Boolean {
      return _builder.hasKey()
    }

    public val GetKeyResponseKt.Dsl.keyOrNull: digitalkey.hub.v1.Hub.DigitalKey?
      get() = _builder.keyOrNull

    /**
     * `string error_code = 2;`
     */
    public var errorCode: kotlin.String
      @kotlin.jvm.JvmName("getErrorCode")
        get() = _builder.errorCode
      @kotlin.jvm.JvmName("setErrorCode")
        set(value) {
        _builder.errorCode = value
      }
    /**
     * `string error_code = 2;`
     */
    public fun clearErrorCode() {
      _builder.clearErrorCode()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.hub.v1.Hub.GetKeyResponse.copy(block: `digitalkey.hub.v1`.GetKeyResponseKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.GetKeyResponse =
  `digitalkey.hub.v1`.GetKeyResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val digitalkey.hub.v1.Hub.GetKeyResponseOrBuilder.keyOrNull: digitalkey.hub.v1.Hub.DigitalKey?
  get() = if (hasKey()) getKey() else null

