// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hub.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.hub.v1;

@kotlin.jvm.JvmName("-initializegetShareResponse")
public inline fun getShareResponse(block: digitalkey.hub.v1.GetShareResponseKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.GetShareResponse =
  digitalkey.hub.v1.GetShareResponseKt.Dsl._create(digitalkey.hub.v1.Hub.GetShareResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.hub.v1.GetShareResponse`
 */
public object GetShareResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.hub.v1.Hub.GetShareResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.hub.v1.Hub.GetShareResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.hub.v1.Hub.GetShareResponse = _builder.build()

    /**
     * `string share_id = 1;`
     */
    public var shareId: kotlin.String
      @kotlin.jvm.JvmName("getShareId")
        get() = _builder.shareId
      @kotlin.jvm.JvmName("setShareId")
        set(value) {
        _builder.shareId = value
      }
    /**
     * `string share_id = 1;`
     */
    public fun clearShareId() {
      _builder.clearShareId()
    }

    /**
     * `string key_id = 2;`
     */
    public var keyId: kotlin.String
      @kotlin.jvm.JvmName("getKeyId")
        get() = _builder.keyId
      @kotlin.jvm.JvmName("setKeyId")
        set(value) {
        _builder.keyId = value
      }
    /**
     * `string key_id = 2;`
     */
    public fun clearKeyId() {
      _builder.clearKeyId()
    }

    /**
     * `string from_user_id = 3;`
     */
    public var fromUserId: kotlin.String
      @kotlin.jvm.JvmName("getFromUserId")
        get() = _builder.fromUserId
      @kotlin.jvm.JvmName("setFromUserId")
        set(value) {
        _builder.fromUserId = value
      }
    /**
     * `string from_user_id = 3;`
     */
    public fun clearFromUserId() {
      _builder.clearFromUserId()
    }

    /**
     * `.digitalkey.hub.v1.AccessLevel access_level = 4;`
     */
    public var accessLevel: digitalkey.hub.v1.Hub.AccessLevel
      @kotlin.jvm.JvmName("getAccessLevel")
        get() = _builder.accessLevel
      @kotlin.jvm.JvmName("setAccessLevel")
        set(value) {
        _builder.accessLevel = value
      }
    /**
     * `.digitalkey.hub.v1.AccessLevel access_level = 4;`
     */
    public fun clearAccessLevel() {
      _builder.clearAccessLevel()
    }
    /**
     * `.digitalkey.hub.v1.AccessLevel access_level = 4;`
     * @return Whether the accessLevel field is set.
     */
    public fun hasAccessLevel(): kotlin.Boolean {
      return _builder.hasAccessLevel()
    }

    public val GetShareResponseKt.Dsl.accessLevelOrNull: digitalkey.hub.v1.Hub.AccessLevel?
      get() = _builder.accessLevelOrNull

    /**
     * `int64 valid_from = 5;`
     */
    public var validFrom: kotlin.Long
      @kotlin.jvm.JvmName("getValidFrom")
        get() = _builder.validFrom
      @kotlin.jvm.JvmName("setValidFrom")
        set(value) {
        _builder.validFrom = value
      }
    /**
     * `int64 valid_from = 5;`
     */
    public fun clearValidFrom() {
      _builder.clearValidFrom()
    }

    /**
     * `int64 valid_until = 6;`
     */
    public var validUntil: kotlin.Long
      @kotlin.jvm.JvmName("getValidUntil")
        get() = _builder.validUntil
      @kotlin.jvm.JvmName("setValidUntil")
        set(value) {
        _builder.validUntil = value
      }
    /**
     * `int64 valid_until = 6;`
     */
    public fun clearValidUntil() {
      _builder.clearValidUntil()
    }

    /**
     * `string error_code = 7;`
     */
    public var errorCode: kotlin.String
      @kotlin.jvm.JvmName("getErrorCode")
        get() = _builder.errorCode
      @kotlin.jvm.JvmName("setErrorCode")
        set(value) {
        _builder.errorCode = value
      }
    /**
     * `string error_code = 7;`
     */
    public fun clearErrorCode() {
      _builder.clearErrorCode()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.hub.v1.Hub.GetShareResponse.copy(block: `digitalkey.hub.v1`.GetShareResponseKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.GetShareResponse =
  `digitalkey.hub.v1`.GetShareResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val digitalkey.hub.v1.Hub.GetShareResponseOrBuilder.accessLevelOrNull: digitalkey.hub.v1.Hub.AccessLevel?
  get() = if (hasAccessLevel()) getAccessLevel() else null

