// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hub.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.hub.v1;

@kotlin.jvm.JvmName("-initializegetShareRequest")
public inline fun getShareRequest(block: digitalkey.hub.v1.GetShareRequestKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.GetShareRequest =
  digitalkey.hub.v1.GetShareRequestKt.Dsl._create(digitalkey.hub.v1.Hub.GetShareRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.hub.v1.GetShareRequest`
 */
public object GetShareRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.hub.v1.Hub.GetShareRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.hub.v1.Hub.GetShareRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.hub.v1.Hub.GetShareRequest = _builder.build()

    /**
     * `string share_id = 1;`
     */
    public var shareId: kotlin.String
      @kotlin.jvm.JvmName("getShareId")
        get() = _builder.shareId
      @kotlin.jvm.JvmName("setShareId")
        set(value) {
        _builder.shareId = value
      }
    /**
     * `string share_id = 1;`
     */
    public fun clearShareId() {
      _builder.clearShareId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.hub.v1.Hub.GetShareRequest.copy(block: `digitalkey.hub.v1`.GetShareRequestKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.GetShareRequest =
  `digitalkey.hub.v1`.GetShareRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

