// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hub.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.hub.v1;

@kotlin.jvm.JvmName("-initializehealthCheckResponse")
public inline fun healthCheckResponse(block: digitalkey.hub.v1.HealthCheckResponseKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.HealthCheckResponse =
  digitalkey.hub.v1.HealthCheckResponseKt.Dsl._create(digitalkey.hub.v1.Hub.HealthCheckResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.hub.v1.HealthCheckResponse`
 */
public object HealthCheckResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.hub.v1.Hub.HealthCheckResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.hub.v1.Hub.HealthCheckResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.hub.v1.Hub.HealthCheckResponse = _builder.build()

    /**
     * `bool healthy = 1;`
     */
    public var healthy: kotlin.Boolean
      @kotlin.jvm.JvmName("getHealthy")
        get() = _builder.healthy
      @kotlin.jvm.JvmName("setHealthy")
        set(value) {
        _builder.healthy = value
      }
    /**
     * `bool healthy = 1;`
     */
    public fun clearHealthy() {
      _builder.clearHealthy()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class AdaptersProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * `repeated .digitalkey.hub.v1.AdapterStatus adapters = 2;`
     */
     public val adapters: com.google.protobuf.kotlin.DslList<digitalkey.hub.v1.Hub.AdapterStatus, AdaptersProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.adaptersList
      )
    /**
     * `repeated .digitalkey.hub.v1.AdapterStatus adapters = 2;`
     * @param value The adapters to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAdapters")
    public fun com.google.protobuf.kotlin.DslList<digitalkey.hub.v1.Hub.AdapterStatus, AdaptersProxy>.add(value: digitalkey.hub.v1.Hub.AdapterStatus) {
      _builder.addAdapters(value)
    }
    /**
     * `repeated .digitalkey.hub.v1.AdapterStatus adapters = 2;`
     * @param value The adapters to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAdapters")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<digitalkey.hub.v1.Hub.AdapterStatus, AdaptersProxy>.plusAssign(value: digitalkey.hub.v1.Hub.AdapterStatus) {
      add(value)
    }
    /**
     * `repeated .digitalkey.hub.v1.AdapterStatus adapters = 2;`
     * @param values The adapters to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllAdapters")
    public fun com.google.protobuf.kotlin.DslList<digitalkey.hub.v1.Hub.AdapterStatus, AdaptersProxy>.addAll(values: kotlin.collections.Iterable<digitalkey.hub.v1.Hub.AdapterStatus>) {
      _builder.addAllAdapters(values)
    }
    /**
     * `repeated .digitalkey.hub.v1.AdapterStatus adapters = 2;`
     * @param values The adapters to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllAdapters")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<digitalkey.hub.v1.Hub.AdapterStatus, AdaptersProxy>.plusAssign(values: kotlin.collections.Iterable<digitalkey.hub.v1.Hub.AdapterStatus>) {
      addAll(values)
    }
    /**
     * `repeated .digitalkey.hub.v1.AdapterStatus adapters = 2;`
     * @param index The index to set the value at.
     * @param value The adapters to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setAdapters")
    public operator fun com.google.protobuf.kotlin.DslList<digitalkey.hub.v1.Hub.AdapterStatus, AdaptersProxy>.set(index: kotlin.Int, value: digitalkey.hub.v1.Hub.AdapterStatus) {
      _builder.setAdapters(index, value)
    }
    /**
     * `repeated .digitalkey.hub.v1.AdapterStatus adapters = 2;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearAdapters")
    public fun com.google.protobuf.kotlin.DslList<digitalkey.hub.v1.Hub.AdapterStatus, AdaptersProxy>.clear() {
      _builder.clearAdapters()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.hub.v1.Hub.HealthCheckResponse.copy(block: `digitalkey.hub.v1`.HealthCheckResponseKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.HealthCheckResponse =
  `digitalkey.hub.v1`.HealthCheckResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

