// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hub.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.hub.v1;

@kotlin.jvm.JvmName("-initializehealthCheckRequest")
public inline fun healthCheckRequest(block: digitalkey.hub.v1.HealthCheckRequestKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.HealthCheckRequest =
  digitalkey.hub.v1.HealthCheckRequestKt.Dsl._create(digitalkey.hub.v1.Hub.HealthCheckRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.hub.v1.HealthCheckRequest`
 */
public object HealthCheckRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.hub.v1.Hub.HealthCheckRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.hub.v1.Hub.HealthCheckRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.hub.v1.Hub.HealthCheckRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.hub.v1.Hub.HealthCheckRequest.copy(block: `digitalkey.hub.v1`.HealthCheckRequestKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.HealthCheckRequest =
  `digitalkey.hub.v1`.HealthCheckRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

