// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hub.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.hub.v1;

@kotlin.jvm.JvmName("-initializelistKeysRequest")
public inline fun listKeysRequest(block: digitalkey.hub.v1.ListKeysRequestKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.ListKeysRequest =
  digitalkey.hub.v1.ListKeysRequestKt.Dsl._create(digitalkey.hub.v1.Hub.ListKeysRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.hub.v1.ListKeysRequest`
 */
public object ListKeysRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.hub.v1.Hub.ListKeysRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.hub.v1.Hub.ListKeysRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.hub.v1.Hub.ListKeysRequest = _builder.build()

    /**
     * `string vehicle_id = 1;`
     */
    public var vehicleId: kotlin.String
      @kotlin.jvm.JvmName("getVehicleId")
        get() = _builder.vehicleId
      @kotlin.jvm.JvmName("setVehicleId")
        set(value) {
        _builder.vehicleId = value
      }
    /**
     * `string vehicle_id = 1;`
     */
    public fun clearVehicleId() {
      _builder.clearVehicleId()
    }

    /**
     * `string user_id = 2;`
     */
    public var userId: kotlin.String
      @kotlin.jvm.JvmName("getUserId")
        get() = _builder.userId
      @kotlin.jvm.JvmName("setUserId")
        set(value) {
        _builder.userId = value
      }
    /**
     * `string user_id = 2;`
     */
    public fun clearUserId() {
      _builder.clearUserId()
    }

    /**
     * `.digitalkey.hub.v1.KeyStatus status = 3;`
     */
    public var status: digitalkey.hub.v1.Hub.KeyStatus
      @kotlin.jvm.JvmName("getStatus")
        get() = _builder.status
      @kotlin.jvm.JvmName("setStatus")
        set(value) {
        _builder.status = value
      }
    public var statusValue: kotlin.Int
      @kotlin.jvm.JvmName("getStatusValue")
        get() = _builder.statusValue
      @kotlin.jvm.JvmName("setStatusValue")
        set(value) {
        _builder.statusValue = value
      }
    /**
     * `.digitalkey.hub.v1.KeyStatus status = 3;`
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }

    /**
     * `int32 page_size = 4;`
     */
    public var pageSize: kotlin.Int
      @kotlin.jvm.JvmName("getPageSize")
        get() = _builder.pageSize
      @kotlin.jvm.JvmName("setPageSize")
        set(value) {
        _builder.pageSize = value
      }
    /**
     * `int32 page_size = 4;`
     */
    public fun clearPageSize() {
      _builder.clearPageSize()
    }

    /**
     * `string page_token = 5;`
     */
    public var pageToken: kotlin.String
      @kotlin.jvm.JvmName("getPageToken")
        get() = _builder.pageToken
      @kotlin.jvm.JvmName("setPageToken")
        set(value) {
        _builder.pageToken = value
      }
    /**
     * `string page_token = 5;`
     */
    public fun clearPageToken() {
      _builder.clearPageToken()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.hub.v1.Hub.ListKeysRequest.copy(block: `digitalkey.hub.v1`.ListKeysRequestKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.ListKeysRequest =
  `digitalkey.hub.v1`.ListKeysRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

