// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hub.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.hub.v1;

@kotlin.jvm.JvmName("-initializeresumeKeyRequest")
public inline fun resumeKeyRequest(block: digitalkey.hub.v1.ResumeKeyRequestKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.ResumeKeyRequest =
  digitalkey.hub.v1.ResumeKeyRequestKt.Dsl._create(digitalkey.hub.v1.Hub.ResumeKeyRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.hub.v1.ResumeKeyRequest`
 */
public object ResumeKeyRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.hub.v1.Hub.ResumeKeyRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.hub.v1.Hub.ResumeKeyRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.hub.v1.Hub.ResumeKeyRequest = _builder.build()

    /**
     * `string key_id = 1;`
     */
    public var keyId: kotlin.String
      @kotlin.jvm.JvmName("getKeyId")
        get() = _builder.keyId
      @kotlin.jvm.JvmName("setKeyId")
        set(value) {
        _builder.keyId = value
      }
    /**
     * `string key_id = 1;`
     */
    public fun clearKeyId() {
      _builder.clearKeyId()
    }

    /**
     * `string trace_id = 2;`
     */
    public var traceId: kotlin.String
      @kotlin.jvm.JvmName("getTraceId")
        get() = _builder.traceId
      @kotlin.jvm.JvmName("setTraceId")
        set(value) {
        _builder.traceId = value
      }
    /**
     * `string trace_id = 2;`
     */
    public fun clearTraceId() {
      _builder.clearTraceId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.hub.v1.Hub.ResumeKeyRequest.copy(block: `digitalkey.hub.v1`.ResumeKeyRequestKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.ResumeKeyRequest =
  `digitalkey.hub.v1`.ResumeKeyRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

