// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hub.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.hub.v1;

@kotlin.jvm.JvmName("-initializesuspendKeyResponse")
public inline fun suspendKeyResponse(block: digitalkey.hub.v1.SuspendKeyResponseKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.SuspendKeyResponse =
  digitalkey.hub.v1.SuspendKeyResponseKt.Dsl._create(digitalkey.hub.v1.Hub.SuspendKeyResponse.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.hub.v1.SuspendKeyResponse`
 */
public object SuspendKeyResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.hub.v1.Hub.SuspendKeyResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.hub.v1.Hub.SuspendKeyResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.hub.v1.Hub.SuspendKeyResponse = _builder.build()

    /**
     * `string error_code = 1;`
     */
    public var errorCode: kotlin.String
      @kotlin.jvm.JvmName("getErrorCode")
        get() = _builder.errorCode
      @kotlin.jvm.JvmName("setErrorCode")
        set(value) {
        _builder.errorCode = value
      }
    /**
     * `string error_code = 1;`
     */
    public fun clearErrorCode() {
      _builder.clearErrorCode()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.hub.v1.Hub.SuspendKeyResponse.copy(block: `digitalkey.hub.v1`.SuspendKeyResponseKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.SuspendKeyResponse =
  `digitalkey.hub.v1`.SuspendKeyResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

