// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hub.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.hub.v1;

@kotlin.jvm.JvmName("-initializetimeRestriction")
public inline fun timeRestriction(block: digitalkey.hub.v1.TimeRestrictionKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.TimeRestriction =
  digitalkey.hub.v1.TimeRestrictionKt.Dsl._create(digitalkey.hub.v1.Hub.TimeRestriction.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.hub.v1.TimeRestriction`
 */
public object TimeRestrictionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.hub.v1.Hub.TimeRestriction.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.hub.v1.Hub.TimeRestriction.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.hub.v1.Hub.TimeRestriction = _builder.build()

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    public class WeekdaysProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * ```
     * 1-7
     * ```
     *
     * `repeated int32 weekdays = 1;`
     */
     public val weekdays: com.google.protobuf.kotlin.DslList<kotlin.Int, WeekdaysProxy>
      @kotlin.jvm.JvmSynthetic
  get() = com.google.protobuf.kotlin.DslList(
        _builder.weekdaysList
      )
    /**
     * ```
     * 1-7
     * ```
     *
     * `repeated int32 weekdays = 1;`
     * @param value The weekdays to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addWeekdays")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, WeekdaysProxy>.add(value: kotlin.Int) {
      _builder.addWeekdays(value)
    }/**
     * ```
     * 1-7
     * ```
     *
     * `repeated int32 weekdays = 1;`
     * @param value The weekdays to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignWeekdays")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, WeekdaysProxy>.plusAssign(value: kotlin.Int) {
      add(value)
    }/**
     * ```
     * 1-7
     * ```
     *
     * `repeated int32 weekdays = 1;`
     * @param values The weekdays to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("addAllWeekdays")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, WeekdaysProxy>.addAll(values: kotlin.collections.Iterable<kotlin.Int>) {
      _builder.addAllWeekdays(values)
    }/**
     * ```
     * 1-7
     * ```
     *
     * `repeated int32 weekdays = 1;`
     * @param values The weekdays to add.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("plusAssignAllWeekdays")
    @Suppress("NOTHING_TO_INLINE")
    public inline operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, WeekdaysProxy>.plusAssign(values: kotlin.collections.Iterable<kotlin.Int>) {
      addAll(values)
    }/**
     * ```
     * 1-7
     * ```
     *
     * `repeated int32 weekdays = 1;`
     * @param index The index to set the value at.
     * @param value The weekdays to set.
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("setWeekdays")
    public operator fun com.google.protobuf.kotlin.DslList<kotlin.Int, WeekdaysProxy>.set(index: kotlin.Int, value: kotlin.Int) {
      _builder.setWeekdays(index, value)
    }/**
     * ```
     * 1-7
     * ```
     *
     * `repeated int32 weekdays = 1;`
     */
    @kotlin.jvm.JvmSynthetic
@kotlin.jvm.JvmName("clearWeekdays")
    public fun com.google.protobuf.kotlin.DslList<kotlin.Int, WeekdaysProxy>.clear() {
      _builder.clearWeekdays()
    }
    /**
     * ```
     * "08:00"
     * ```
     *
     * `string start_time = 2;`
     */
    public var startTime: kotlin.String
      @kotlin.jvm.JvmName("getStartTime")
        get() = _builder.startTime
      @kotlin.jvm.JvmName("setStartTime")
        set(value) {
        _builder.startTime = value
      }
    /**
     * ```
     * "08:00"
     * ```
     *
     * `string start_time = 2;`
     */
    public fun clearStartTime() {
      _builder.clearStartTime()
    }

    /**
     * ```
     * "18:00"
     * ```
     *
     * `string end_time = 3;`
     */
    public var endTime: kotlin.String
      @kotlin.jvm.JvmName("getEndTime")
        get() = _builder.endTime
      @kotlin.jvm.JvmName("setEndTime")
        set(value) {
        _builder.endTime = value
      }
    /**
     * ```
     * "18:00"
     * ```
     *
     * `string end_time = 3;`
     */
    public fun clearEndTime() {
      _builder.clearEndTime()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.hub.v1.Hub.TimeRestriction.copy(block: `digitalkey.hub.v1`.TimeRestrictionKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.TimeRestriction =
  `digitalkey.hub.v1`.TimeRestrictionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

