// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hub.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.hub.v1;

@kotlin.jvm.JvmName("-initializevehicleStatusRequest")
public inline fun vehicleStatusRequest(block: digitalkey.hub.v1.VehicleStatusRequestKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.VehicleStatusRequest =
  digitalkey.hub.v1.VehicleStatusRequestKt.Dsl._create(digitalkey.hub.v1.Hub.VehicleStatusRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.hub.v1.VehicleStatusRequest`
 */
public object VehicleStatusRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.hub.v1.Hub.VehicleStatusRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.hub.v1.Hub.VehicleStatusRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.hub.v1.Hub.VehicleStatusRequest = _builder.build()

    /**
     * `string vehicle_id = 1;`
     */
    public var vehicleId: kotlin.String
      @kotlin.jvm.JvmName("getVehicleId")
        get() = _builder.vehicleId
      @kotlin.jvm.JvmName("setVehicleId")
        set(value) {
        _builder.vehicleId = value
      }
    /**
     * `string vehicle_id = 1;`
     */
    public fun clearVehicleId() {
      _builder.clearVehicleId()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.hub.v1.Hub.VehicleStatusRequest.copy(block: `digitalkey.hub.v1`.VehicleStatusRequestKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.VehicleStatusRequest =
  `digitalkey.hub.v1`.VehicleStatusRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

