// Generated by the protocol buffer compiler. DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: hub.proto

@file:com.google.protobuf.Generated
// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package digitalkey.hub.v1;

@kotlin.jvm.JvmName("-initializevehicleStatusUpdate")
public inline fun vehicleStatusUpdate(block: digitalkey.hub.v1.VehicleStatusUpdateKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.VehicleStatusUpdate =
  digitalkey.hub.v1.VehicleStatusUpdateKt.Dsl._create(digitalkey.hub.v1.Hub.VehicleStatusUpdate.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `digitalkey.hub.v1.VehicleStatusUpdate`
 */
public object VehicleStatusUpdateKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: digitalkey.hub.v1.Hub.VehicleStatusUpdate.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
      internal fun _create(builder: digitalkey.hub.v1.Hub.VehicleStatusUpdate.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
  @kotlin.PublishedApi
    internal fun _build(): digitalkey.hub.v1.Hub.VehicleStatusUpdate = _builder.build()

    /**
     * `string vehicle_id = 1;`
     */
    public var vehicleId: kotlin.String
      @kotlin.jvm.JvmName("getVehicleId")
        get() = _builder.vehicleId
      @kotlin.jvm.JvmName("setVehicleId")
        set(value) {
        _builder.vehicleId = value
      }
    /**
     * `string vehicle_id = 1;`
     */
    public fun clearVehicleId() {
      _builder.clearVehicleId()
    }

    /**
     * `int32 lock_status = 2;`
     */
    public var lockStatus: kotlin.Int
      @kotlin.jvm.JvmName("getLockStatus")
        get() = _builder.lockStatus
      @kotlin.jvm.JvmName("setLockStatus")
        set(value) {
        _builder.lockStatus = value
      }
    /**
     * `int32 lock_status = 2;`
     */
    public fun clearLockStatus() {
      _builder.clearLockStatus()
    }

    /**
     * `int32 engine_status = 3;`
     */
    public var engineStatus: kotlin.Int
      @kotlin.jvm.JvmName("getEngineStatus")
        get() = _builder.engineStatus
      @kotlin.jvm.JvmName("setEngineStatus")
        set(value) {
        _builder.engineStatus = value
      }
    /**
     * `int32 engine_status = 3;`
     */
    public fun clearEngineStatus() {
      _builder.clearEngineStatus()
    }

    /**
     * `int32 door_status = 4;`
     */
    public var doorStatus: kotlin.Int
      @kotlin.jvm.JvmName("getDoorStatus")
        get() = _builder.doorStatus
      @kotlin.jvm.JvmName("setDoorStatus")
        set(value) {
        _builder.doorStatus = value
      }
    /**
     * `int32 door_status = 4;`
     */
    public fun clearDoorStatus() {
      _builder.clearDoorStatus()
    }

    /**
     * `int32 window_status = 5;`
     */
    public var windowStatus: kotlin.Int
      @kotlin.jvm.JvmName("getWindowStatus")
        get() = _builder.windowStatus
      @kotlin.jvm.JvmName("setWindowStatus")
        set(value) {
        _builder.windowStatus = value
      }
    /**
     * `int32 window_status = 5;`
     */
    public fun clearWindowStatus() {
      _builder.clearWindowStatus()
    }

    /**
     * `int32 battery_pct = 6;`
     */
    public var batteryPct: kotlin.Int
      @kotlin.jvm.JvmName("getBatteryPct")
        get() = _builder.batteryPct
      @kotlin.jvm.JvmName("setBatteryPct")
        set(value) {
        _builder.batteryPct = value
      }
    /**
     * `int32 battery_pct = 6;`
     */
    public fun clearBatteryPct() {
      _builder.clearBatteryPct()
    }

    /**
     * `int32 interior_temp = 7;`
     */
    public var interiorTemp: kotlin.Int
      @kotlin.jvm.JvmName("getInteriorTemp")
        get() = _builder.interiorTemp
      @kotlin.jvm.JvmName("setInteriorTemp")
        set(value) {
        _builder.interiorTemp = value
      }
    /**
     * `int32 interior_temp = 7;`
     */
    public fun clearInteriorTemp() {
      _builder.clearInteriorTemp()
    }

    /**
     * `int32 alarm_status = 8;`
     */
    public var alarmStatus: kotlin.Int
      @kotlin.jvm.JvmName("getAlarmStatus")
        get() = _builder.alarmStatus
      @kotlin.jvm.JvmName("setAlarmStatus")
        set(value) {
        _builder.alarmStatus = value
      }
    /**
     * `int32 alarm_status = 8;`
     */
    public fun clearAlarmStatus() {
      _builder.clearAlarmStatus()
    }

    /**
     * `double latitude = 9;`
     */
    public var latitude: kotlin.Double
      @kotlin.jvm.JvmName("getLatitude")
        get() = _builder.latitude
      @kotlin.jvm.JvmName("setLatitude")
        set(value) {
        _builder.latitude = value
      }
    /**
     * `double latitude = 9;`
     */
    public fun clearLatitude() {
      _builder.clearLatitude()
    }

    /**
     * `double longitude = 10;`
     */
    public var longitude: kotlin.Double
      @kotlin.jvm.JvmName("getLongitude")
        get() = _builder.longitude
      @kotlin.jvm.JvmName("setLongitude")
        set(value) {
        _builder.longitude = value
      }
    /**
     * `double longitude = 10;`
     */
    public fun clearLongitude() {
      _builder.clearLongitude()
    }

    /**
     * `int64 timestamp = 11;`
     */
    public var timestamp: kotlin.Long
      @kotlin.jvm.JvmName("getTimestamp")
        get() = _builder.timestamp
      @kotlin.jvm.JvmName("setTimestamp")
        set(value) {
        _builder.timestamp = value
      }
    /**
     * `int64 timestamp = 11;`
     */
    public fun clearTimestamp() {
      _builder.clearTimestamp()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun digitalkey.hub.v1.Hub.VehicleStatusUpdate.copy(block: `digitalkey.hub.v1`.VehicleStatusUpdateKt.Dsl.() -> kotlin.Unit): digitalkey.hub.v1.Hub.VehicleStatusUpdate =
  `digitalkey.hub.v1`.VehicleStatusUpdateKt.Dsl._create(this.toBuilder()).apply { block() }._build()

