---
apiVersion: v1
kind: Service
metadata:
  name: hub
  namespace: dkcs-prod
  labels:
    app: hub
    app.kubernetes.io/name: hub
    app.kubernetes.io/component: gateway
spec:
  selector:
    app: hub
  ports:
    - name: rest
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: grpc
      port: 9090
      targetPort: 9090
      protocol: TCP
    - name: metrics
      port: 9093
      targetPort: 9093
      protocol: TCP
  type: ClusterIP
